const axios = require('axios');

const dataToInsert = [

    {
  "personalnummer": 321679,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Irmgard Wilde",
  "adresse": "Litzowstr. 19, 22041 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1925-08-17"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 73,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1957-04-01"),
  "unternehmensaustritt": new Date("1983-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1985-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,

{
  "personalnummer": 976026,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Karin Wettengel",
  "adresse": "Bebelallee 70a, 22297 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1951-03-05"),
  "geheiratetAm": new Date("1984-04-19"),
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1978-04-15"),
  "unternehmensaustritt": new Date("1989-09-18"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2005-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "44 31 71"
}
,

{
  "personalnummer": 500396,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Erika Wallner",
  "adresse": "Harksheider Str. 135, 22399 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1937-04-26"),
  "geheiratetAm": new Date("1960-01-23"),
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-07-01"),
  "unternehmensaustritt": new Date("1989-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1993-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Tel.: 602 12 73"
}
,

{
  "personalnummer": 326991,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Annelies Wallek",
  "adresse": "Am Spitzwald 116, 21509 Glinde",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1934-07-26"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1979-04-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": new Date("1973-01-01"),
  "rentenbeginn": new Date("1994-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "711 90 79"
}
,

{
  "personalnummer": 318758,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Gerhard Wachsmuth",
  "adresse": "Rauschener Ring 7b, 22047 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1952-11-01"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1978-05-01"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2017-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0171 5858635"
}
,

{
  "personalnummer": 402703,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Giselbert von Gartzen",
  "adresse": "Schlankreye 21, 20144 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1940-04-23"),
  "geheiratetAm": new Date("1982-10-26"),
  "gesellschaft": "91",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-06-01"),
  "unternehmensaustritt": new Date("1986-10-31"),
  "ruhegeldfaehigAb": new Date("1961-05-01"),
  "rentenbeginn": new Date("1993-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,

{
  "personalnummer": 326777,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Gerda Stolley",
  "adresse": "Stammanstraße 2, 22303 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "geschieden",
  "geburtsdatum": new Date("1938-04-26"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1978-10-01"),
  "unternehmensaustritt": new Date("1990-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1998-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,
{
  "personalnummer": 115535,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Hans-Joachim Steffen",
  "adresse": "Rauchschwalbenweg 28, 22147 Hamburg",
  "geschlecht": "männlich",
  "familienstand": null,
  "geburtsdatum": new Date("1941-10-20"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-02-01"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": new Date("1968-03-01"),
  "rentenbeginn": new Date("2004-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,

{
  "personalnummer": 323592,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Liselotte Senst",
  "adresse": "Averhoffstraße 30, 22085 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1932-08-29"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1972-05-15"),
  "unternehmensaustritt": new Date("1990-06-30"),
  "ruhegeldfaehigAb": new Date("1972-05-15"),
  "rentenbeginn": new Date("1992-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,

{
  "personalnummer": 500417,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Erika Schulz",
  "adresse": "c/o Beate Schulz-Montag, Wiesenerstr. 36, 12101 Berlin",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1945-08-31"),
  "geheiratetAm": new Date("1958-07-18"),
  "gesellschaft": "91",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1961-09-12"),
  "unternehmensaustritt": new Date("1984-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,

{
  "personalnummer": 132134,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Rainer Gowasch",
  "adresse": "Karousou Xrist. 6, G50100 Kozani Griechenland",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1942-09-02"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-06-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "00002461029084"
}
,

{
  "personalnummer": 137738,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Bernd Grän",
  "adresse": "Neugrabener Bahnhofstraße 111, 21149 Hamburg",
  "geschlecht": "männlich",
  "familienstand": null,
  "geburtsdatum": new Date("1944-02-07"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-07-16"),
  "unternehmensaustritt": new Date("1988-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,

{
  "personalnummer": 500369,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Helga Griesel",
  "adresse": "Friedlandstr 32, 25451 Quickborn",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1936-11-09"),
  "geheiratetAm": new Date("1964-06-18"),
  "gesellschaft": "91",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-07-01"),
  "unternehmensaustritt": new Date("1992-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1998-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 04106-672 19"
}
,

{
  "personalnummer": 500229,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Eva Großmann",
  "adresse": "c/o Bernd Grossmann, Dorfstr. 25, 85375 Neufahrn b. Freising",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1938-03-28"),
  "geheiratetAm": new Date("1957-09-14"),
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,

{
  "personalnummer": 976029,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Josef Hautmann",
  "adresse": "Enzianstraße 52, 82178 Puchheim",
  "geschlecht": "männlich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1941-07-14"),
  "geheiratetAm": new Date("1969-08-11"),
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-01-01"),
  "unternehmensaustritt": new Date("1988-08-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2022-02-24"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "08980072738"
}
,

{
  "personalnummer": 500515,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ingrid Heilenkötter",
  "adresse": "Bäckergasse 13, 48143 Münster",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1929-08-28"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 83,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1988-05-01"),
  "unternehmensaustritt": new Date("1996-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 322594,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Dieter Hoee",
  "adresse": "Am Heidberg 24, 22889 Tangstedt",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1943-02-16"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-04-01"),
  "unternehmensaustritt": new Date("1983-01-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2008-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 401640,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Helga Hönck",
  "adresse": "Wittland 5 A, 22589 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1931-03-28"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1959-01-30"),
  "unternehmensaustritt": new Date("1980-08-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1980-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500386,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Margret Kaiser",
  "adresse": "Strindbergweg 3c, 22587 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1940-08-03"),
  "geheiratetAm": new Date("1972-07-21"),
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-08-01"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 866143"
}
,

{
  "personalnummer": 136358,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Joachim Kaufmann",
  "adresse": "Kurzer Kamp 23, 22339 Hamburg",
  "geschlecht": "männlich",
  "familienstand": null,
  "geburtsdatum": new Date("1943-07-24"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-07-01"),
  "unternehmensaustritt": new Date("1986-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2006-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 321869,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Elke Kleff",
  "adresse": "Groten Hoff 12, 22359 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1939-11-14"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1963-11-07"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1999-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 168989,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ilse Köcher",
  "adresse": "Am Bäckfeld 20 a, 21335 Lüneburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1944-07-28"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1982-09-01"),
  "unternehmensaustritt": new Date("1987-05-14"),
  "ruhegeldfaehigAb": new Date("1976-03-01"),
  "rentenbeginn": new Date("1987-05-15"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 322529,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Vorruheständler",
  "name": "Hans-Georg Krangemann",
  "adresse": "Am Schulwald 19, 22415 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1929-02-26"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 71,
  "arbVerhRentTr": "10",
  "unternehmenseintritt": new Date("1960-11-01"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1992-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500552,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Inge Krüger",
  "adresse": "Perelstraße 214, 21031 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1939-07-15"),
  "geheiratetAm": new Date("1960-02-27"),
  "gesellschaft": "91",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-01-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2002-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500500,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ursel Lange",
  "adresse": "Spannskamp 25d, 22527 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1937-12-21"),
  "geheiratetAm": new Date("1959-08-28"),
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-05-01"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1994-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,
{
  "personalnummer": 327403,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Bernd Lewalter",
  "adresse": "Sierichstrasse 46, 22301 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1944-11-21"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1980-06-01"),
  "unternehmensaustritt": new Date("1990-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2009-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 976052,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Renate Loebert",
  "adresse": "Norderstr. 32, 24539 Neumünster",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1939-01-19"),
  "geheiratetAm": new Date("1965-06-04"),
  "gesellschaft": "91",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1965-03-01"),
  "unternehmensaustritt": new Date("1986-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 131946,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Teilübertragung auf Direktversicherung",
  "name": "Gerhard Lohse",
  "adresse": "Rahlstedter Straße 186e, 22143 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1938-03-24"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-07-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "677 65 82"
}
,

{
  "personalnummer": 326207,
  "aktuelleStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "alteStatusgruppe": null,
  "name": "Andrea Lotz",
  "adresse": "Hans-Dewitz-Ring 1, 21075 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1960-05-08"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1977-09-01"),
  "unternehmensaustritt": new Date("1989-11-30"),
  "ruhegeldfaehigAb": new Date("1980-07-05"),
  "rentenbeginn": new Date("1989-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,

{
  "personalnummer": 976066,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Christel Lübkert",
  "adresse": "Luchsstraße 29, 46535 Dinslaken",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1950-01-03"),
  "geheiratetAm": new Date("1971-08-06"),
  "gesellschaft": "91",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-01-01"),
  "unternehmensaustritt": new Date("1983-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2013-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 02064-1600317 oder 0176 10 14 1674"
}
,

{
  "personalnummer": 321323,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Eberhard March",
  "adresse": "Fritz-Reuter-Str. 9, 23843 Bad Oldesloe",
  "geschlecht": "männlich",
  "familienstand": "?",
  "geburtsdatum": new Date("1944-01-14"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-03-01"),
  "unternehmensaustritt": new Date("1985-09-30"),
  "ruhegeldfaehigAb": new Date("1968-03-01"),
  "rentenbeginn": new Date("2009-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 322008,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Elli-Jutta Michalski",
  "adresse": "Rechterallee 2, 25462 Rellingen",
  "geschlecht": "weiblich",
  "familienstand": "getr.",
  "geburtsdatum": new Date("1937-11-04"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-07-01"),
  "unternehmensaustritt": new Date("1979-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1997-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Auskunft zum Versorgungsausgleich"
}
,

{
  "personalnummer": 976062,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Eva Mosmann",
  "adresse": "c/o Lorenz Mosmann, Oberes Tor 21, 97237 Altertheim",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1950-08-11"),
  "geheiratetAm": new Date("1975-04-24"),
  "gesellschaft": "91",
  "versorgungsordnung": 74,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1964-01-01"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 04541-132233"
}
,

{
  "personalnummer": 325373,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ingeborg Plett",
  "adresse": "Vogt-Groth-Weg 75, 22609 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1929-10-10"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1950-01-01"),
  "unternehmensaustritt": new Date("1963-09-16"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1963-09-17"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 976063,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Maren Puffert",
  "adresse": "c/o Tina Puffert, Fischerweg 10, 4058 Basel/Schweiz",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1946-04-23"),
  "geheiratetAm": new Date("1973-03-16"),
  "gesellschaft": "91",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-03-01"),
  "unternehmensaustritt": new Date("1990-06-30"),
  "ruhegeldfaehigAb": new Date("1968-01-01"),
  "rentenbeginn": new Date("2000-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500509,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ingrid Rieß",
  "adresse": "Wohnpark Kastanienhof, Am Mittelfelde 102, 30519 Hannover",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1937-08-12"),
  "geheiratetAm": new Date("1958-10-31"),
  "gesellschaft": "91",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1951-11-01"),
  "unternehmensaustritt": new Date("1986-07-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Tochter"
}
,

{
  "personalnummer": 141762,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Hella Ritter",
  "adresse": "Bothmannstraße 4, 22047 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1938-02-07"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-07-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1998-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 693 36 50"
}
,
{
  "personalnummer": 500471,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Edith Schliestedt",
  "adresse": "c/o Seniorenzentrum Kapernau, Rennbahnstr. 51–53, 22111 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1939-04-17"),
  "geheiratetAm": new Date("1959-04-03"),
  "gesellschaft": "91",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1957-09-01"),
  "unternehmensaustritt": new Date("1989-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1993-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 672 61 82"
}
,
{
  "personalnummer": 281790,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Elisabeth Hunger",
  "adresse": "Hölderlinweg 6, 97941 Tauberbischofsheim",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1942-10-30"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1977-01-01"),
  "unternehmensaustritt": new Date("1985-06-30"),
  "ruhegeldfaehigAb": new Date("1968-08-01"),
  "rentenbeginn": new Date("2005-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 280677,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Karl Huober",
  "adresse": "Gartenstr. 20, 75382 Althengstett",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1937-10-29"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1962-04-01"),
  "unternehmensaustritt": new Date("1984-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1999-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500042,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Sigrid Irmler",
  "adresse": "c/o GGI GmbH Frau Alt-Günter, Eppendorfer Weg 204, 20251 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1934-05-28"),
  "geheiratetAm": new Date("1972-03-30"),
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-10-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1987-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Dr. Katrin Stieß, Kanzlei Norton Rose Fulbright LLP"
}
,

{
  "personalnummer": 116061,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Gudrun Kaergel",
  "adresse": "Jungfernburgstraße 8, 88131 Lindau",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1939-03-07"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 78,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1966-11-01"),
  "unternehmensaustritt": new Date("1983-01-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1999-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 083826089133"
}
,
{
  "personalnummer": 500470,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Rotraud Kettner",
  "adresse": "Trifelstraße 58, 67112 Mutterstadt",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1934-07-28"),
  "geheiratetAm": new Date("1960-11-25"),
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-08-01"),
  "unternehmensaustritt": new Date("1983-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1998-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,
{
  "personalnummer": 115808,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Monika Kisielewski",
  "adresse": "Hohenheimer Straße 11, 70771 Leinfelden/Echterdingen",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1944-02-04"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-01-01"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 280693,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Helga Klapper",
  "adresse": "Barbarastraße 5, 79106 Freiburg",
  "geschlecht": "weiblich",
  "familienstand": null,
  "geburtsdatum": new Date("1940-07-20"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1967-01-01"),
  "unternehmensaustritt": new Date("1985-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500420,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Marie-Johanna Knobloch",
  "adresse": "Teichäckerweg 12, 88339 Bad Waldsee",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1937-09-15"),
  "geheiratetAm": new Date("1962-02-17"),
  "gesellschaft": "61",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1983-04-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1984-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "07524-4094775"
}
,

{
  "personalnummer": 500512,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Hildegard Kühnling",
  "adresse": "c/o C. Piethe, Tiergartenstraße 1, 71032 Böblingen",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1931-12-29"),
  "geheiratetAm": new Date("1954-07-31"),
  "gesellschaft": "61",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1967-06-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1992-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500559,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ursula Kutzborski",
  "adresse": "Gutastraße 16, 70771 Leinfelden-Echterdingen",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1946-08-28"),
  "geheiratetAm": new Date("1970-01-01"),
  "gesellschaft": "61",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-10-01"),
  "unternehmensaustritt": new Date("1987-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2004-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "0711 79 79 529"
}
,

{
  "personalnummer": 116053,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Helga Maly",
  "adresse": "c/o Christina Maly, Am Buberlesbach 19, 70195 Stuttgart",
  "geschlecht": "weiblich",
  "familienstand": "gesch.",
  "geburtsdatum": new Date("1935-10-24"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1967-10-25"),
  "unternehmensaustritt": new Date("1987-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1995-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich"
}
,

{
  "personalnummer": 116319,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Rosemarie Meyer",
  "adresse": "Postfach 1212, 72581 Dettingen/Erms",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1938-06-02"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 78,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1962-01-15"),
  "unternehmensaustritt": new Date("1983-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1998-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "immer Postfach angeben, Telefon: 07123888268"
}
,

{
  "personalnummer": 403881,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Anneliese Plenz",
  "adresse": "c/o Frau Antje Plenz, Schönbühlstr. 42, 70188 Stuttgart",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1931-02-21"),
  "geheiratetAm": new Date("1957-10-03"),
  "gesellschaft": "61",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1954-03-22"),
  "unternehmensaustritt": new Date("1982-12-31"),
  "ruhegeldfaehigAb": new Date("1954-01-01"),
  "rentenbeginn": new Date("1983-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 07031 809 399"
}
,

{
  "personalnummer": 282053,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Sybille Plesch-Kinzler",
  "adresse": "Kirchbachstraße 9, 71229 Leonberg",
  "geschlecht": "weiblich",
  "familienstand": null,
  "geburtsdatum": new Date("1942-12-21"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-05-01"),
  "unternehmensaustritt": new Date("1985-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2008-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 283481,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Bernd Rau",
  "adresse": "Heidelberger Straße 132, 74080 Heilbronn-Böcking",
  "geschlecht": "männlich",
  "familienstand": "?",
  "geburtsdatum": new Date("1940-10-04"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1967-04-16"),
  "unternehmensaustritt": new Date("1983-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 403366,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Lore Rein",
  "adresse": "Am Lindele 43, 73230 Kirchheim",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1935-11-28"),
  "geheiratetAm": new Date("1958-06-16"),
  "gesellschaft": "61",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1957-09-15"),
  "unternehmensaustritt": new Date("1986-11-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1991-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 404900,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Rainer Riemann",
  "adresse": "Feldbergstraße 3, 79333 Teningen",
  "geschlecht": "männlich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1942-10-29"),
  "geheiratetAm": new Date("1974-08-19"),
  "gesellschaft": "61",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-07-01"),
  "unternehmensaustritt": new Date("1983-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1983-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Tel.: 07641-7106"
}
,

{
  "personalnummer": 280891,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Irmgard Riester",
  "adresse": "Im Asemwald 6/21, 70599 Stuttgart",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1931-05-18"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1959-06-29"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1991-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,

{
  "personalnummer": 500434,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Annemarie Ruczkowski",
  "adresse": "Stettiner Straße 35, 71032 Böblingen",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1937-12-02"),
  "geheiratetAm": new Date("1960-07-29"),
  "gesellschaft": "61",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1964-09-15"),
  "unternehmensaustritt": new Date("1985-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1994-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,

{
  "personalnummer": 403920,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ursula Rückert",
  "adresse": "Lortzingstraße 11, 40667 Meerbusch",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1937-05-15"),
  "geheiratetAm": new Date("1964-02-28"),
  "gesellschaft": "61",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-07-01"),
  "unternehmensaustritt": new Date("1983-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1998-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Schwiegersohn: Herr Mariner, Telefon: 0170 23 67 762"
}
,

{
  "personalnummer": 282020,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Sebastian Sage",
  "adresse": "Menzelstraße 35b, 70192 Stuttgart",
  "geschlecht": "männlich",
  "familienstand": null,
  "geburtsdatum": new Date("1947-01-27"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-09-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2012-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,

{
  "personalnummer": 500479,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ruth Sandbiller",
  "adresse": "Gluckstr. 27, 73660 Urbach",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1930-01-14"),
  "geheiratetAm": new Date("1951-10-11"),
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-01-01"),
  "unternehmensaustritt": new Date("1981-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1991-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,

{
  "personalnummer": 280271,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Einald Sandreuther",
  "adresse": "Krausmühle 1, 67283 Obrigheim",
  "geschlecht": "männlich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1934-01-16"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1964-10-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": new Date("1955-03-01"),
  "rentenbeginn": new Date("1999-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Tel. 06359-2222"
}
,

{
  "personalnummer": 976020,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Hildegard Schoppe",
  "adresse": "Camberleystraße 51, 74321 Bietigheim-Bissingen",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1939-03-02"),
  "geheiratetAm": new Date("1961-09-30"),
  "gesellschaft": "61",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-03-01"),
  "unternehmensaustritt": new Date("1985-01-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1999-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,

{
  "personalnummer": 500253,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ingeborg Schultes",
  "adresse": "Wittenberger Weg 2, 68309 Mannheim",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1935-08-24"),
  "geheiratetAm": new Date("1957-04-20"),
  "gesellschaft": "61",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1966-04-01"),
  "unternehmensaustritt": new Date("1984-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,

{
  "personalnummer": 976018,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Renate Seba",
  "adresse": "Stettener Straße 31, 71394 Kernen i.R.",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1936-08-05"),
  "geheiratetAm": new Date("1959-07-31"),
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-11-01"),
  "unternehmensaustritt": new Date("1982-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1995-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,

{
  "personalnummer": 281600,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Jürgen Seitz",
  "adresse": "Ruitstraße 12, 71691 Freiberg",
  "geschlecht": "männlich",
  "familienstand": "geschieden",
  "geburtsdatum": new Date("1946-09-26"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-02-01"),
  "unternehmensaustritt": new Date("1986-08-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2009-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich"
}
,

{
  "personalnummer": 976015,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Hella Settelmaier",
  "adresse": "Bautzener Weg 14, 68309 Mannheim",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1938-07-16"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1965-10-01"),
  "unternehmensaustritt": new Date("1986-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1997-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 116186,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Sigrid Stark",
  "adresse": "Wilhelm-Ziegler-Weg 26, 91541 Rothenburg ob der Tauber",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1948-06-14"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1985-09-15"),
  "ruhegeldfaehigAb": new Date("1968-04-01"),
  "rentenbeginn": new Date("2008-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 976033,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Waltraud Strauss",
  "adresse": "Friedenstraße 8, 89180 Berghuelen",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1938-07-13"),
  "geheiratetAm": new Date("1963-11-08"),
  "gesellschaft": "61",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-11-16"),
  "unternehmensaustritt": new Date("1980-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1998-01-07"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 281451,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Hubert Sumser",
  "adresse": "Neckarpromenade 15-528, 68167 Mannheim",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1938-08-15"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-09-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2003-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 282442,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Lothar Thürer",
  "adresse": "Theodor-Körner-Str. 2, 68723 Oftersheim",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1944-01-05"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-05-01"),
  "unternehmensaustritt": new Date("1980-03-31"),
  "ruhegeldfaehigAb": new Date("1966-08-01"),
  "rentenbeginn": new Date("2009-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500401,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Gisela Wagner",
  "adresse": "Robert-Bosch-Str. 2, 70192 Stuttgart",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1951-03-25"),
  "geheiratetAm": new Date("1984-06-29"),
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-07-01"),
  "unternehmensaustritt": new Date("1985-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2002-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0711-2261811"
}
,

{
  "personalnummer": 281840,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Jürgen Weller",
  "adresse": "Birkenstraße 41, 71155 Altdorf",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1940-07-08"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-01-01"),
  "unternehmensaustritt": new Date("1985-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2005-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 282145,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Peter Wetzel",
  "adresse": "Haydnstraße 19, 70734 Fellbach",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1939-07-21"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2002-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0711-574925"
}
,

{
  "personalnummer": 282384,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Heinz Windholz",
  "adresse": "Wormser Straße 51, 01309 Dresden",
  "geschlecht": "männlich",
  "familienstand": null,
  "geburtsdatum": new Date("1949-02-17"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-06-01"),
  "unternehmensaustritt": new Date("1985-08-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2015-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500448,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Fritz Wössner",
  "adresse": "Heilbronner Straße 35, 71732 Tamm",
  "geschlecht": "männlich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1937-05-05"),
  "geheiratetAm": new Date("1974-10-04"),
  "gesellschaft": "61",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-04-01"),
  "unternehmensaustritt": new Date("1980-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1998-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon 07141-603859"
}
,

{
  "personalnummer": 280396,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Fritz Wößner",
  "adresse": "Heilbronner Str. 35, 71732 Tamm-Hohenstange",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1937-05-05"),
  "geheiratetAm": new Date("1974-10-04"),
  "gesellschaft": "61",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-10-01"),
  "unternehmensaustritt": new Date("1985-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2002-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500554,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Rita Xander",
  "adresse": "Obere Zeilstraße 37, 74343 Kleinsachsenheim",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1947-08-01"),
  "geheiratetAm": new Date("1966-04-22"),
  "gesellschaft": "61",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-05-01"),
  "unternehmensaustritt": new Date("1981-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2003-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 07147 74 32"
}
,

{
  "personalnummer": 500546,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Renate Buhrz",
  "adresse": "Rehagenering 16d, 22949 Ammersbek",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1946-04-12"),
  "geheiratetAm": new Date("1970-03-20"),
  "gesellschaft": "81",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-07-01"),
  "unternehmensaustritt": new Date("1993-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1997-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "045323185"
}
,

{
  "personalnummer": 500513,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Gisela Heimann-Quaas",
  "adresse": "Bachstraße 18, 22941 Bargteheide",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1945-01-21"),
  "geheiratetAm": new Date("1973-04-06"),
  "gesellschaft": "81",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-01-01"),
  "unternehmensaustritt": new Date("1993-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 04532-5964"
}
,

{
  "personalnummer": 976016,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Christine Ackermann",
  "adresse": "Mahlhaus 5, 22159 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1928-12-16"),
  "geheiratetAm": new Date("1952-02-23"),
  "gesellschaft": "91",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1959-07-01"),
  "unternehmensaustritt": new Date("1992-11-30"),
  "ruhegeldfaehigAb": new Date("1954-01-01"),
  "rentenbeginn": new Date("1992-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 323753,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Brigitte Apollonio",
  "adresse": "Mittelweg 6, 21465 Reinbek",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1944-11-01"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-07-01"),
  "unternehmensaustritt": new Date("1986-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2006-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 323519,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Peter Appelt",
  "adresse": "Friedrichstraße 105, 10117 Berlin",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1943-07-25"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-03-15"),
  "unternehmensaustritt": new Date("1981-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2008-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500431,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Heidrun Bach",
  "adresse": "Große Elbstraße 57, 22767 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1955-03-13"),
  "geheiratetAm": new Date("1983-09-23"),
  "gesellschaft": "91",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-09-01"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1995-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 324095,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Alfred Bennecke",
  "adresse": "Teutonenweg 91a, 22453 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1934-07-11"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 71,
  "arbVerhRentTr": "10",
  "unternehmenseintritt": new Date("1957-03-12"),
  "unternehmensaustritt": new Date("1989-07-31"),
  "ruhegeldfaehigAb": new Date("1957-03-01"),
  "rentenbeginn": new Date("1994-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 404164,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Elisabeth Beyn",
  "adresse": "Am Feenteich 1, 22085 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1925-12-30"),
  "geheiratetAm": new Date("1959-03-26"),
  "gesellschaft": "91",
  "versorgungsordnung": 72,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1954-03-01"),
  "unternehmensaustritt": new Date("1977-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1977-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 229 95 01"
}
,

{
  "personalnummer": 323468,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Renate Blumberg",
  "adresse": "Kirschenallee 12, 23746 Kellenhusen",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1947-12-02"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-12-20"),
  "unternehmensaustritt": new Date("1982-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2008-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500478,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Gabriele Boekholt",
  "adresse": "Blumenau 52, 22089 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1943-05-21"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-01-01"),
  "unternehmensaustritt": new Date("1988-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1998-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 321729,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Marianne Braun",
  "adresse": "Breslauer Straße 12, 25479 Ellerau",
  "geschlecht": "weiblich",
  "familienstand": null,
  "geburtsdatum": new Date("1942-11-07"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-01-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 299781,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Teilübertragung auf Direktversicherung",
  "name": "Wilfried Bundt",
  "adresse": "Paschbergstraße 42, 21438 Brackel (Nordheide)",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1942-11-05"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-06-01"),
  "unternehmensaustritt": new Date("1987-12-31"),
  "ruhegeldfaehigAb": new Date("1972-07-01"),
  "rentenbeginn": new Date("2002-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}











    ];
    
     // Axios POST request function
    // Axios POST request function
async function insertData() {
  for (let i = 0; i < dataToInsert.length; i++) {
    const person = dataToInsert[i];

    try {
      const response = await axios.post(
        "http://localhost:4000/api/person",
        person
      );

      console.log(`✔️ Inserted personalnummer ${person.personalnummer}`);
    } catch (error) {
      // Wenn der Server geantwortet hat (HTTP-Fehlercode)
      if (error.response) {
        // 400 = existiert schon (so wie du es in deiner Route gebaut hast)
        if (error.response.status === 400) {
          console.warn(
            `⚠️ personalnummer ${person.personalnummer} exists – skipped`
          );
          continue; // optional, macht nur explizit "weiter" zur nächsten Person
        }

        // Andere HTTP-Fehler
        console.error(
          `❌ HTTP ${error.response.status} for personalnummer ${person.personalnummer}:`,
          error.response.data
        );
      } else {
        // Kein Response = z.B. Netzwerkfehler / Server nicht erreichbar
        console.error(
          `❌ Network/Unknown error for personalnummer ${person.personalnummer}:`,
          error.message
        );
      }
    }
  }

  console.log("✅ Import finished.");
}

    
    // Call the function to insert data
    insertData();