const axios = require('axios');

const dataToInsert = [

    {
  "personalnummer": 131953,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Dejan Cerovic",
  "adresse": "Bul. Arsenija Carnojevica 26/St 21, 11070 Novi Beograd Srbija",
  "geschlecht": "männlich",
  "familienstand": "gesch",
  "geburtsdatum": new Date("1932-02-13"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-08-01"),
  "unternehmensaustritt": new Date("1980-09-29"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1997-03-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2009-11-30"),
  "bemerkung": "Telefon: 0038-1112132937, Sommer Montenegro, Winter Serbien"
}
,

{
  "personalnummer": 125484,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Alice Cerwenka",
  "adresse": "Gartenstraße 15a, 22885 Barsbüttel",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1936-05-12"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1971-09-01"),
  "unternehmensaustritt": new Date("1993-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 132498,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Friedrich Choyne",
  "adresse": "Abrahamstr 32, 22145 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1937-01-03"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 71,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1962-08-15"),
  "unternehmensaustritt": new Date("1992-12-31"),
  "ruhegeldfaehigAb": new Date("1962-08-01"),
  "rentenbeginn": new Date("1997-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500446,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Gabriele Dehnkamp",
  "adresse": "Hodenberger Str. 37 A, 28355 Bremen",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1927-01-16"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 72,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1955-10-15"),
  "unternehmensaustritt": new Date("1982-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0421-259 798"
}
,

{
  "personalnummer": 976050,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Dr. Hiltrud Marschner-Schäfer",
  "adresse": "Justus-Brinkmann-Straße 103, 21029 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1940-12-08"),
  "geheiratetAm": new Date("1990-11-16"),
  "gesellschaft": "91",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-12-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2002-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "1. Ehefrau verstorben, VA rückgängig"
}
,

{
  "personalnummer": 404307,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Marie Luise Dzietko",
  "adresse": "Segeberger Chaussee 182a, 22851 Norderstedt",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1935-06-02"),
  "geheiratetAm": new Date("1963-04-11"),
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-07-01"),
  "unternehmensaustritt": new Date("1988-11-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1993-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 522 26 74"
}
,

{
  "personalnummer": 976012,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Gerda Galeazzi",
  "adresse": "Mühlendamm 7, 22087 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1934-06-11"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-04-01"),
  "unternehmensaustritt": new Date("1990-12-31"),
  "ruhegeldfaehigAb": new Date("1964-02-01"),
  "rentenbeginn": new Date("1995-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}

,

{
  "personalnummer": 335638,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Brigitte Giordan",
  "adresse": "Ole Tann 1, 25451 Quickborn",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1946-05-31"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-07-01"),
  "unternehmensaustritt": new Date("1982-07-23"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1982-07-24"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 976055,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Inga Götze",
  "adresse": "Lindenweg 133, 30966 Hemmingen",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1943-05-28"),
  "geheiratetAm": new Date("1974-05-28"),
  "gesellschaft": "M1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-01-01"),
  "unternehmensaustritt": new Date("1988-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 401279,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Josefine Müller",
  "adresse": "Klabundstr. 7, 81737 München",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1931-04-10"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-10-01"),
  "unternehmensaustritt": new Date("1983-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1984-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 254144,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Ursula Raithel",
  "adresse": "Herbststraße 24, 83080 Oberaudorf",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1939-09-13"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1965-04-01"),
  "unternehmensaustritt": new Date("1980-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1999-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "08003 2562"
}
,

{
  "personalnummer": 254169,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Anna Regensburger",
  "adresse": "Ehrenbreitsteiner Str. 59, 80993 München",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1926-07-08"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1966-04-01"),
  "unternehmensaustritt": new Date("1983-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1986-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 269035,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Elisabeth Ringeis",
  "adresse": "Neugablonzer Str. 64, 87600 Kaufbeuren",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1934-12-26"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-05-01"),
  "unternehmensaustritt": new Date("1985-09-13"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1985-09-14"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500451,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Lieselotte Röhrl",
  "adresse": "c/o Städtisches Bürgerheim, Münchener Straße 2, 82362 Weilheim",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1930-01-15"),
  "geheiratetAm": new Date("1956-11-02"),
  "gesellschaft": "51",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-07-01"),
  "unternehmensaustritt": new Date("1983-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1994-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 088192770972"
}
,

{
  "personalnummer": 284091,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Karl-Heinz Schleifer",
  "adresse": "Im Auweg 49, 67269 Grünstadt",
  "geschlecht": "männlich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1947-07-09"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-09-01"),
  "unternehmensaustritt": new Date("1984-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2012-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "VA, Telefon: 06359 92 90 82"
}
,

{
  "personalnummer": 500221,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Irmgard Simeth",
  "adresse": "Franz-Fackler-Str. 6, 80995 München",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1939-05-30"),
  "geheiratetAm": new Date("1960-06-03"),
  "gesellschaft": "51",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1967-05-01"),
  "unternehmensaustritt": new Date("1983-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 403406,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Paula Straßer",
  "adresse": "Landfriedstr. 12, 81547 München",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1930-10-12"),
  "geheiratetAm": new Date("1951-07-30"),
  "gesellschaft": "51",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1958-12-15"),
  "unternehmensaustritt": new Date("1973-02-28"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1973-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500057,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Gertrud Tobisch",
  "adresse": "Amselweg 55, 90768 Fürth",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1932-03-15"),
  "geheiratetAm": new Date("1957-07-20"),
  "gesellschaft": "51",
  "versorgungsordnung": 74,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1958-08-01"),
  "unternehmensaustritt": new Date("1985-05-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1985-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 401642,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Doris Vogg",
  "adresse": "Dr.-Schmelzing-Str. 34, 86169 Augsburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1933-01-30"),
  "geheiratetAm": new Date("1953-06-06"),
  "gesellschaft": "51",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1957-10-16"),
  "unternehmensaustritt": new Date("1985-05-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 258095,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Hildegard Wanner",
  "adresse": "Christiansreuther Str. 29, 95032 Hof",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1939-10-04"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1963-04-16"),
  "unternehmensaustritt": new Date("1980-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-04-11"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Sonderfall Anpassung, Korrektur 05.10.2000 vorgenommen"
}
,

{
  "personalnummer": 265024,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Fritz Weber",
  "adresse": "Anton-Bartl-Str. 4, 82327 Tutzing",
  "geschlecht": "männlich",
  "familienstand": null,
  "geburtsdatum": new Date("1941-08-27"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1984-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2006-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500492,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Renate Ziebell",
  "adresse": "Werner-von-Siemens-Allee 23, 90552 Röthenbach",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1944-02-28"),
  "geheiratetAm": new Date("1980-06-06"),
  "gesellschaft": "51",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1966-04-01"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1991-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0151 425 16 602"
}
,

{
  "personalnummer": 500427,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Helga Albrecht",
  "adresse": "Weißenfelser Weg 13, 68309 Mannheim",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1940-01-17"),
  "geheiratetAm": new Date("1973-09-21"),
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-07-01"),
  "unternehmensaustritt": new Date("1986-11-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1991-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 283101,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Ursula Anders",
  "adresse": "Anselm-Pflug-Str. 1, 88097 Eriskirch",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1938-04-03"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-08-01"),
  "unternehmensaustritt": new Date("1983-01-31"),
  "ruhegeldfaehigAb": new Date("1973-02-01"),
  "rentenbeginn": new Date("1998-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 282541,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Gertraud Auerhammer-Fehn",
  "adresse": "Hosemannstraße 9a, 83451 Piding",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1950-02-04"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-07-01"),
  "unternehmensaustritt": new Date("1985-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2010-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Heirat nach UA"
}
,

{
  "personalnummer": 282525,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Kurt Bartholomä",
  "adresse": "Juan Carlos I Nr. 39, Cristimar, K4-4, E38650 Los Cristianos - Tenerife",
  "geschlecht": "männlich",
  "familienstand": "",
  "geburtsdatum": new Date("1939-04-11"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-07-01"),
  "unternehmensaustritt": new Date("1982-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2002-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0034 922 75 55 78"
}
,

{
  "personalnummer": 115923,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Hilde Baumann",
  "adresse": "c/o Herrn Dennis Baumann, Benzstraße 9, 68775 Ketsch",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1949-05-11"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-07-19"),
  "unternehmensaustritt": new Date("1985-02-28"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2014-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 280784,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Gabriele Bay",
  "adresse": "Schottstraße 6, 70192 Stuttgart",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1938-06-16"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1958-10-01"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1998-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 280461,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Liselotte Blanz",
  "adresse": "Friedrich-Schofer-Str. 38, 71332 Waiblingen",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1928-07-27"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1961-10-01"),
  "unternehmensaustritt": new Date("1986-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 07151-54140"
}
,

{
  "personalnummer": 500352,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Gertrud Blaszczyk",
  "adresse": "Im Schlafläger 6, 68519 Viernheim",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1934-06-17"),
  "geheiratetAm": new Date("1955-02-12"),
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-04-01"),
  "unternehmensaustritt": new Date("1983-12-31"),
  "ruhegeldfaehigAb": new Date("1972-02-01"),
  "rentenbeginn": new Date("1988-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0620 44244"
}
,

{
  "personalnummer": 976023,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ruth Bösinger",
  "adresse": "Beethovenstraße 66, 71640 Ludwigsburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1951-04-20"),
  "geheiratetAm": new Date("1971-01-09"),
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-09-01"),
  "unternehmensaustritt": new Date("1986-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2006-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 280149,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Teilübertragung auf Direktversicherung",
  "name": "Werner Brümmer",
  "adresse": "Seestraße 27d, 78464 Konstanz",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1936-03-21"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-11-01"),
  "unternehmensaustritt": new Date("1987-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500497,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Sabine Buhrke",
  "adresse": "Marienstraße 17, 71332 Waiblingen",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1948-03-08"),
  "geheiratetAm": new Date("1973-11-23"),
  "gesellschaft": "61",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-01-01"),
  "unternehmensaustritt": new Date("1985-04-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2005-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 07151987770"
}
,

{
  "personalnummer": 500517,
  "aktuelleStatusgruppe": "Versorgungsausgleich",
  "alteStatusgruppe": null,
  "name": "Renate Castanjen",
  "adresse": "Martin-Luther-King-Allee 16, 89231 Neu-Ulm",
  "geschlecht": "weiblich",
  "familienstand": "gesch.",
  "geburtsdatum": new Date("1937-09-19"),
  "geheiratetAm": new Date("1958-11-28"),
  "gesellschaft": "61",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1963-01-01"),
  "unternehmensaustritt": new Date("1985-09-15"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1995-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 282368,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Elisabeth Dillmann",
  "adresse": "Eibenweg 4, 73084 Salach",
  "geschlecht": "weiblich",
  "familienstand": null,
  "geburtsdatum": new Date("1943-07-07"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-04-01"),
  "unternehmensaustritt": new Date("1983-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2003-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 283358,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Gerhard Oberstein",
  "adresse": "Augarten 18, 72160 Horb a.N. - Dettingen",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1935-07-15"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-03-01"),
  "unternehmensaustritt": new Date("1979-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1995-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 283705,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Otto Dobner",
  "adresse": "Johannes-Hoffart-Str. 29, 68163 Mannheim",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1941-11-23"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-11-01"),
  "unternehmensaustritt": new Date("1981-08-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2003-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500545,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Karin Dorn",
  "adresse": "Röckenwiesenstr. 7, 70197 Stuttgart",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1940-05-18"),
  "geheiratetAm": new Date("1961-01-01"),
  "gesellschaft": "61",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-07-01"),
  "unternehmensaustritt": new Date("1985-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2002-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500506,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Ute Eggers",
  "adresse": "Rathausstraße 96a, 68519 Viernheim",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1944-08-02"),
  "geheiratetAm": new Date("1980-05-16"),
  "gesellschaft": "61",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-05-01"),
  "unternehmensaustritt": new Date("1983-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1991-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "VA - Telefon: 06204-76202"
}
,

{
  "personalnummer": 976017,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Klaus Eifler",
  "adresse": "Wittenberger Weg 7, 68309 Mannheim",
  "geschlecht": "männlich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1941-07-27"),
  "geheiratetAm": new Date("1965-07-09"),
  "gesellschaft": "61",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-03-01"),
  "unternehmensaustritt": new Date("1986-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1992-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 283770,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Klaus Eisenmann",
  "adresse": "Im Asemwald 54/8, 70599 Stuttgart",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1944-10-19"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-03-08"),
  "unternehmensaustritt": new Date("1982-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "0711-7289907"
}
,

{
  "personalnummer": 281931,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Karel Fajfr",
  "adresse": "Alpstraße 14, 72631 Aichtal",
  "geschlecht": "männlich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1943-09-07"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-05-01"),
  "unternehmensaustritt": new Date("1985-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2008-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 280388,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Jan Formanek",
  "adresse": "Pestalozzieweg 13, 76530 Baden-Baden",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1934-12-14"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-12-01"),
  "unternehmensaustritt": new Date("1982-02-28"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich - 2. Ehe!!!!!!"
}
,

{
  "personalnummer": 500266,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Elfriede Ganz",
  "adresse": "Kornweg 9, 76185 Karlsruhe",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1951-04-02"),
  "geheiratetAm": new Date("1970-11-06"),
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-11-01"),
  "unternehmensaustritt": new Date("1983-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2002-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 282210,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Helga Grindel",
  "adresse": "Atzelbuckelstraße 6b, 68259 Mannheim",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1940-05-17"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1986-05-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 280065,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Manfred Grözinger",
  "adresse": "Blütenstraße 18, 70599 Stuttgart",
  "geschlecht": "männlich",
  "familienstand": "geschieden",
  "geburtsdatum": new Date("1935-09-09"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1957-03-01"),
  "unternehmensaustritt": new Date("1978-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1999-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich"
}
,

{
  "personalnummer": 282178,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Sigrid Guida",
  "adresse": "Burgerwaldstraße 6, 91567 Herrieden",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1949-10-17"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1985-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2015-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 281592,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Renate Hanus",
  "adresse": "Hölderlinstraße 7, 70771 Leinfelden-Echterdingen",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1948-07-10"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-01-01"),
  "unternehmensaustritt": new Date("1983-07-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2010-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "0711-7547120"
}
,

{
  "personalnummer": 282376,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Ulrike Hausmann",
  "adresse": "Hohenstaufenstraße 42, 71696 Möglingen",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1950-09-16"),
  "geheiratetAm": new Date("1993-09-17"),
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-04-01"),
  "unternehmensaustritt": new Date("1985-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2013-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Eheschließung nach UA"
}
,

{
  "personalnummer": 283861,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Peter Hechelmann",
  "adresse": "Badenerstraße 12, 78315 Radolfzell",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1947-08-18"),
  "geheiratetAm": new Date("2011-07-25"),
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-10-01"),
  "unternehmensaustritt": new Date("1984-04-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2012-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Tel.: 07732 97 16 24, email: p-hechelmann@t-online.de"
}
,
{
  "personalnummer": 281816,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Dietrich Heckel",
  "adresse": "Fribolinstraße 20, 72321 Bietigheim-Bissingen",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1935-11-23"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-01-01"),
  "unternehmensaustritt": new Date("1986-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0714-244335"
}
,

{
  "personalnummer": 280503,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Ingrid Heering",
  "adresse": "c/o Herrn Ralf Helm, Manspergerstraße 15, 70619 Stuttgart",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1942-10-23"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1963-10-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500061,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Helga Heinsen",
  "adresse": "Cäsar-von-Hofacker-Anlage 18, 71640 Ludwigsburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1941-01-12"),
  "geheiratetAm": new Date("1966-07-15"),
  "gesellschaft": "61",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-01-01"),
  "unternehmensaustritt": new Date("1984-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2002-08-16"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 283192,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Hertha Heinz",
  "adresse": "Birkenstraße 6, 76879 Essingen",
  "geschlecht": "weiblich",
  "familienstand": null,
  "geburtsdatum": new Date("1944-03-13"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1974-01-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2004-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 402357,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Elisabeth Heinze",
  "adresse": "Auwaldstr. 98, 79110 Freiburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1940-05-06"),
  "geheiratetAm": new Date("1959-08-29"),
  "gesellschaft": "61",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-10-01"),
  "unternehmensaustritt": new Date("1982-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1983-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 116327,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Oskar Hess",
  "adresse": "Bautzener Weg 8, 68309 Mannheim",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1930-10-23"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1966-04-01"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1994-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500569,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Gisela Hewig",
  "adresse": "Weinklinge 14, 70329 Stuttgart",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1937-03-13"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1961-09-15"),
  "unternehmensaustritt": new Date("1978-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2002-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 500529,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Lore Hirrlinger",
  "adresse": "Wiflingshauser Str 129, 73732 Esslingen",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1928-08-09"),
  "geheiratetAm": new Date("1954-08-28"),
  "gesellschaft": "61",
  "versorgungsordnung": 82,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-07-01"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1986-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 281303,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Edith Huber-Brändli",
  "adresse": "Vermontstraße 8, 70806 Kornwestheim",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1949-05-06"),
  "geheiratetAm": null,
  "gesellschaft": "61",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-01-01"),
  "unternehmensaustritt": new Date("1985-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2011-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 07141 287 602"
},

{
  "personalnummer": 190447,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Marianne Tietjen",
  "adresse": "Günther-Hafemann-Str. 6, 28327 Bremen",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1936-06-02"),
  "geheiratetAm": null,
  "gesellschaft": "21",
  "versorgungsordnung": 74,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1965-04-02"),
  "unternehmensaustritt": new Date("1984-01-05"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1984-01-06"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 175430,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Elisabeth Wiegmann",
  "adresse": "c/o Renate Emmerich, Hittendahlplatz 11c, 21447 Handorf",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1934-07-02"),
  "geheiratetAm": null,
  "gesellschaft": "21",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1960-02-01"),
  "unternehmensaustritt": new Date("1987-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 105619,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Sylvia Bader",
  "adresse": "Schwarzbachstraße 60, 40625 Düsseldorf",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1947-10-10"),
  "geheiratetAm": null,
  "gesellschaft": "31",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-01-01"),
  "unternehmensaustritt": new Date("1982-10-11"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2012-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "0211674380"
}
,


{
  "personalnummer": 500279,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Erika Bieschke",
  "adresse": "c/o Herrn Norbert Bieschke, Lindnering 153, 82024 Taufkirchen",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1933-11-03"),
  "geheiratetAm": new Date("1953-01-31"),
  "gesellschaft": "31",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1958-10-06"),
  "unternehmensaustritt": new Date("1981-01-22"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1981-01-23"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 500455,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Irmgard Blume",
  "adresse": "Dürrering 8, 40878 Ratingen",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1936-12-25"),
  "geheiratetAm": new Date("1958-02-15"),
  "gesellschaft": "31",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1957-10-01"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Sohn: Christoph Blume"
},

{
  "personalnummer": 500014,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Margret Buchwald",
  "adresse": "Römerstraße 163, 41462 Neuss",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1936-12-26"),
  "geheiratetAm": new Date("1956-10-25"),
  "gesellschaft": "31",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1959-11-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 208579,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Arnold Bürgen",
  "adresse": "Rosendalstr. 97, 40882 Ratingen",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1930-06-23"),
  "geheiratetAm": null,
  "gesellschaft": "31",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1961-04-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 206987,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Jürgen Drebes",
  "adresse": "Kleiner Ranzen 5, 31867 Lauenau",
  "geschlecht": "männlich",
  "familienstand": "gesch.",
  "geburtsdatum": new Date("1944-04-24"),
  "geheiratetAm": null,
  "gesellschaft": "31",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-10-01"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2009-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "VA, Telefon: 05043 96 31 88"
},

{
  "personalnummer": 206870,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Wolfgang Dunsche",
  "adresse": "Hohe Buchen 1b, 45133 Essen",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1946-08-01"),
  "geheiratetAm": null,
  "gesellschaft": "31",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-07-01"),
  "unternehmensaustritt": new Date("1984-04-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2011-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0172-4355194"
},

{
  "personalnummer": 500543,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Marion Epp",
  "adresse": "Klappheckstraße 2, 40474 Düsseldorf",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1942-12-15"),
  "geheiratetAm": new Date("1971-12-01"),
  "gesellschaft": "31",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-10-01"),
  "unternehmensaustritt": new Date("1986-05-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2006-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 206938,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Teilübertragung auf Direktversicherung",
  "name": "Otto Faßbinder",
  "adresse": "Wattenbeker Weg 6, 24625 Negenharrie",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1938-02-04"),
  "geheiratetAm": null,
  "gesellschaft": "31",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-07-01"),
  "unternehmensaustritt": new Date("1986-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich, Telefon: 04322-1380"
},

{
  "personalnummer": 208280,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Manfred Fechner",
  "adresse": "Offenbergerstr. 17, 48151 Münster",
  "geschlecht": "männlich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1941-03-17"),
  "geheiratetAm": null,
  "gesellschaft": "31",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-03-01"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2005-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 02571 7150"
},

{
  "personalnummer": 500503,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Sigrid Gottschall",
  "adresse": "Mühlenstraße 9, 59192 Bergkamen-Oberad.",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1941-07-28"),
  "geheiratetAm": new Date("1967-02-07"),
  "gesellschaft": "31",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-01-01"),
  "unternehmensaustritt": new Date("1980-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2002-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 02306-80031"
}
,

{
  "personalnummer": 500477,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Erika Hamacher",
  "adresse": "Herbartstraße 49, 40882 Ratingen",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1941-10-29"),
  "geheiratetAm": new Date("1964-02-21"),
  "gesellschaft": "31",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-01-01"),
  "unternehmensaustritt": new Date("1983-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 02102 84 58 29"
},

{
  "personalnummer": 500488,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Barbara Heckers",
  "adresse": "Fontanestraße 86, 40789 Monheim",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1937-11-17"),
  "geheiratetAm": new Date("1959-03-19"),
  "gesellschaft": "31",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1957-08-01"),
  "unternehmensaustritt": new Date("1985-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 02173-62574"
},

{
  "personalnummer": 403039,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Krista Heller",
  "adresse": "Nelkenweg 41, 41564 Kaarst",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1939-12-13"),
  "geheiratetAm": new Date("1964-04-27"),
  "gesellschaft": "31",
  "versorgungsordnung": 78,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1967-04-01"),
  "unternehmensaustritt": new Date("1983-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1995-09-11"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 500558,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Gertrud Hilger",
  "adresse": "c/o Herrn Dieter Hilger, Heinrich-Geißler-Str. 28, 42897 Remscheid",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1926-02-06"),
  "geheiratetAm": new Date("1952-05-24"),
  "gesellschaft": "31",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-01-01"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 500060,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Elisabeth Hoffmann",
  "adresse": "Wartburgstrasse 2, 47259 Duisburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1938-04-08"),
  "geheiratetAm": new Date("1958-06-13"),
  "gesellschaft": "31",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-09-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1994-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 403569,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Henriette Hopfner",
  "adresse": "Champagne 47, 40822 Mettmann",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1931-10-30"),
  "geheiratetAm": new Date("1958-07-18"),
  "gesellschaft": "31",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1952-04-28"),
  "unternehmensaustritt": new Date("1983-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1987-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 02104-9-52453"
},

{
  "personalnummer": 401801,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Christel Krokor",
  "adresse": "Straussstr. 3, 59227 Ahlen",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1928-06-24"),
  "geheiratetAm": new Date("1947-04-01"),
  "gesellschaft": "31",
  "versorgungsordnung": 74,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1961-06-15"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1986-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 207464,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Elsbeth Lahtz",
  "adresse": "c/o Frau Maren Lahtz-Tuszynski, Bebelstr. 24, 44319 Dortmund",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1929-11-26"),
  "geheiratetAm": null,
  "gesellschaft": "31",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Tochter: 0231 10876346 1073 21 62 945"
},

{
  "personalnummer": 207035,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Eckart Maertens",
  "adresse": "Habichtstraße 78, 45134 Essen",
  "geschlecht": "männlich",
  "familienstand": null,
  "geburtsdatum": new Date("1942-07-11"),
  "geheiratetAm": null,
  "gesellschaft": "31",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-11-01"),
  "unternehmensaustritt": new Date("1983-02-28"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500242,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Gerda Medek",
  "adresse": "Auf der Aspel 16, 50859 Köln-Widdersdorf",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1939-04-28"),
  "geheiratetAm": new Date("1961-11-16"),
  "gesellschaft": "31",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-07-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0221 170 95 46"
},

{
  "personalnummer": 500298,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Angelika Melling",
  "adresse": "Eduard-Schloemann-Str. 20, 40237 Düsseldorf",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1947-09-24"),
  "geheiratetAm": new Date("1970-09-25"),
  "gesellschaft": "31",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1955-03-11"),
  "unternehmensaustritt": new Date("1981-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1981-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0211-663122"
},

{
  "personalnummer": 500341,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Inga Niquet",
  "adresse": "Clarenbachstr. 2a, 41462 Neuss",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1941-02-23"),
  "geheiratetAm": new Date("1961-06-20"),
  "gesellschaft": "31",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1958-07-01"),
  "unternehmensaustritt": new Date("1984-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1987-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 207597,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Gerd Nosek",
  "adresse": "Levinstr. 62, 45356 Essen",
  "geschlecht": "männlich",
  "familienstand": "geschieden",
  "geburtsdatum": new Date("1947-03-07"),
  "geheiratetAm": new Date("1969-10-01"),
  "gesellschaft": "31",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-10-01"),
  "unternehmensaustritt": new Date("1983-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2012-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich"
},

{
  "personalnummer": 500524,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Hanni Nowitzki",
  "adresse": "Westfalenstraße 33, 45661 Recklinghausen",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1933-06-17"),
  "geheiratetAm": new Date("1956-01-21"),
  "gesellschaft": "31",
  "versorgungsordnung": 74,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1960-08-01"),
  "unternehmensaustritt": new Date("1986-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1986-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 207498,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Marianne Partzsch",
  "adresse": "Lazarettstr. 50, 45127 Essen",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1927-01-08"),
  "geheiratetAm": null,
  "gesellschaft": "31",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1958-12-08"),
  "unternehmensaustritt": new Date("1985-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1987-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0201-224607"
},

{
  "personalnummer": 500086,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Hannelore Petzelt",
  "adresse": "Espenweg 37, 47804 Krefeld",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1937-03-01"),
  "geheiratetAm": new Date("1961-02-25"),
  "gesellschaft": "31",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1964-07-08"),
  "unternehmensaustritt": new Date("1984-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 208397,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Christian Pietzek",
  "adresse": "Düppelstraße 13, 45138 Essen",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1942-10-31"),
  "geheiratetAm": null,
  "gesellschaft": "31",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-07-01"),
  "unternehmensaustritt": new Date("1983-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0201-27 32 36"
},

{
  "personalnummer": 500307,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Loni Reinhardt",
  "adresse": "Bahnhofstr. 2, 21684 Agathenburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1936-08-05"),
  "geheiratetAm": new Date("1956-09-08"),
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1979-04-01"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1995-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 205732,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Helmut Schliebs",
  "adresse": "Rügenstraße 10, 40880 Ratingen",
  "geschlecht": "männlich",
  "familienstand": "geschieden",
  "geburtsdatum": new Date("1940-02-12"),
  "geheiratetAm": null,
  "gesellschaft": "31",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-10-01"),
  "unternehmensaustritt": new Date("1984-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2005-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich"
},

{
  "personalnummer": 976035,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ellen Schönitz",
  "adresse": "Landsberger Straße 26, 40599 Düsseldorf",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1940-04-14"),
  "geheiratetAm": new Date("1966-01-13"),
  "gesellschaft": "31",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-04-01"),
  "unternehmensaustritt": new Date("1984-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2004-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500319,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Helga Schweda",
  "adresse": "Akademiestraße 1, 40213 Düsseldorf",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1940-03-07"),
  "geheiratetAm": new Date("1964-08-28"),
  "gesellschaft": "31",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1961-01-01"),
  "unternehmensaustritt": new Date("1983-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1984-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "0211-325497 Co. Canyamel, Via de la Golondrina 6, E07580 Capdepera"
},

{
  "personalnummer": 209270,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Erich Semmrich",
  "adresse": "Füsilierstr. 21, 40476 Düsseldorf",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1927-01-12"),
  "geheiratetAm": null,
  "gesellschaft": "31",
  "versorgungsordnung": 74,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1961-01-06"),
  "unternehmensaustritt": new Date("1986-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1987-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 208272,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Eckart Vogler",
  "adresse": "Erphostraße 36, 48145 Münster",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1946-10-09"),
  "geheiratetAm": null,
  "gesellschaft": "31",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-10-01"),
  "unternehmensaustritt": new Date("1985-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2011-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich"
},

{
  "personalnummer": 280040,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Edmund Eisenberger",
  "adresse": "Wittelsbacher Straße 6a, 82319 Starnberg",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1940-03-08"),
  "geheiratetAm": null,
  "gesellschaft": "41",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1967-01-01"),
  "unternehmensaustritt": new Date("1983-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2005-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0177-2555221"
},

{
  "personalnummer": 401215,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Maria Fell",
  "adresse": "c/o Betreuungsbüro Lorenz, Mühlenstr. 17, 66802 Überherrn",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1931-06-20"),
  "geheiratetAm": new Date("1957-05-13"),
  "gesellschaft": "41",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-01-01"),
  "unternehmensaustritt": new Date("1984-07-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1984-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 108191,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Peter Gottschick",
  "adresse": "Hornauer Weg 7, 65843 Sulzbach/Taunus",
  "geschlecht": "männlich",
  "familienstand": null,
  "geburtsdatum": new Date("1941-04-18"),
  "geheiratetAm": null,
  "gesellschaft": "41",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-03-16"),
  "unternehmensaustritt": new Date("1983-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2006-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Tel. 06196-22491"
},

{
  "personalnummer": 500037,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Augusta Gressler",
  "adresse": "Otto-Löwe-Str. 6, 60486 Frankfurt",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1937-12-05"),
  "geheiratetAm": new Date("1970-02-04"),
  "gesellschaft": "41",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1965-06-01"),
  "unternehmensaustritt": new Date("1980-05-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1980-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 232249,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Karl-Heinz Hagen",
  "adresse": "Goethestraße 6, 64367 Mühltal-Traisa",
  "geschlecht": "männlich",
  "familienstand": "geschieden",
  "geburtsdatum": new Date("1929-07-23"),
  "geheiratetAm": null,
  "gesellschaft": "41",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-07-01"),
  "unternehmensaustritt": new Date("1986-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich"
},

{
  "personalnummer": 500413,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Lisa Hampe",
  "adresse": "Wohnung 26, Am Hammelsberg 6, 34253 Lohfelden",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1933-07-30"),
  "geheiratetAm": new Date("1955-08-31"),
  "gesellschaft": "41",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1955-02-10"),
  "unternehmensaustritt": new Date("1985-11-30"),
  "ruhegeldfaehigAb": new Date("1955-02-01"),
  "rentenbeginn": new Date("1989-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "0561-98802655"
},

{
  "personalnummer": 108217,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Dr. Udo Heukelbach",
  "adresse": "An der Litzelwiese 16, 60488 Frankfurt/Main",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1942-06-11"),
  "geheiratetAm": null,
  "gesellschaft": "41",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-10-01"),
  "unternehmensaustritt": new Date("1984-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2006-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 231340,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Ursula Ihme",
  "adresse": "Max-Planck-Straße 8, 65760 Eschborn",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1941-02-23"),
  "geheiratetAm": null,
  "gesellschaft": "41",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1965-02-01"),
  "unternehmensaustritt": new Date("1980-09-30"),
  "ruhegeldfaehigAb": new Date("1963-01-01"),
  "rentenbeginn": new Date("2003-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 401747,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Traute Keiling",
  "adresse": "Unter den Kastanien 13, 60596 Frankfurt",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1929-05-02"),
  "geheiratetAm": new Date("1954-12-24"),
  "gesellschaft": "41",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-02-01"),
  "unternehmensaustritt": new Date("1985-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1985-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 500429,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ruhtraut Krauss",
  "adresse": "Glogauer Strasse 1a, 63814 Mainaschaff",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1937-02-19"),
  "geheiratetAm": new Date("1960-02-18"),
  "gesellschaft": "41",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1974-05-01"),
  "unternehmensaustritt": new Date("1986-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1991-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 230789,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Karl-Heinz Kröger",
  "adresse": "Am Hang 4, 34253 Lohfelden",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1936-12-31"),
  "geheiratetAm": new Date("1965-01-18"),
  "gesellschaft": "41",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1982-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2002-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0561-514932"
},

{
  "personalnummer": 500096,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Elisabeth Kuhn",
  "adresse": "c/o Dagmar Wolf, Zeil 24, 65719 Hofheim",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1928-03-29"),
  "geheiratetAm": new Date("1951-06-09"),
  "gesellschaft": "41",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1953-01-02"),
  "unternehmensaustritt": new Date("1983-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1983-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Schwiegersohn Helmut Wolf, Telefon: 06192-6503"
},

{
  "personalnummer": 500564,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ursel Kühn",
  "adresse": "An der Kurhessenhalle 56, 34134 Kassel",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1933-01-29"),
  "geheiratetAm": new Date("1951-06-09"),
  "gesellschaft": "41",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1953-01-02"),
  "unternehmensaustritt": new Date("1985-07-31"),
  "ruhegeldfaehigAb": new Date("1963-01-01"),
  "rentenbeginn": new Date("1988-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 108365,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Uwe Mayer",
  "adresse": "Idastraße 37, 63456 Hanau 7",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1944-01-18"),
  "geheiratetAm": new Date("1968-01-01"),
  "gesellschaft": "41",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1984-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2009-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,
{
  "personalnummer": 234542,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Helga Möslein",
  "adresse": "Friedrich-Ebert-Straße 49 b, 63179 Obertshausen",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1938-11-10"),
  "geheiratetAm": null,
  "gesellschaft": "41",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1952-08-01"),
  "unternehmensaustritt": new Date("1973-08-14"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1973-08-15"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}










          ];

// Axios POST request function
// Axios POST request function
async function insertData() {
  for (let i = 0; i < dataToInsert.length; i++) {
    const person = dataToInsert[i];

    try {
      const response = await axios.post(
        "http://localhost:4000/api/person",
        person
      );

      console.log(`✔️ Inserted personalnummer ${person.personalnummer}`);
    } catch (error) {
      // Wenn der Server geantwortet hat (HTTP-Fehlercode)
      if (error.response) {
        // 400 = existiert schon (so wie du es in deiner Route gebaut hast)
        if (error.response.status === 400) {
          console.warn(
            `⚠️ personalnummer ${person.personalnummer} exists – skipped`
          );
          continue; // optional, macht nur explizit "weiter" zur nächsten Person
        }

        // Andere HTTP-Fehler
        console.error(
          `❌ HTTP ${error.response.status} for personalnummer ${person.personalnummer}:`,
          error.response.data
        );
      } else {
        // Kein Response = z.B. Netzwerkfehler / Server nicht erreichbar
        console.error(
          `❌ Network/Unknown error for personalnummer ${person.personalnummer}:`,
          error.message
        );
      }
    }
  }

  console.log("✅ Import finished.");
}


// Call the function to insert data
insertData();