const axios = require('axios');

const dataToInsert = [
    
    
    {
  "personalnummer": 108647,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Josef Paertmann",
  "adresse": "Wilhelm-Raabe-Straße 17, 38104 Braunschweig",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1943-08-10"),
  "geheiratetAm": new Date("1971-07-21"),
  "gesellschaft": "41",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-08-01"),
  "unternehmensaustritt": new Date("1982-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 231720,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Helmut Pilgenröther",
  "adresse": "c/o Parkwohnstift, App. 735, Heinrich-von-Kleist-Str. 2, 97688 Bad Kissingen",
  "geschlecht": "männlich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1936-02-09"),
  "geheiratetAm": null,
  "gesellschaft": "41",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1967-11-01"),
  "unternehmensaustritt": new Date("1984-07-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 230554,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Lieselotte Polzin",
  "adresse": "Eckenheimer Landstr. 307, 60320 Frankfurt",
  "geschlecht": "weiblich",
  "familienstand": "?",
  "geburtsdatum": new Date("1934-01-04"),
  "geheiratetAm": null,
  "gesellschaft": "41",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1965-03-01"),
  "unternehmensaustritt": new Date("1979-09-30"),
  "ruhegeldfaehigAb": new Date("1966-05-16"),
  "rentenbeginn": new Date("1994-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "069 56 31 44"
},

{
  "personalnummer": 230763,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Lieselotte Preikschat",
  "adresse": "In der Eisenbach 50, 65510 Idstein",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1929-01-11"),
  "geheiratetAm": new Date("1953-04-18"),
  "gesellschaft": "41",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-07-01"),
  "unternehmensaustritt": new Date("1985-11-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 500510,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ingrid Reich",
  "adresse": "c/o Herrn Olaf Reich, Finkenweg 1, 34266 Niestetal",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1936-10-25"),
  "geheiratetAm": new Date("1961-03-09"),
  "gesellschaft": "41",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1950-10-01"),
  "unternehmensaustritt": new Date("1986-02-28"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1987-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 230078,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Klaus-Joachim Reichert",
  "adresse": "Taunusstraße 3, 55118 Mainz",
  "geschlecht": "männlich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1944-08-18"),
  "geheiratetAm": new Date("1970-03-26"),
  "gesellschaft": "41",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-10-01"),
  "unternehmensaustritt": new Date("1986-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2004-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 06131 32 95 978"
},

{
  "personalnummer": 232082,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Dittmar Schäfer",
  "adresse": "Mozartstraße 6, 34246 Vellmar",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1949-08-11"),
  "geheiratetAm": new Date("1972-04-01"),
  "gesellschaft": "41",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-09-01"),
  "unternehmensaustritt": new Date("1985-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2011-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 05618 24034"
},


{
  "personalnummer": 500520,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Margot Schellheimer",
  "adresse": "Am Pflaster 17, 36399 Freiensteinau",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1932-05-02"),
  "geheiratetAm": new Date("1954-02-06"),
  "gesellschaft": "41",
  "versorgungsordnung": 74,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1957-11-18"),
  "unternehmensaustritt": new Date("1984-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1984-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "06644-1360"
},

{
  "personalnummer": 230516,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Silvia Schmitz",
  "adresse": "Hauptstraße 1c, 67808 Moersfeld",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1936-04-04"),
  "geheiratetAm": new Date("1954-04-10"),
  "gesellschaft": "41",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-01-01"),
  "unternehmensaustritt": new Date("1981-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 06358 98 94"
},

{
  "personalnummer": 232439,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Heinz Schönefeldt",
  "adresse": "Fuchstanzstr. 4, 61449 Steinbach",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1930-09-20"),
  "geheiratetAm": new Date("1960-02-05"),
  "gesellschaft": "41",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1960-04-01"),
  "unternehmensaustritt": new Date("1986-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 232751,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Klaus-Dieter Theis",
  "adresse": "Rundes Feld 1A, 34128 Kassel",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1942-01-28"),
  "geheiratetAm": null,
  "gesellschaft": "41",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1966-09-01"),
  "unternehmensaustritt": new Date("1978-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2002-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich"
},

{
  "personalnummer": 500439,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Margot Vaupel",
  "adresse": "Helsaer Straße 45, 34123 Kassel",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1935-07-16"),
  "geheiratetAm": new Date("1960-05-27"),
  "gesellschaft": "41",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1946-10-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1986-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 230227,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Monika Zaunmüller",
  "adresse": "Finkenweg 41, 66130 Brebach/Feching",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1944-11-28"),
  "geheiratetAm": null,
  "gesellschaft": "41",
  "versorgungsordnung": 78,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1963-04-01"),
  "unternehmensaustritt": new Date("1981-08-28"),
  "ruhegeldfaehigAb": new Date("1964-11-28"),
  "rentenbeginn": new Date("2009-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 404047,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Marlen Ziola",
  "adresse": "Reichenberger Straße 1, 63452 Hanau",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1944-07-26"),
  "geheiratetAm": new Date("1965-08-19"),
  "gesellschaft": "41",
  "versorgungsordnung": 86,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-02-15"),
  "unternehmensaustritt": new Date("1983-09-27"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1983-09-28"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Anpassung nach PV, keine Erhöhung auf MR 0618184429"
},

{
  "personalnummer": 255240,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Rita Baumgartner",
  "adresse": "Gerhart-Hauptmann-Ring 9, 81737 München",
  "geschlecht": "weiblich",
  "familienstand": "gesch.",
  "geburtsdatum": new Date("1938-04-21"),
  "geheiratetAm": new Date("1972-05-03"),
  "gesellschaft": "51",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-01-01"),
  "unternehmensaustritt": new Date("1980-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1998-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich"
},

{
  "personalnummer": 255638,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Helmut Berger",
  "adresse": "Herrnbühlstraße 2, 90602 Pyrbaum",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1939-12-28"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-02-01"),
  "unternehmensaustritt": new Date("1984-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich"
},

{
  "personalnummer": 976013,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Helga Blumentritt",
  "adresse": "Straßbergerstraße 38, 80809 München",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1944-09-04"),
  "geheiratetAm": new Date("1964-01-09"),
  "gesellschaft": "51",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1960-07-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1997-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "089-3512783"
},

{
  "personalnummer": 112185,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Roland Bothen",
  "adresse": "Langerstr. 2, 81675 München",
  "geschlecht": "männlich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1928-09-27"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-11-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 089 47 12 49"
},

{
  "personalnummer": 225208,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Sigrid Bretzel",
  "adresse": "Fallmerayerstraße 28, 80796 München",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1940-08-22"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-03-01"),
  "unternehmensaustritt": new Date("1978-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2005-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 256081,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Ludwig Drescher",
  "adresse": "Jahnstr. 30, 84406 Dorfen",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1939-12-05"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-07-01"),
  "unternehmensaustritt": new Date("1985-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 253104,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Elfriede Eckart",
  "adresse": "Robert-Koch-Straße 4b, 82031 Grünwald",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1943-07-31"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-07-15"),
  "unternehmensaustritt": new Date("1978-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2006-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "089 649 14 250"
},

{
  "personalnummer": 253096,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Martin Eibel",
  "adresse": "Dachauer Straße 28, 80335 München",
  "geschlecht": "männlich",
  "familienstand": null,
  "geburtsdatum": new Date("1942-08-17"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1964-11-01"),
  "unternehmensaustritt": new Date("1980-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "089-553065"
},
{
  "personalnummer": 500252,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Else Fischer-Voigt",
  "adresse": "Flurweg 20, 82024 Taufkirchen",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1941-11-19"),
  "geheiratetAm": new Date("1971-09-09"),
  "gesellschaft": "51",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1955-01-16"),
  "unternehmensaustritt": new Date("1987-12-31"),
  "ruhegeldfaehigAb": new Date("1954-11-01"),
  "rentenbeginn": new Date("1996-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 040207-281844"
},
{
  "personalnummer": 976065,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Brigitte Fröhlich",
  "adresse": "Schützenstraße 10, 84109 Wörth/Isar",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1943-09-12"),
  "geheiratetAm": new Date("1967-11-02"),
  "gesellschaft": "51",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1967-12-01"),
  "unternehmensaustritt": new Date("1982-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 257303,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Edna Fusenig",
  "adresse": "Möwestraße 15a, 81827 München",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1940-05-02"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1966-06-06"),
  "unternehmensaustritt": new Date("1978-03-31"),
  "ruhegeldfaehigAb": new Date("1963-03-01"),
  "rentenbeginn": new Date("2000-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 252585,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Ludwig Gerold",
  "adresse": "Hans-Boeckler-Str. 34, 80995 München",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1926-11-25"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1958-11-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": new Date("1954-01-01"),
  "rentenbeginn": new Date("1989-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 089 150 29 36"
},

{
  "personalnummer": 256727,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Xaver Geyer",
  "adresse": "Krählerstraße 1, 81373 München",
  "geschlecht": "männlich",
  "familienstand": null,
  "geburtsdatum": new Date("1937-10-15"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-06-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 089 725 42 39"
},

{
  "personalnummer": 259010,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Wolfgang Götz",
  "adresse": "Jagdfeldring 81, 85540 Haar",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1946-03-17"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1975-01-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2009-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 253286,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Anita Götzfried",
  "adresse": "Am Ährenfeld 3/1, 81375 München",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1928-12-28"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1954-11-15"),
  "unternehmensaustritt": new Date("1984-03-31"),
  "ruhegeldfaehigAb": new Date("1954-03-15"),
  "rentenbeginn": new Date("1989-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 256313,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Rita Hartmann",
  "adresse": "c/o Dieter Endruweit, Am Klostergarten 5, 84034 Landshut",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1944-09-17"),
  "geheiratetAm": new Date("1997-10-26"),
  "gesellschaft": "51",
  "versorgungsordnung": 78,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1965-10-01"),
  "unternehmensaustritt": new Date("1982-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 255935,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Karin Havlin",
  "adresse": "Waxensteinstraße 62c, 86163 Augsburg",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1944-12-16"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-07-16"),
  "unternehmensaustritt": new Date("1982-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2008-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 253450,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Heinz Hilmer",
  "adresse": "Wirtsbreite 17, 80939 München",
  "geschlecht": "männlich",
  "familienstand": "?",
  "geburtsdatum": new Date("1936-03-13"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-09-01"),
  "unternehmensaustritt": new Date("1978-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 256883,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Anna Hofknecht",
  "adresse": "Mittelbachweg 8, 84539 Zangberg",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1940-06-28"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1967-06-26"),
  "unternehmensaustritt": new Date("1981-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Heirat nach Austritt?"
},


{
  "personalnummer": 253864,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Ingrid G. Hofmiller",
  "adresse": "Schumacherring 4, 81737 München",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1945-02-03"),
  "geheiratetAm": new Date("1983-06-30"),
  "gesellschaft": "51",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-04-01"),
  "unternehmensaustritt": new Date("1981-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2005-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 136283,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Dr. Monika Huber",
  "adresse": "Herzogstraße 95, 80796 München",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1948-02-23"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-10-01"),
  "unternehmensaustritt": new Date("1983-12-31"),
  "ruhegeldfaehigAb": new Date("1967-10-01"),
  "rentenbeginn": new Date("2013-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 253419,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Erika Klein",
  "adresse": "Hochwaldstraße 47, 85598 Baldham",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1937-02-03"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1962-04-01"),
  "unternehmensaustritt": new Date("1980-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1997-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 500304,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Hildegard Köhler",
  "adresse": "c/o Ruth Becher-Morawetz, Am Schießhaus 2c, 95445 Bayreuth",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1923-08-02"),
  "geheiratetAm": new Date("1944-04-15"),
  "gesellschaft": "51",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1959-08-01"),
  "unternehmensaustritt": new Date("1981-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1981-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0921-7851577 Tochter Frau Ruth Becher-Morawetz"
},

{
  "personalnummer": 400709,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Angela Kraus",
  "adresse": "Marienbader Str. 9, 90480 Nürnberg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1939-07-11"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1959-08-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-02-08"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 266130,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Isolde Krebs",
  "adresse": "Bertholdstraße 3, 80809 München",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1944-10-21"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1964-12-01"),
  "unternehmensaustritt": new Date("1982-04-17"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1982-04-18"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 126250,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Dieter Kreiner",
  "adresse": "Buchenstraße 24, 96123 Litzendorf",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1944-04-06"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-01-01"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 255281,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Heide-Marie Krinner",
  "adresse": "Graseckstraße 20, 82431 Kochel am See",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1944-12-16"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-04-01"),
  "unternehmensaustritt": new Date("1984-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2010-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 08851-362"
},

{
  "personalnummer": 258624,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Monika Kuchenbauer",
  "adresse": "Erlbachweg 1, 83109 Großkarolinenfeld",
  "geschlecht": "weiblich",
  "familienstand": "?",
  "geburtsdatum": new Date("1942-12-18"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2003-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 401641,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Anna Lederer",
  "adresse": "Perlacher Straße 126, 81539 München",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1930-04-23"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1960-08-15"),
  "unternehmensaustritt": new Date("1979-05-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1979-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 269076,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Elisabeth Mayer",
  "adresse": "Beblostr. 22/1, 81677 München",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1934-05-04"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1960-04-01"),
  "unternehmensaustritt": new Date("1987-01-15"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1987-01-16"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 089/915746"
},

{
  "personalnummer": 252279,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Siegfried Meier",
  "adresse": "Dieselstraße 9, 80993 München",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1939-07-28"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1967-07-01"),
  "unternehmensaustritt": new Date("1977-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2002-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 402539,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Johanna Messerer",
  "adresse": "Bachstraße 1, 86971 Peiting",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1931-07-02"),
  "geheiratetAm": new Date("1950-09-30"),
  "gesellschaft": "51",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1963-09-01"),
  "unternehmensaustritt": new Date("1986-02-18"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1986-02-19"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 403762,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Elisabeth Meyer",
  "adresse": "Westring 13 A, 86673 Bergheim",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1936-09-19"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1964-03-16"),
  "unternehmensaustritt": new Date("1981-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1981-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 112581,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Erich Moosburner",
  "adresse": "Von-Stauffenberg-Str. 90/1, 82008 Unterhaching",
  "geschlecht": "männlich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1928-10-30"),
  "geheiratetAm": null,
  "gesellschaft": "51",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-01-01"),
  "unternehmensaustritt": new Date("1985-09-30"),
  "ruhegeldfaehigAb": new Date("1969-08-01"),
  "rentenbeginn": new Date("1988-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 321877,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Volker Stancke",
  "adresse": "Vagtstraße 7, 28203 Bremen",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1940-08-12"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-03-01"),
  "unternehmensaustritt": new Date("1985-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2005-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich, 2. Ehe"
},

{
  "personalnummer": 404066,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Lutz Steiger",
  "adresse": "Konrad-Reuter-Str. 4, 22393 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1938-10-25"),
  "geheiratetAm": null,
  "gesellschaft": "N2",
  "versorgungsordnung": 81,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1963-08-01"),
  "unternehmensaustritt": new Date("1977-08-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1998-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "040/601 50 10"
},

{
  "personalnummer": 405129,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Margrit Thiele",
  "adresse": "Stargarder Str. 53, 22147 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1937-02-28"),
  "geheiratetAm": new Date("1962-08-17"),
  "gesellschaft": "N1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-06-01"),
  "unternehmensaustritt": new Date("1983-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1985-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 500016,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Christiane Urbschus",
  "adresse": "Emsstraße 60, 48145 Münster",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1939-12-23"),
  "geheiratetAm": new Date("1979-10-19"),
  "gesellschaft": "N1",
  "versorgungsordnung": 81,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1951-08-01"),
  "unternehmensaustritt": new Date("1982-04-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1987-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 500491,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Christel Vahl",
  "adresse": "Bleichenstraße 74, 31515 Wunstorf",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1946-06-12"),
  "geheiratetAm": new Date("1967-03-12"),
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1974-07-01"),
  "unternehmensaustritt": new Date("1984-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2003-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 05033 85 84"
},

{
  "personalnummer": 319285,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Ellen Wegner",
  "adresse": "Gurlittstraße 18, 24106 Kiel",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1948-03-12"),
  "geheiratetAm": new Date("1985-04-02"),
  "gesellschaft": "N1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-06-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2008-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich"
},

{
  "personalnummer": 337808,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Teilübertragung auf Direktversicherung",
  "name": "Ortwin Werner",
  "adresse": "Jungfrauenthal 22, 20149 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1937-05-03"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1977-07-17"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": new Date("1966-07-01"),
  "rentenbeginn": new Date("2002-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 151738,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Uwe Werner",
  "adresse": "Elbstraße 48, 22880 Wedel",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1941-02-05"),
  "geheiratetAm": new Date("1984-09-03"),
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1976-07-01"),
  "unternehmensaustritt": new Date("1989-08-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 500474,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Margarete Wiehler",
  "adresse": "Kriemhildstraße 15 Haus D, 22559 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1930-10-25"),
  "geheiratetAm": new Date("1957-07-27"),
  "gesellschaft": "N1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-01-01"),
  "unternehmensaustritt": new Date("1990-07-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1992-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 01734619344"
},

{
  "personalnummer": 146175,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Doris Ziegler",
  "adresse": "Mohrhof 5, 24794 Borgstedt",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1935-07-18"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 74,
  "arbVerhRentTr": "10",
  "unternehmenseintritt": new Date("1958-11-03"),
  "unternehmensaustritt": new Date("1990-12-31"),
  "ruhegeldfaehigAb": new Date("1958-11-01"),
  "rentenbeginn": new Date("1995-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 320978,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Teilübertragung auf Direktversicherung",
  "name": "Dr. Manfred Ziercke",
  "adresse": "Bredenbekstraße 30a, 22397 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1943-06-23"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-04-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2008-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 337360,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Sabine Zuther",
  "adresse": "Sandhöhe 9, 21465 Reinbek",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1947-08-26"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-02-01"),
  "unternehmensaustritt": new Date("1981-09-30"),
  "ruhegeldfaehigAb": new Date("1971-10-01"),
  "rentenbeginn": new Date("1981-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 7106093"
},

{
  "personalnummer": 500303,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Christa Abraham",
  "adresse": "Ohkoppel 23, 25421 Pinneberg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1946-01-20"),
  "geheiratetAm": new Date("1967-06-24"),
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1958-07-01"),
  "unternehmensaustritt": new Date("1986-01-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1991-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 04101-67709 – es gibt einen Sohn"
},

{
  "personalnummer": 500224,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Dorothee Anderer",
  "adresse": "Hummelsbüttler Weg 12, 22339 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1938-04-18"),
  "geheiratetAm": new Date("1976-05-09"),
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1958-03-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 976064,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Rita Baark",
  "adresse": "Marienhoehe 13, 25451 Quickborn",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1935-10-31"),
  "geheiratetAm": new Date("1964-07-10"),
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1961-07-01"),
  "unternehmensaustritt": new Date("1987-01-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 500034,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ilse Bendtsen",
  "adresse": "Grandweg 79, 25451 Quickborn",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1930-11-06"),
  "geheiratetAm": new Date("1953-10-17"),
  "gesellschaft": "11",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-10-01"),
  "unternehmensaustritt": new Date("1987-01-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 404076,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Erika Bollmann",
  "adresse": "c/o Jutta Putfarcken, Hermann-Ehlers-Weg 3, 29303 Bergen",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1936-09-26"),
  "geheiratetAm": new Date("1958-02-22"),
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-11-15"),
  "unternehmensaustritt": new Date("1982-08-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Tochter: imbissamfunkturm@web.de"
},

{
  "personalnummer": 321984,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Sieglinde Brütting",
  "adresse": "Brahmsstraße 3A, 91052 Erlangen",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1939-11-28"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 78,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1967-10-01"),
  "unternehmensaustritt": new Date("1983-06-30"),
  "ruhegeldfaehigAb": new Date("1963-01-01"),
  "rentenbeginn": new Date("1998-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 976025,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Helga Brüggmann",
  "adresse": "c/o Dr. Th. Brüggmann, Hirtenbrink 3, 21423 Winsen/Luhe",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1934-09-29"),
  "geheiratetAm": new Date("1956-03-03"),
  "gesellschaft": "11",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1952-08-04"),
  "unternehmensaustritt": new Date("1983-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1987-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 400908,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ursula Cohrs",
  "adresse": "Schlankreye 25, 20144 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1940-08-15"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-04-01"),
  "unternehmensaustritt": new Date("1986-11-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1986-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 420 8229"
},


{
  "personalnummer": 976036,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ingrid Damm",
  "adresse": "Rissenerweg 37, 25482 Appen-Etz",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1936-09-21"),
  "geheiratetAm": new Date("1957-09-14"),
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1955-04-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1998-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500507,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Margret Damm",
  "adresse": "Oberst-V.-Stauffenbergstr. 26, 25421 Pinneberg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1930-09-12"),
  "geheiratetAm": new Date("1953-12-19"),
  "gesellschaft": "11",
  "versorgungsordnung": 74,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1966-01-15"),
  "unternehmensaustritt": new Date("1987-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0410124458"
},

{
  "personalnummer": 145722,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Hans-Jörg Duvigneau",
  "adresse": "Wasgenstr. 39, 14129 Berlin",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1935-06-11"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-06-01"),
  "unternehmensaustritt": new Date("1983-08-31"),
  "ruhegeldfaehigAb": new Date("1966-06-01"),
  "rentenbeginn": new Date("2000-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "030-8018439"
},

{
  "personalnummer": 404850,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Renate Eger",
  "adresse": "Tannenhof 53, 22397 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1937-09-19"),
  "geheiratetAm": new Date("1958-01-31"),
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1963-07-01"),
  "unternehmensaustritt": new Date("1985-04-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1985-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 124859,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Elly Fehlinger",
  "adresse": "Brookwisch 9, 22946 Grossensee",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1926-07-12"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 73,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1963-01-01"),
  "unternehmensaustritt": new Date("1982-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1986-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 500002,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Brigitte Felger",
  "adresse": "Svenborger Str. 24, 24109 Kiel",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1945-12-03"),
  "geheiratetAm": new Date("1964-06-12"),
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1961-10-01"),
  "unternehmensaustritt": new Date("1985-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Pfändung ab 01.05.23 ab Finanzamt Kiel"
},
{
  "personalnummer": 100214,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Gerd Förster",
  "adresse": "Schaumanns­kamp 35, 21465 Reinbek",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1930-07-05"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": "10",
  "unternehmenseintritt": new Date("1971-06-15"),
  "unternehmensaustritt": new Date("1987-06-30"),
  "ruhegeldfaehigAb": new Date("1971-06-01"),
  "rentenbeginn": new Date("1995-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 149211,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Marianne Frenzel",
  "adresse": "Friedenstraße 30, 21335 Lüneburg",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1944-10-12"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-07-01"),
  "unternehmensaustritt": new Date("1986-04-30"),
  "ruhegeldfaehigAb": new Date("1971-09-01"),
  "rentenbeginn": new Date("2004-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 04137-1344"
},

{
  "personalnummer": 403028,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Rita Gloor",
  "adresse": "Friedrich-Friesen-Str 22, 21502 Geesthacht",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1934-08-28"),
  "geheiratetAm": new Date("1953-08-15"),
  "gesellschaft": "11",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-07-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1987-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 124875,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Gisela Gramse",
  "adresse": "Stresemannallee 16, 22529 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1945-10-10"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 78,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1967-05-01"),
  "unternehmensaustritt": new Date("1983-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2010-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 152371,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Heidemarie Gutzeit",
  "adresse": "Klipperstraße 13, 23558 Lübeck",
  "geschlecht": "weiblich",
  "familienstand": "geschieden",
  "geburtsdatum": new Date("1941-10-05"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-11-01"),
  "unternehmensaustritt": new Date("1980-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 404729,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Irmgard Hagemann",
  "adresse": "c/o Herrn Norbert Mahler, Wiesenstraße 4F, 22885 Barsbüttel-Stellau",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1934-04-11"),
  "geheiratetAm": new Date("1953-06-27"),
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1974-08-12"),
  "unternehmensaustritt": new Date("1988-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 157339,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ingrid Hansen",
  "adresse": "Binnenfeldredder 65, 21031 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1938-03-30"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-08-01"),
  "unternehmensaustritt": new Date("1980-09-02"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1980-09-03"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500356,
  "aktuelleStatusgruppe": "Versorgungsausgleich",
  "alteStatusgruppe": null,
  "name": "Elke Harm",
  "adresse": "Gryphiusstraße 12, 22299 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1945-08-05"),
  "geheiratetAm": new Date("1966-07-08"),
  "gesellschaft": "11",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1979-12-31"),
  "ruhegeldfaehigAb": new Date("1968-01-15"),
  "rentenbeginn": new Date("2008-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleichsrente Telefon: 0172 40 17 811"
},

{
  "personalnummer": 976044,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ute Hühner",
  "adresse": "Gungelsbrunnen 8, 21339 Lüneburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1944-03-15"),
  "geheiratetAm": new Date("1972-10-27"),
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-10-01"),
  "unternehmensaustritt": new Date("1988-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1993-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "04131188303"
},

{
  "personalnummer": 500572,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Gisela Jonas",
  "adresse": "Osterrade 61, 24340 Eckernförde",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1930-07-24"),
  "geheiratetAm": new Date("1969-05-23"),
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1964-09-15"),
  "unternehmensaustritt": new Date("1988-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 149039,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Helmut Kappertz",
  "adresse": "Kalker Hauptstraße 222, 51103 Köln",
  "geschlecht": "männlich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1943-08-23"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-04-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2006-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Sohn: Urs Kappertz, 0221 340 37 85"
},

{
  "personalnummer": 149138,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Mohamed Khefacha",
  "adresse": "R 1, No. 4, TN5000 Monastir (Tunesien)",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1942-08-24"),
  "geheiratetAm": new Date("1973-01-11"),
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-08-15"),
  "unternehmensaustritt": new Date("1985-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0021 694 122 600"
},

{
  "personalnummer": 976042,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Renate Kienast",
  "adresse": "Willinghusener Landstr. 33, 22885 Barsbüttel",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1937-03-07"),
  "geheiratetAm": new Date("1964-05-14"),
  "gesellschaft": "11",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-03-01"),
  "unternehmensaustritt": new Date("1987-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2002-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500457,
  "aktuelleStatusgruppe": "Versorgungsausgleich",
  "alteStatusgruppe": null,
  "name": "Waltraut Kinder",
  "adresse": "Schellhorner Straße 4, 24211 Preetz",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1934-05-11"),
  "geheiratetAm": new Date("1954-12-01"),
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-07-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1991-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "04342 87927"
},

{
  "personalnummer": 156810,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Jürgen Koch",
  "adresse": "Buschhagen 2, 22159 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1946-05-25"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": "10",
  "unternehmenseintritt": new Date("1979-07-01"),
  "unternehmensaustritt": new Date("1988-04-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 404075,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Waltraut Kringel",
  "adresse": "Hegholt 52 A, 22179 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1931-09-11"),
  "geheiratetAm": new Date("1951-03-03"),
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-08-15"),
  "unternehmensaustritt": new Date("1987-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1987-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 642 78 77"
},

{
  "personalnummer": 500361,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Lissy Kristandt",
  "adresse": "Tucholskyring 1, 22175 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1935-02-23"),
  "geheiratetAm": new Date("1955-07-02"),
  "gesellschaft": "11",
  "versorgungsordnung": 74,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1961-06-19"),
  "unternehmensaustritt": new Date("1989-06-30"),
  "ruhegeldfaehigAb": new Date("1961-06-19"),
  "rentenbeginn": new Date("1992-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 404894,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Erika Lehmann",
  "adresse": "Teichweg 22, 22949 Ammersbek",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1935-06-21"),
  "geheiratetAm": new Date("1968-01-27"),
  "gesellschaft": "11",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1965-09-15"),
  "unternehmensaustritt": new Date("1980-05-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1980-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 401864,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Inge Martens",
  "adresse": "c/o Herrn Klaus Martens, Sandheideweg 15, 13595 Berlin",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1930-02-15"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-12-01"),
  "unternehmensaustritt": new Date("1983-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1985-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}






















    













              ];

// Axios POST request function
// Axios POST request function
async function insertData() {
  for (let i = 0; i < dataToInsert.length; i++) {
    const person = dataToInsert[i];

    try {
      const response = await axios.post(
        "http://localhost:4000/api/person",
        person
      );

      console.log(`✔️ Inserted personalnummer ${person.personalnummer}`);
    } catch (error) {
      // Wenn der Server geantwortet hat (HTTP-Fehlercode)
      if (error.response) {
        // 400 = existiert schon (so wie du es in deiner Route gebaut hast)
        if (error.response.status === 400) {
          console.warn(
            `⚠️ personalnummer ${person.personalnummer} exists – skipped`
          );
          continue; // optional, macht nur explizit "weiter" zur nächsten Person
        }

        // Andere HTTP-Fehler
        console.error(
          `❌ HTTP ${error.response.status} for personalnummer ${person.personalnummer}:`,
          error.response.data
        );
      } else {
        // Kein Response = z.B. Netzwerkfehler / Server nicht erreichbar
        console.error(
          `❌ Network/Unknown error for personalnummer ${person.personalnummer}:`,
          error.message
        );
      }
    }
  }

  console.log("✅ Import finished.");
}


// Call the function to insert data
insertData();