const axios = require('axios');

const dataToInsert = [
    
    {
  "personalnummer": 976053,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ursula Logemann",
  "adresse": "c/o Christina Dean, 8 Mead Road, UB8 1AU Uxbridge, England",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1937-07-22"),
  "geheiratetAm": new Date("1963-05-22"),
  "gesellschaft": "21",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-04-01"),
  "unternehmensaustritt": new Date("1990-07-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1993-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 976059,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Kaija Bongardt",
  "adresse": "Holzdamm 2B, 50374 Erftstadt",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1940-03-05"),
  "geheiratetAm": new Date("1970-07-14"),
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-01-15"),
  "unternehmensaustritt": new Date("1990-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2006-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 976051,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Dr. Hiltrud Marschner-Schäfer",
  "adresse": "Justus-Brinkmann-Straße 103, 21029 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1940-12-08"),
  "geheiratetAm": new Date("1990-11-16"),
  "gesellschaft": "81A",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-10-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2002-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "1. Ehefrau verstorben, EVA rückgängig"
},

{
  "personalnummer": 976046,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Pirkko Heinz",
  "adresse": "Teutendorfer Weg 23, 23570 Lübeck",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1949-07-30"),
  "geheiratetAm": new Date("1971-06-05"),
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1984-08-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2008-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 04502 85716"
},

{
  "personalnummer": 136457,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Albert Lennertz",
  "adresse": "Büchel 23-25, 52062 Aachen",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1945-01-13"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-09-01"),
  "unternehmensaustritt": new Date("1985-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2010-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 312066,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Reinhard Lischka",
  "adresse": "Saselwiete 2a, 22393 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1939-11-24"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-04-01"),
  "unternehmensaustritt": new Date("1991-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2004-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 122630,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Klaus-Dieter Mack",
  "adresse": "Moosburgstraße 41, I-39023 Laas-Eyrs",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1939-04-15"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1965-09-01"),
  "unternehmensaustritt": new Date("1983-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 141358,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Eckart Maron",
  "adresse": "Dannenkoppel 27, 22391 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1942-12-01"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-10-18"),
  "unternehmensaustritt": new Date("1984-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0174-3894232"
},

{
  "personalnummer": 976027,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Karin Masanek",
  "adresse": "Uppenhof 6, 22359 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1939-02-21"),
  "geheiratetAm": new Date("1966-07-29"),
  "gesellschaft": "81A",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1966-01-01"),
  "unternehmensaustritt": new Date("1989-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1994-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 105288,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Gisela Mehrvarz",
  "adresse": "Necklenbroicher Straße 63e, 40667 Meerbusch",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1941-06-26"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-10-15"),
  "unternehmensaustritt": new Date("1982-02-28"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2004-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 102392,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Peter Naujokat",
  "adresse": "Knesebeckstraße 98 A, 10623 Berlin",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1941-10-22"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-01-01"),
  "unternehmensaustritt": new Date("1979-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2005-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 030: 53007088"
},

{
  "personalnummer": 976032,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ursel Richter",
  "adresse": "Stefanstraße 15, 65795 Hattersheim am Main",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1937-01-02"),
  "geheiratetAm": new Date("1964-11-19"),
  "gesellschaft": "81A",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-05-01"),
  "unternehmensaustritt": new Date("1980-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1995-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 06190 917 129"
},

{
  "personalnummer": 105999,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Wiltraud Ruckes",
  "adresse": "Reichsstraße 55, 40217 Düsseldorf",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1942-01-18"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1965-04-01"),
  "unternehmensaustritt": new Date("1978-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1978-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 976024,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Christel Sairally",
  "adresse": "Eichelhäherkamp 62, 22397 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1937-01-20"),
  "geheiratetAm": new Date("1963-02-22"),
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-05-16"),
  "unternehmensaustritt": new Date("1982-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1998-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 109397,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Hildegard Scheele-Appel",
  "adresse": "Rietzschkeweg 4, 04289 Leipzig",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1941-07-04"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1976-09-16"),
  "unternehmensaustritt": new Date("1984-12-31"),
  "ruhegeldfaehigAb": new Date("1973-06-16"),
  "rentenbeginn": new Date("2001-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 122648,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Dieter Schindler",
  "adresse": "Kreuzbühl 5, 96364 Marktrodach",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1931-11-09"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1965-04-01"),
  "unternehmensaustritt": new Date("1976-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1994-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 09261501729"
},

{
  "personalnummer": 323295,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Peter Schmidt",
  "adresse": "Andersenstraße 23A, 22589 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1947-05-20"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-04-01"),
  "unternehmensaustritt": new Date("1984-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2011-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "823 10152 ?"
},

{
  "personalnummer": 312884,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Ulrich Kurt Schmidt",
  "adresse": "Albert-Schweitzer-Str. 33a, 91710 Gunzenhausen",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1943-03-13"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-08-01"),
  "unternehmensaustritt": new Date("1983-07-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2008-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 09831-8819900"
},

{
  "personalnummer": 500504,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Renate Schmitt",
  "adresse": "Neckarstraße 54, 63263 Neu-Isenburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1950-09-23"),
  "geheiratetAm": new Date("1970-04-29"),
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1976-06-01"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2010-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 976054,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Hildegard Schreiber",
  "adresse": "Wisplerstraße 42, 22609 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1937-04-19"),
  "geheiratetAm": new Date("1960-08-05"),
  "gesellschaft": "81A",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1965-04-20"),
  "unternehmensaustritt": new Date("1984-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0174 463 36 43"
},

{
  "personalnummer": 976007,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Heidi Schroth",
  "adresse": "Tulpenweg 7, 76571 Gaggenau",
  "geschlecht": "weiblich",
  "familienstand": "gesch.",
  "geburtsdatum": new Date("1939-11-14"),
  "geheiratetAm": new Date("1976-10-05"),
  "gesellschaft": "81A",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1964-01-01"),
  "unternehmensaustritt": new Date("1976-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1999-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich"
},

{
  "personalnummer": 500360,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Christa Schulz",
  "adresse": "Dorfstrasse 91a, 25436 Groß Nordende",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1947-12-24"),
  "geheiratetAm": new Date("1965-01-29"),
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-09-01"),
  "unternehmensaustritt": new Date("1991-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 976056,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Renate Schwabe",
  "adresse": "Hinterm See 14, 22946 Großensee",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1934-10-14"),
  "geheiratetAm": new Date("1964-10-01"),
  "gesellschaft": "81A",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1964-04-01"),
  "unternehmensaustritt": new Date("1987-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1991-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500012,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Margret Smrcek",
  "adresse": "Laurembergstieg 3, 22931 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1941-05-25"),
  "geheiratetAm": new Date("1968-07-08"),
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-04-01"),
  "unternehmensaustritt": new Date("1983-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500440,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Lisa Sprecher",
  "adresse": "Sohnstraße 17, 40237 Düsseldorf",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1951-06-20"),
  "geheiratetAm": new Date("1984-12-14"),
  "gesellschaft": "81A",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-01-01"),
  "unternehmensaustritt": new Date("1987-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1991-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "2. Ehe ?????!!!"
},

{
  "personalnummer": 500557,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ute Springer",
  "adresse": "Berner Heerweg 142, 22159 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1940-08-04"),
  "geheiratetAm": new Date("1964-07-17"),
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-08-01"),
  "unternehmensaustritt": new Date("1987-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-02-10"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 01764628806 und 6022756"
},

{
  "personalnummer": 320747,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Joachim Stark",
  "adresse": "Hinsbleek 10, 22391 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1933-11-17"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 78,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1963-10-01"),
  "unternehmensaustritt": new Date("1983-01-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1998-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 976048,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Bärbel Steffens",
  "adresse": "Hufnerstraße 7, 22083 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1940-01-21"),
  "geheiratetAm": new Date("1958-10-25"),
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-10-01"),
  "unternehmensaustritt": new Date("1985-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1997-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 500433,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ingeborg Stinglwagner-Daschil",
  "adresse": "Traminerstraße 21, 81547 München",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1939-06-24"),
  "geheiratetAm": new Date("2010-06-23"),
  "gesellschaft": "81A",
  "versorgungsordnung": 72,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-05-01"),
  "unternehmensaustritt": new Date("1983-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 123018,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Ingo Thiel",
  "adresse": "c/o Frau Anja Ehrhardt, Ginsterweg 18, 19073 Wittenförden",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1941-07-14"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1967-07-01"),
  "unternehmensaustritt": new Date("1984-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2006-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Venezuela; p.Intern: 02161-6399394; email: ingo.thiel@online.de"
},

{
  "personalnummer": 404663,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Magdalena Tooren-Wolff",
  "adresse": "Werrastraße 13, 30519 Hannover",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1947-09-16"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-07-01"),
  "unternehmensaustritt": new Date("1992-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1997-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 108720,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Hans-Christian Unger",
  "adresse": "Freiligrathstr. 7a, 01445 Radebeul",
  "geschlecht": "männlich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1941-10-02"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-12-01"),
  "unternehmensaustritt": new Date("1984-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2005-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500302,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Irene Urban",
  "adresse": "Wiesenbruchstraße 9, 47475 Kamp-Lintfort",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1930-01-09"),
  "geheiratetAm": new Date("1955-08-25"),
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-12-01"),
  "unternehmensaustritt": new Date("1984-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 282194,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Karin Vathke",
  "adresse": "Lauenburger Straße 23, 76139 Karlsruhe",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1947-05-30"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1986-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0721-689317"
},

{
  "personalnummer": 131466,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Klaus Vietor",
  "adresse": "Kritenbarg 3, 22391 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1938-09-15"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1958-09-15"),
  "unternehmensaustritt": new Date("1985-05-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2003-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 606 36 07 0171 9536914, 2. Ehe nach UA"
},

{
  "personalnummer": 311191,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Dietrich Voigt",
  "adresse": "Harburger Straße 80, 21435 Stelle",
  "geschlecht": "männlich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1942-12-12"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-07-15"),
  "unternehmensaustritt": new Date("1982-03-02"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1982-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 322313,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Peter Wels",
  "adresse": "Hemmingsstedter Weg 161, 22609 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1946-03-19"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-06-15"),
  "unternehmensaustritt": new Date("1981-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2011-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich, 2. Ehe nach UA"
},

{
  "personalnummer": 321596,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Wilhelm Wiebelitz",
  "adresse": "Behnkweg 4, 25451 Quickborn",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1946-07-02"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-02-01"),
  "unternehmensaustritt": new Date("1982-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2008-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 04166 769224"
},

{
  "personalnummer": 112888,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Evelyne Wilderius",
  "adresse": "Waldvögeleinstraße 8, 80995 München",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1944-12-23"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-07-01"),
  "unternehmensaustritt": new Date("1979-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2005-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 141317,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Dr. Wolfgang Zemlin",
  "adresse": "Süllbergsterasse 56, 22587 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1944-11-15"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-09-01"),
  "unternehmensaustritt": new Date("1983-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2009-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500244,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Hannelore Dietze",
  "adresse": "Grootkoppel 32b, 22949 Ammersbek",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1943-06-25"),
  "geheiratetAm": new Date("1966-12-16"),
  "gesellschaft": "90",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-04-01"),
  "unternehmensaustritt": new Date("1998-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 976037,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Irmgraut Gensewich",
  "adresse": "Tönninger Weg 13, 22609 Hamburg 52",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1941-10-10"),
  "geheiratetAm": new Date("1974-01-28"),
  "gesellschaft": "90",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-10-16"),
  "unternehmensaustritt": new Date("1998-02-28"),
  "ruhegeldfaehigAb": new Date("1969-10-01"),
  "rentenbeginn": new Date("1998-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 310003,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Rosemarie Grell",
  "adresse": "Fahrenkrön 40, 22179 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1938-05-16"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 76,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1987-01-15"),
  "unternehmensaustritt": new Date("1995-03-31"),
  "ruhegeldfaehigAb": new Date("1983-02-15"),
  "rentenbeginn": new Date("1998-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 976049,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ursula Hawlitzky",
  "adresse": "Berner Str. 3D, 22159 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1946-08-25"),
  "geheiratetAm": new Date("1970-10-02"),
  "gesellschaft": "90",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-10-01"),
  "unternehmensaustritt": new Date("1996-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 132084,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Barbara Holm-Wendel",
  "adresse": "Beim Findling 3, 22869 Schenefeld",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1942-06-07"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 76,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1996-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2002-07-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2025-09-28"),
  "bemerkung": null
},

{
  "personalnummer": 500476,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Renate Horst",
  "adresse": "Schaerstr. 44, 21031 Hamburg 80",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1938-06-16"),
  "geheiratetAm": new Date("1961-06-10"),
  "gesellschaft": "90",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1965-07-01"),
  "unternehmensaustritt": new Date("1997-12-31"),
  "ruhegeldfaehigAb": new Date("1961-03-01"),
  "rentenbeginn": new Date("1998-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon. 739 28 717"
},

{
  "personalnummer": 336685,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Vorruheständler",
  "name": "Albrecht Huck",
  "adresse": "Brombeerweg 17, 21423 Winsen/Luhe",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1938-07-24"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1961-01-01"),
  "unternehmensaustritt": new Date("1998-12-31"),
  "ruhegeldfaehigAb": new Date("1958-10-01"),
  "rentenbeginn": new Date("2000-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}

    






    
       ];
    
     // Axios POST request function
    // Axios POST request function
async function insertData() {
  for (let i = 0; i < dataToInsert.length; i++) {
    const person = dataToInsert[i];

    try {
      const response = await axios.post(
        "http://localhost:4000/api/person",
        person
      );

      console.log(`✔️ Inserted personalnummer ${person.personalnummer}`);
    } catch (error) {
      // Wenn der Server geantwortet hat (HTTP-Fehlercode)
      if (error.response) {
        // 400 = existiert schon (so wie du es in deiner Route gebaut hast)
        if (error.response.status === 400) {
          console.warn(
            `⚠️ personalnummer ${person.personalnummer} exists – skipped`
          );
          continue; // optional, macht nur explizit "weiter" zur nächsten Person
        }

        // Andere HTTP-Fehler
        console.error(
          `❌ HTTP ${error.response.status} for personalnummer ${person.personalnummer}:`,
          error.response.data
        );
      } else {
        // Kein Response = z.B. Netzwerkfehler / Server nicht erreichbar
        console.error(
          `❌ Network/Unknown error for personalnummer ${person.personalnummer}:`,
          error.message
        );
      }
    }
  }

  console.log("✅ Import finished.");
}

    
    // Call the function to insert data
    insertData();