const axios = require('axios');

const dataToInsert = [
    
    
    {
  "personalnummer": 147116,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Gisela Leckband",
  "adresse": "Waldstraße 4A, 24960 Glücksburg",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1936-09-26"),
  "geheiratetAm": new Date("1984-08-24"),
  "gesellschaft": "11",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-08-01"),
  "unternehmensaustritt": new Date("1986-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1994-08-24"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 147157,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Reiner Witt",
  "adresse": "Münterweg 6, 22115 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1935-04-12"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 75,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1968-07-01"),
  "unternehmensaustritt": new Date("1990-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1995-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 147165,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Heinz Rosenlöcher",
  "adresse": "Norra Storgatan 76A, S57334 Tranas, Schweden",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1937-10-15"),
  "geheiratetAm": new Date("1968-05-24"),
  "gesellschaft": "N1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-07-01"),
  "unternehmensaustritt": new Date("1992-01-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-01-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2019-03-26"),
  "bemerkung": "004614014436"
},
{
  "personalnummer": 147199,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Kurt Wunsch",
  "adresse": "Sürhöper Koppelweg 22 A, 21244 Buchholz",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1920-10-17"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 75,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1968-07-15"),
  "unternehmensaustritt": new Date("1980-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1981-01-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2000-03-09"),
  "bemerkung": ""
}
,
{
  "personalnummer": 147207,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Herta Hutner",
  "adresse": "Reichenberger Straße 35, 25421 Pinneberg",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1940-12-20"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 74,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1966-01-01"),
  "unternehmensaustritt": new Date("1995-12-31"),
  "ruhegeldfaehigAb": new Date("1966-02-01"),
  "rentenbeginn": new Date("2001-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,
{
  "personalnummer": 147223,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Dorothea Mann",
  "adresse": "Finnmarkring 6, 22145 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "?",
  "geburtsdatum": new Date("1916-03-02"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 73,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1966-01-01"),
  "unternehmensaustritt": new Date("1979-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1979-04-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2017-07-01"),
  "bemerkung": ""
}
,
{
  "personalnummer": 147249,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Hans Andresen",
  "adresse": "Waterloostr 22, 22769 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1927-07-14"),
  "geheiratetAm": new Date("1951-01-01"),
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1966-02-01"),
  "unternehmensaustritt": new Date("1985-07-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1987-08-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2013-02-15"),
  "bemerkung": ""
}
,
{
  "personalnummer": 147256,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Lieselotte Johannsen",
  "adresse": "c/o Seniorenresidenz, App. 117, Wohldkamp 2, 23669 Timmendorfer Strand",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1929-12-19"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1966-02-01"),
  "unternehmensaustritt": new Date("1986-01-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-01-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2023-10-03"),
  "bemerkung": ""
}
,
{
  "personalnummer": 147264,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Jürgen Zietz",
  "adresse": "Karl-Strutz-Weg 4, 22119 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1940-03-23"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1966-04-01"),
  "unternehmensaustritt": new Date("1984-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2003-04-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2015-01-29"),
  "bemerkung": ""
}
,
{
  "personalnummer": 147272,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Bruno Marx",
  "adresse": "Wüstenhöfener Str. 3, 21255 Dohren",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1926-12-24"),
  "geheiratetAm": new Date("1952-11-15"),
  "gesellschaft": "11",
  "versorgungsordnung": 73,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1961-04-01"),
  "unternehmensaustritt": new Date("1982-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1987-01-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2002-07-15"),
  "bemerkung": ""
}
,
{
  "personalnummer": 147280,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Rosa Domian",
  "adresse": "Bothmannstr. 5a, 22047 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1924-06-15"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-08-15"),
  "unternehmensaustritt": new Date("1979-01-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1984-07-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("1998-10-12"),
  "bemerkung": ""
}
,
{
    "personalnummer": 147298,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Frühpensionäre",
    "name": "Gerda Knittel",
    "adresse": "Barenbleek 30, 22179 Hamburg",
    "geschlecht": "weiblich",
    "familienstand": "verh.",
    "geburtsdatum": new Date("1944-09-07"),
    "geheiratetAm": null,
    "gesellschaft": "90",
    "versorgungsordnung": 76,
    "arbVerhRentTr": 10,
    "unternehmenseintritt": new Date("1971-10-01"),
    "unternehmensaustritt": new Date("1997-12-31"),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date("2004-10-01"),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
  },
  {
    "personalnummer": 147322,
    "aktuelleStatusgruppe": "Verstorbene",
    "alteStatusgruppe": "Altersrentner",
    "name": "Jack Hermann",
    "adresse": "Möllner Landstraße 148a, 22117 Hamburg",
    "geschlecht": "männlich",
    "familienstand": "verh.",
    "geburtsdatum": new Date("1933-09-18"),
    "geheiratetAm": new Date("1958-11-07"),
    "gesellschaft": "11",
    "versorgungsordnung": 71,
    "arbVerhRentTr": 10,
    "unternehmenseintritt": new Date("1961-07-14"),
    "unternehmensaustritt": new Date("1988-12-31"),
    "ruhegeldfaehigAb": new Date("1961-07-01"),
    "rentenbeginn": new Date("1993-10-01"),
    "zusagedatum": null,
    "verstorbenAm": new Date("2002-04-07"),
    "bemerkung": ""
  },
  {
    "personalnummer": 147348,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "---",
    "name": "Anni Azem",
    "adresse": "Walter-Freitag-Straße 20, 21031 Hamburg",
    "geschlecht": "weiblich",
    "familienstand": "verh.",
    "geburtsdatum": new Date("1931-05-13"),
    "geheiratetAm": null,
    "gesellschaft": "N1",
    "versorgungsordnung": 71,
    "arbVerhRentTr": 10,
    "unternehmenseintritt": new Date("1966-05-01"),
    "unternehmensaustritt": new Date("1991-05-31"),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date("1991-06-01"),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "Telefon: 724 66 93"
  },
  {
  "personalnummer": 147363,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Gudrun Deertz",
  "adresse": "c/o Manuela Ruge, Hittendahlplatz 21c, 21447 Handorf",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1936-07-01"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 74,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1966-06-01"),
  "unternehmensaustritt": new Date("1991-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,
{
  "personalnummer": 147371,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Elisabeth Reiche",
  "adresse": "c/o Monika Hilpert, Sudetenstr. 37, 23701 Eutin",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1936-11-20"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 74,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1966-07-01"),
  "unternehmensaustritt": new Date("1991-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "2504197"
}
,

{
  "personalnummer": 147405,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Gerda Bernhorst",
  "adresse": "c/o Insel e.V. Herrn Jacobsen, Heußweg 25, 20255 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1925-08-21"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1966-07-19"),
  "unternehmensaustritt": new Date("1985-08-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1985-09-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2013-09-02"),
  "bemerkung": null
}
,

{
  "personalnummer": 147439,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Wolf-Dietrich Stötzer",
  "adresse": "Heidering 22, 21441 Garstedt",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1936-01-23"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-10-01"),
  "unternehmensaustritt": new Date("1991-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-10-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2004-05-19"),
  "bemerkung": null
}
,

{
  "personalnummer": 147470,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Ingeburg Frenzel",
  "adresse": "c/o Frau I.S. El-Gawaly, Postfach 540 124, 22501 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1919-05-30"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 73,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1966-11-15"),
  "unternehmensaustritt": new Date("1979-05-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1979-06-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2011-04-14"),
  "bemerkung": null
}
,

{
  "personalnummer": 147488,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Paul Hack",
  "adresse": "Loherstr. 9 G, 22149 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1929-06-17"),
  "geheiratetAm": new Date("1954-12-18"),
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1971-09-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-07-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2003-12-02"),
  "bemerkung": null
}
,

{
  "personalnummer": 147496,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Emil Baumann",
  "adresse": "Ringelrosenweg 4c, 22177 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1927-09-26"),
  "geheiratetAm": new Date("1951-06-23"),
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1956-09-01"),
  "unternehmensaustritt": new Date("1984-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1986-04-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2006-01-22"),
  "bemerkung": null
}
,

{
  "personalnummer": 147512,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Friedrich Pschunder",
  "adresse": "Heidhörn 11, 22307 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1915-08-11"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 73,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1950-02-01"),
  "unternehmensaustritt": new Date("1978-08-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1978-09-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("1993-12-23"),
  "bemerkung": null
}
,

{
  "personalnummer": 147546,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Hermann Eger",
  "adresse": "Tannenhof 53, 22397 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1934-04-15"),
  "geheiratetAm": new Date("1958-01-31"),
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1963-07-01"),
  "unternehmensaustritt": new Date("1985-04-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1985-05-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2000-10-31"),
  "bemerkung": null
}
,

{
  "personalnummer": 147553,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Helmuth Hansen",
  "adresse": "Up dem Wiemen 30, 21077 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1922-01-10"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 73,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1963-05-01"),
  "unternehmensaustritt": new Date("1982-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1982-07-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2017-08-06"),
  "bemerkung": "VA-Auskunft"
}
,
{
  "personalnummer": 147561,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Kurt Paetow",
  "adresse": "Geesthachter Straße 20, 21502 Geesthacht",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1922-01-08"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 74,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1959-11-01"),
  "unternehmensaustritt": new Date("1984-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1984-07-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("1999-04-05"),
  "bemerkung": null
}
,
{
  "personalnummer": 147579,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Klaus Rotter",
  "adresse": "Teinstücken 3g, 22525 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1930-08-17"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1960-10-20"),
  "unternehmensaustritt": new Date("1987-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,
{
  "personalnummer": 147587,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Walter Schröder",
  "adresse": "Wohnung Nr. 2113, Zeller Straße 17, 22145 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1914-01-17"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 73,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1963-07-01"),
  "unternehmensaustritt": new Date("1975-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1979-02-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2004-03-05"),
  "bemerkung": null
}
,
{
  "personalnummer": 147595,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Claus Zander",
  "adresse": "Wittland 26 G, 22589 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1928-03-25"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1960-01-16"),
  "unternehmensaustritt": new Date("1985-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-04-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("1995-09-29"),
  "bemerkung": null
}
,

{
  "personalnummer": 147603,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Irmgard Füllkrug",
  "adresse": "Am Thermalbad 1, 31542 Bad Nenndorf",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1923-08-26"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1963-07-01"),
  "unternehmensaustritt": new Date("1977-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1983-09-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2006-02-05"),
  "bemerkung": null
}
,

{
  "personalnummer": 147611,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Frieda Kloppenburg",
  "adresse": "c/o Frau Petra Mielke, Ellerneck 9, 20045 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1914-11-20"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 73,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1962-02-01"),
  "unternehmensaustritt": new Date("1977-11-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1977-12-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2015-11-06"),
  "bemerkung": null
}
,

{
  "personalnummer": 147652,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Hildegard Tabert",
  "adresse": "Röweland 6a, 22419 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1926-01-28"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1946-05-01"),
  "unternehmensaustritt": new Date("1986-01-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1986-02-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2012-11-26"),
  "bemerkung": null
}
,

{
  "personalnummer": 147660,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Willi Freyer",
  "adresse": "An De Drift 4, 23775 Grossenbrode",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1929-02-24"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 74,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1966-08-15"),
  "unternehmensaustritt": new Date("1987-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-03-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("1996-02-02"),
  "bemerkung": null
}
,

{
  "personalnummer": 147694,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Magdalene Bornschein",
  "adresse": "c/o DRK Pflege im Altenheim, Amalienweg 1, 24119 Kronshagen",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1922-01-07"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 73,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1955-02-28"),
  "unternehmensaustritt": new Date("1980-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1980-11-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2000-12-14"),
  "bemerkung": null
}
,
{
  "personalnummer": 147710,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Marieanne Herzig",
  "adresse": "Turkuring 33, 24109 Kiel",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1933-11-12"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 71,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1954-05-01"),
  "unternehmensaustritt": new Date("1988-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1993-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,
{
  "personalnummer": 147728,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Kurt Brunzel",
  "adresse": "Brucknerstr. 10, 23556 Lübeck",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1927-08-25"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 74,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1960-02-01"),
  "unternehmensaustritt": new Date("1990-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1991-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}
,
{
  "personalnummer": 147736,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Anita Schütt",
  "adresse": "Oher Weg 6B, 21509 Glinde",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1923-03-19"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 77,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1971-04-02"),
  "unternehmensaustritt": new Date("1983-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1983-04-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2010-07-12"),
  "bemerkung": "Sohn Rainer Schütt: 7102846, Bornweg 6c, 21509 Glinde"
}
,
{
  "personalnummer": 147744,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Hubertus Kessen",
  "adresse": "Jahnstr. 72 C, 25451 Quickborn",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1932-11-29"),
  "geheiratetAm": new Date("1957-07-16"),
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1971-06-01"),
  "unternehmensaustritt": new Date("1988-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-03-22"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2011-06-16"),
  "bemerkung": "Telefon: 041064242"
}
,
{
  "personalnummer": 147751,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Hans-Peter Pulmer",
  "adresse": "Auering 77, 21629 Neu Wulmsdorf",
  "geschlecht": "männlich",
  "familienstand": "gesch.",
  "geburtsdatum": new Date("1926-12-08"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1971-06-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-01-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2013-03-03"),
  "bemerkung": "Versorgungsausgleich"
}
,
{
  "personalnummer": 147769,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Christa Hoffmann",
  "adresse": "Spann 6, 22848 Norderstedt",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1925-12-10"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 77,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1971-06-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1986-01-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("1996-08-16"),
  "bemerkung": null
}
,
{
  "personalnummer": 147777,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Georg Felger",
  "adresse": "Svenborger Str. 24, 24109 Kiel",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1930-09-28"),
  "geheiratetAm": new Date("1964-06-12"),
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1961-10-01"),
  "unternehmensaustritt": new Date("1985-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-10-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2001-12-03"),
  "bemerkung": null
}
,

{
  "personalnummer": 147793,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Jens Grävenitz",
  "adresse": "Nordlandweg 110, 22145 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1940-11-06"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 74,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1956-04-01"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-01-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2003-05-13"),
  "bemerkung": null
}
,

{
  "personalnummer": 147801,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Christel Gramatzki",
  "adresse": "c/o Frau Wiltraud Kropfganz, Harmsstraße 68, 24114 Kiel",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1934-10-16"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 71,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1961-01-16"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": new Date("1961-01-01"),
  "rentenbeginn": new Date("1994-11-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2010-06-27"),
  "bemerkung": "Tel. Schwägerin: 0431 672711"
}
,

{
  "personalnummer": 147835,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Margarete Ursula Hillebrandt",
  "adresse": "Neue Straße 8, 27726 Worpswede",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1919-06-14"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 73,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1957-01-16"),
  "unternehmensaustritt": new Date("1979-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1979-07-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("1998-12-31"),
  "bemerkung": null
}
,
{
  "personalnummer": 147850,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Elise Hofer",
  "adresse": "Schäferkoppel 1, 24354 Rieseby",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1918-09-08"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 73,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1954-06-24"),
  "unternehmensaustritt": new Date("1978-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1978-10-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2005-03-20"),
  "bemerkung": "Ehemann im Januar 05 verstorben"
}
,
{
  "personalnummer": 147868,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Inge Marriot",
  "adresse": "c/o Frau Petra Roedenbeck-Wachsmann, Lupinenkamp 43, 22339 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1920-08-24"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-08-15"),
  "unternehmensaustritt": new Date("1980-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1981-01-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2014-02-19"),
  "bemerkung": null
}
,
{
  "personalnummer": 147892,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Veit Bichel",
  "adresse": "Oberst-v.-Stauffenberg-Str. 37, 25421 Pinneberg",
  "geschlecht": "männlich",
  "familienstand": "geschieden",
  "geburtsdatum": new Date("1937-11-30"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-07-01"),
  "unternehmensaustritt": new Date("1992-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1997-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich"
}
,
{
  "personalnummer": 147934,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Sigrid Kühl",
  "adresse": "Fockstr. 7/9, 24114 Kiel",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1929-03-07"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1961-01-01"),
  "unternehmensaustritt": new Date("1989-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-04-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("1998-04-20"),
  "bemerkung": null
}
,
{
  "personalnummer": 147967,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Herbert Rath",
  "adresse": "Moorwisch 10, 22547 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1922-04-14"),
  "geheiratetAm": new Date("1950-05-26"),
  "gesellschaft": "11",
  "versorgungsordnung": 75,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1971-01-01"),
  "unternehmensaustritt": new Date("1984-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1984-10-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2002-02-20"),
  "bemerkung": null
}
,
{
  "personalnummer": 147991,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Gudrun Hautmann",
  "adresse": "Enzianstraße 52, 82178 Puchheim",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1944-07-18"),
  "geheiratetAm": null,
  "gesellschaft": "91",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-01-01"),
  "unternehmensaustritt": new Date("1988-08-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2004-08-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2022-02-23"),
  "bemerkung": "08980072738"
}
,
{
  "personalnummer": 148015,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Karl Müller",
  "adresse": "Neumühlener Straße 60, 24148 Kiel",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1923-12-08"),
  "geheiratetAm": new Date("1949-10-01"),
  "gesellschaft": "11",
  "versorgungsordnung": 73,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1954-07-15"),
  "unternehmensaustritt": new Date("1978-08-15"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1978-08-16"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2004-12-16"),
  "bemerkung": ""
}
,

{
  "personalnummer": 148072,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Hanna Becker",
  "adresse": "Heidhoern 13, 22307 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1924-06-19"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 75,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1971-01-01"),
  "unternehmensaustritt": new Date("1984-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1984-07-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("1995-04-10"),
  "bemerkung": ""
}
,

{
  "personalnummer": 148098,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Greta Sibbert",
  "adresse": "c/o Anke Czarnetzki, Hindenburg Str. 5, 72622 Nürtingen",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1935-02-15"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1960-01-01"),
  "unternehmensaustritt": new Date("1985-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1985-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "07022 30 84 380"
}
,

{
  "personalnummer": 148106,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Lothar Scheduikat",
  "adresse": "c/o Christine Kiek, Unterstkoppel 9, 24222 Schwentinental",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1929-06-09"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1961-09-01"),
  "unternehmensaustritt": new Date("1985-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-07-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2025-05-30"),
  "bemerkung": ""
}
,

{
  "personalnummer": 148122,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Gerhard Petri",
  "adresse": "Bielfeldtstraße 14, 22763 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1933-03-15"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1987-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1994-12-08"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 148130,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Leonhard Hoffmann",
  "adresse": "Koesliner Str. 38, 22147 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1934-12-06"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": "10",
  "unternehmenseintritt": new Date("1972-11-01"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}
,

{
  "personalnummer": 148171,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Peter Philipsen",
  "adresse": "Ebnetstraße 11, 88239 Wangen i. Allgäu",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1941-02-18"),
  "geheiratetAm": new Date("1994-01-01"),
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": "",
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1982-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2004-03-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2015-07-04"),
  "bemerkung": "Versorgungsausgleich"
}
,

{
  "personalnummer": 148221,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Herbert Wrage",
  "adresse": "Wernigeroder Weg 8c, 22455 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1914-01-08"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 73,
  "arbVerhRentTr": "10",
  "unternehmenseintritt": new Date("1961-01-01"),
  "unternehmensaustritt": new Date("1975-11-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1979-02-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("1995-11-16"),
  "bemerkung": ""
}
,

{
  "personalnummer": 148239,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Kay Zigelski",
  "adresse": "Birkenweg 9, 24211 Preetz",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1925-05-13"),
  "geheiratetAm": new Date("1950-06-10"),
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": "10",
  "unternehmenseintritt": new Date("1957-05-01"),
  "unternehmensaustritt": new Date("1984-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1986-01-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2002-09-20"),
  "bemerkung": ""
}
,

{
  "personalnummer": 148247,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Werner Ohlmann",
  "adresse": "Swebenbrunnen 13f, 22159 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1921-11-23"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": "10",
  "unternehmenseintritt": new Date("1955-09-01"),
  "unternehmensaustritt": new Date("1983-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1984-12-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2011-02-06"),
  "bemerkung": ""
}
,

{
  "personalnummer": 148262,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Curt Westphal",
  "adresse": "Rosenhof, Hoisdorfer Landstr. 72, App. 3, 22927 Großhansdorf",
  "geschlecht": "männlich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1924-11-20"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": "10",
  "unternehmenseintritt": new Date("1955-03-15"),
  "unternehmensaustritt": new Date("1986-11-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1987-01-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2014-08-19"),
  "bemerkung": "Telefon: 04102/7077725"
}
,

{
  "personalnummer": 148346,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Helga Braun",
  "adresse": "c/o Jaschar Tavenamehr, Lassenweg 9, 24220 Flintbek",
  "geschlecht": "weiblich",
  "familienstand": "gesch",
  "geburtsdatum": new Date("1936-01-13"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-02-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2025-03-26"),
  "bemerkung": ""
}
,

{
  "personalnummer": 148379,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Wilko Freiherr von Wintzingerode",
  "adresse": "Hermann-Kätelhön-Str. 15, 59519 Möhnesee",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1941-08-08"),
  "geheiratetAm": null,
  "gesellschaft": "902",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1974-09-01"),
  "unternehmensaustritt": new Date("2006-08-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2006-09-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2021-12-02"),
  "bemerkung": "Telefon: 02924-7881"
}
,

{
  "personalnummer": 148445,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Marianne Schalk",
  "adresse": "Rügendamm 3, 24226 Heikendorf",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1929-12-29"),
  "geheiratetAm": new Date("1992-05-19"),
  "gesellschaft": "11",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1965-10-01"),
  "unternehmensaustritt": new Date("1981-01-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-01-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2015-08-07"),
  "bemerkung": ""
}
,

{
  "personalnummer": 148502,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Alfred Nevermann",
  "adresse": "Kolberger Platz 1, 23558 Lübeck",
  "geschlecht": "männlich",
  "familienstand": "geschieden",
  "geburtsdatum": new Date("1931-01-04"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1953-04-16"),
  "unternehmensaustritt": new Date("1986-01-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1991-02-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("1995-02-15"),
  "bemerkung": ""
}
,

{
  "personalnummer": 148510,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Heinrich Swidersky",
  "adresse": "In der Niederung 9b, 22047 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1918-01-30"),
  "geheiratetAm": new Date("1983-12-31"),
  "gesellschaft": "11",
  "versorgungsordnung": 73,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1966-07-01"),
  "unternehmensaustritt": new Date("1979-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1979-07-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("1993-11-27"),
  "bemerkung": ""
}
,


{
  "personalnummer": 148577,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Heinrich Christiansen",
  "adresse": "Püttenhorst 31, 21035 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1928-09-06"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1972-10-01"),
  "unternehmensaustritt": new Date("1986-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-10-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2004-12-06"),
  "bemerkung": "Eheschließung nach UA"
}
,

{
  "personalnummer": 148585,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Waltraud Gildenast",
  "adresse": "bei Herrn B. Zimmermann, Stadermoor 56, 21683 Stade",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1925-01-25"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1967-10-01"),
  "unternehmensaustritt": new Date("1979-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1985-02-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2020-05-09"),
  "bemerkung": "2. Ehe 0451 7070159"
}
,

{
  "personalnummer": 148619,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Margret Heim",
  "adresse": "Kleiststr 11, 23617 Stockelsdorf",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1932-02-28"),
  "geheiratetAm": new Date("1985-12-20"),
  "gesellschaft": "N1",
  "versorgungsordnung": 75,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1968-10-01"),
  "unternehmensaustritt": new Date("1988-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1992-03-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2023-06-24"),
  "bemerkung": null
}
,

{
  "personalnummer": 148643,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Margot Klein",
  "adresse": "c/o Herrn Jörg Hustedt, Postfach 730269, 22122 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1923-12-02"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 77,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1973-08-01"),
  "unternehmensaustritt": new Date("1984-04-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1984-05-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2022-03-16"),
  "bemerkung": "gesetzlicher Betreuer"
}
,

{
  "personalnummer": 148676,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Werner Tyx",
  "adresse": "Hinschenfelder Stücken 3, 22047 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1926-01-17"),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-05-01"),
  "unternehmensaustritt": new Date("1985-01-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1986-02-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("1996-09-04"),
  "bemerkung": null
}
,

{
  "personalnummer": 148692,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Horst Wiehler",
  "adresse": "Kriemhildstraße 15 Haus D, 22559 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1928-12-07"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1970-01-01"),
  "unternehmensaustritt": new Date("1990-07-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1992-01-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2014-12-22"),
  "bemerkung": "Telefon: 01734619344"
}
,

{
  "personalnummer": 148742,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Ingrid Garbe-Kraemmer",
  "adresse": "Langgade 46, DK4874 Gedser",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1948-06-16"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-07-01"),
  "unternehmensaustritt": new Date("1986-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2010-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Eheschließung nach Austritt"
}
,

{
  "personalnummer": 148759,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Wolfgang Kinder",
  "adresse": "Rosenstraße 8b, 24582 Wattenbek",
  "geschlecht": "männlich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1931-01-24"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1972-07-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1991-02-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2014-03-14"),
  "bemerkung": "VA, Telefon: 04322-692451"
}
,

{
  "personalnummer": 148809,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Marlene Ertel",
  "adresse": "c/o Andrea Hessler, Dorotheenstraße 55, 22301 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1939-01-19"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-08-15"),
  "unternehmensaustritt": new Date("1986-02-28"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2002-02-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2024-09-09"),
  "bemerkung": null
}
,

{
  "personalnummer": 148890,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Karl-Friedrich Hühner",
  "adresse": "Gungelsbrunnen 8, 21339 Lüneburg",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1933-10-21"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1972-10-01"),
  "unternehmensaustritt": new Date("1988-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1993-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "04131188303"
}
,

{
  "personalnummer": 148916,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Udo Schütt",
  "adresse": "Appener Weg 6, 20251 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1942-05-26"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-11-01"),
  "unternehmensaustritt": new Date("1987-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "?"
}







 

 
 ];




 // Axios POST request function
// Axios POST request function
async function insertData() {
  for (let i = 0; i < dataToInsert.length; i++) {
    const person = dataToInsert[i];

    try {
      const response = await axios.post(
        "http://localhost:4000/api/person",
        person
      );

      console.log(`✔️ Inserted personalnummer ${person.personalnummer}`);
    } catch (error) {
      // Wenn der Server geantwortet hat (HTTP-Fehlercode)
      if (error.response) {
        // 400 = existiert schon (so wie du es in deiner Route gebaut hast)
        if (error.response.status === 400) {
          console.warn(
            `⚠️ personalnummer ${person.personalnummer} exists – skipped`
          );
          continue; // optional, macht nur explizit "weiter" zur nächsten Person
        }

        // Andere HTTP-Fehler
        console.error(
          `❌ HTTP ${error.response.status} for personalnummer ${person.personalnummer}:`,
          error.response.data
        );
      } else {
        // Kein Response = z.B. Netzwerkfehler / Server nicht erreichbar
        console.error(
          `❌ Network/Unknown error for personalnummer ${person.personalnummer}:`,
          error.message
        );
      }
    }
  }

  console.log("✅ Import finished.");
}


// Call the function to insert data
insertData();