const axios = require('axios');

const dataToInsert = [




    {
    "personalnummer": 136523,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Hans-Dietrich Oerding",
    "adresse": "Am Berge 28, 21629 Neu Wulmsdorf",
    "geschlecht": "männlich",
    "familienstand": null,
    "geburtsdatum": new Date('1944-05-03'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1972-01-01'),
    "unternehmensaustritt": new Date('1982-02-28'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2009-06-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 500046,
    "aktuelleStatusgruppe": "Hinterbliebene",
    "alteStatusgruppe": null,
    "name": "Elke Nandy",
    "adresse": "c/o Max-Brauer-Haus, Hohnerredder 21a, 22175 Hamburg",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1940-01-01'),
    "geheiratetAm": new Date('1964-09-18'),
    "gesellschaft": "81A",
    "versorgungsordnung": 71,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1963-05-01'),
    "unternehmensaustritt": new Date('1984-01-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1984-02-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 500550,
    "aktuelleStatusgruppe": "Hinterbliebene",
    "alteStatusgruppe": null,
    "name": "Hannelore Naefken",
    "adresse": "Sonnenredder 70, 22045 Hamburg",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1943-08-25'),
    "geheiratetAm": new Date('1964-07-17'),
    "gesellschaft": "81A",
    "versorgungsordnung": 75,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1967-04-01'),
    "unternehmensaustritt": new Date('1990-09-30'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1990-10-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "040715 81 96"
},

{
    "personalnummer": 104752,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Heinz-Peter Moseler",
    "adresse": "Uhlenkoog 25, 24113 Kiel",
    "geschlecht": "männlich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1939-10-08'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1973-01-09'),
    "unternehmensaustritt": new Date('1981-08-31'),
    "ruhegeldfaehigAb": new Date('1971-09-09'),
    "rentenbeginn": new Date('2003-06-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "Telefon: 0431-6594515"
},

{
    "personalnummer": 283002,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Thomas Mörder",
    "adresse": "Von-Andrianstraße 8, 83620 Feldkirchen-Westerham",
    "geschlecht": "männlich",
    "familienstand": "VA",
    "geburtsdatum": new Date('1942-04-26'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1973-04-01'),
    "unternehmensaustritt": new Date('1983-12-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2006-05-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 310979,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Frühpensionäre",
    "name": "Günter Möller",
    "adresse": "Großer Ring 41c, 25492 Heist",
    "geschlecht": "männlich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1933-09-06'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 75,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1968-10-01'),
    "unternehmensaustritt": new Date('1989-08-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1993-10-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 313130,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Gertrud Möllenkamp",
    "adresse": "Lange Hecke 37, 37130 Gleichen",
    "geschlecht": "weiblich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1952-08-12'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1978-07-01'),
    "unternehmensaustritt": new Date('1989-08-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2018-03-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 322958,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Ursula Meyer",
    "adresse": "Up de Worth 39, 22391 Hamburg",
    "geschlecht": "weiblich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1947-12-06'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 77,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1969-10-01'),
    "unternehmensaustritt": new Date('1983-09-30'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2013-02-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 311472,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Hajo Meyer",
    "adresse": "Muchallstraße 13, 26789 Leer/Ostfr.",
    "geschlecht": "männlich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1943-07-05'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1972-01-01'),
    "unternehmensaustritt": new Date('1985-04-30'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2003-08-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 500416,
    "aktuelleStatusgruppe": "Hinterbliebene",
    "alteStatusgruppe": null,
    "name": "Lotte Mey",
    "adresse": "Plathweg 9, 22307 Hamburg",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1931-08-06'),
    "geheiratetAm": new Date('1963-05-27'),
    "gesellschaft": "81A",
    "versorgungsordnung": 75,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1969-04-01'),
    "unternehmensaustritt": new Date('1989-12-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1994-04-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
"personalnummer": 131573,
"aktuelleStatusgruppe": "Altersrentner",
"alteStatusgruppe": "Frühpensionäre",
"name": "Manfred-Hermann Mex",
"adresse": "Am Mühlenberg 28, 21271 Asendorf",
"geschlecht": "männlich",
"familienstand": "verh.",
"geburtsdatum": new Date('1939-05-20'),
"geheiratetAm": null,
"gesellschaft": "81A",
"versorgungsordnung": 77,
"arbVerhRentTr": null,
"unternehmenseintritt": new Date('1969-02-01'),
"unternehmensaustritt": new Date('1995-03-31'),
"ruhegeldfaehigAb": null,
"rentenbeginn": new Date('1999-06-01'),
"zusagedatum": null,
"verstorbenAm": null,
"bemerkung": ""
},

{
"personalnummer": 500263,
"aktuelleStatusgruppe": "Hinterbliebene",
"alteStatusgruppe": null,
"name": "Dr. Margot Lehner-Siegmund",
"adresse": "Unsöldstraße 14, 80538 München",
"geschlecht": "weiblich",
"familienstand": "verw.",
"geburtsdatum": new Date('1942-05-27'),
"geheiratetAm": null,
"gesellschaft": "81A",
"versorgungsordnung": 78,
"arbVerhRentTr": null,
"unternehmenseintritt": new Date('1962-05-01'),
"unternehmensaustritt": new Date('1979-12-31'),
"ruhegeldfaehigAb": new Date('1959-09-01'),
"rentenbeginn": new Date('1987-04-01'),
"zusagedatum": null,
"verstorbenAm": null,
"bemerkung": ""
},

{
"personalnummer": 500496,
"aktuelleStatusgruppe": "Hinterbliebene",
"alteStatusgruppe": null,
"name": "Wiltrud Laufer",
"adresse": "Schlebuschweg 23a, 21029 Hamburg",
"geschlecht": "weiblich",
"familienstand": "verw.",
"geburtsdatum": new Date('1938-12-12'),
"geheiratetAm": null,
"gesellschaft": "81A",
"versorgungsordnung": 71,
"arbVerhRentTr": null,
"unternehmenseintritt": new Date('1966-01-01'),
"unternehmensaustritt": new Date('1984-12-31'),
"ruhegeldfaehigAb": null,
"rentenbeginn": new Date('1996-06-01'),
"zusagedatum": null,
"verstorbenAm": null,
"bemerkung": ""
},

{
"personalnummer": 319160,
"aktuelleStatusgruppe": "Altersrentner",
"alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
"name": "Dieter Lange",
"adresse": "Möhlenbarg 21, 22848 Norderstedt",
"geschlecht": "männlich",
"familienstand": "ledig",
"geburtsdatum": new Date('1941-04-19'),
"geheiratetAm": null,
"gesellschaft": "81A",
"versorgungsordnung": 77,
"arbVerhRentTr": null,
"unternehmenseintritt": new Date('1969-01-01'),
"unternehmensaustritt": new Date('1984-10-31'),
"ruhegeldfaehigAb": null,
"rentenbeginn": new Date('2006-05-01'),
"zusagedatum": null,
"verstorbenAm": null,
"bemerkung": ""
},

{
"personalnummer": 102574,
"aktuelleStatusgruppe": "Altersrentner",
"alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
"name": "Ingrid Lampe",
"adresse": "Curtiusweg 20, 27749 Delmenhorst",
"geschlecht": "weiblich",
"familienstand": "verh.",
"geburtsdatum": new Date('1944-09-07'),
"geheiratetAm": null,
"gesellschaft": "81A",
"versorgungsordnung": 77,
"arbVerhRentTr": null,
"unternehmenseintritt": new Date('1970-01-01'),
"unternehmensaustritt": new Date('1982-10-19'),
"ruhegeldfaehigAb": null,
"rentenbeginn": new Date('2009-10-01'),
"zusagedatum": null,
"verstorbenAm": null,
"bemerkung": "Telefon: 0422162488"
},

{
    "personalnummer": 500498,
    "aktuelleStatusgruppe": "Hinterbliebene",
    "alteStatusgruppe": null,
    "name": "Käthe Krifft",
    "adresse": "Amselweg 2, 41849 Wassenberg",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1936-08-31'),
    "geheiratetAm": new Date('1961-04-14'),
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1971-01-01'),
    "unternehmensaustritt": new Date('1981-03-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1992-08-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 319368,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Anni Kohlmey",
    "adresse": "Georg-Kerschensteiner-Str. 17, 23554 Lübeck",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1940-08-10'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1973-10-01'),
    "unternehmensaustritt": new Date('1984-03-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2005-09-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 105130,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Karl-Heinz Klärding",
    "adresse": "Karl-Marx-Allee 142, 52066 Aachen",
    "geschlecht": "männlich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1936-08-07'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1971-01-01'),
    "unternehmensaustritt": new Date('1985-03-19'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1996-09-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "0031455728210, L.T.M. Weg 22, NL 6412 BP Heerlen Niederlande"
},

{
    "personalnummer": 108951,
    "aktuelleStatusgruppe": "Verstorbene",
    "alteStatusgruppe": "Altersrentner",
    "name": "Ingrid Kerth",
    "adresse": "c/o Frau Dr. jur. E. Portz, Imlangelfeld 10a, 61350 Bad Homburg vor der Höhe",
    "geschlecht": "weiblich",
    "familienstand": "gesch.",
    "geburtsdatum": new Date('1942-05-08'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 75,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1972-10-01'),
    "unternehmensaustritt": new Date('1984-12-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1985-01-01'),
    "zusagedatum": null,
    "verstorbenAm": new Date('2023-12-19'),
    "bemerkung": ""
},

{
    "personalnummer": 319681,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Joachim Kasten",
    "adresse": "Kirchenstraße 340, 22946 Trittau",
    "geschlecht": "männlich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1942-09-20'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 71,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1976-11-01'),
    "unternehmensaustritt": new Date('1983-12-31'),
    "ruhegeldfaehigAb": new Date('1966-09-01'),
    "rentenbeginn": new Date('2006-01-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "Versorgungsausgleich Telefon: 04107 908847"
},

{
    "personalnummer": 404041,
    "aktuelleStatusgruppe": "Verstorbene",
    "alteStatusgruppe": "Hinterbliebene",
    "name": "Anneliese Kaden",
    "adresse": "c/o Gerald Kaden, Hermsdorfer Damm 106, 13467 Berlin",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1927-08-19'),
    "geheiratetAm": new Date('1953-02-14'),
    "gesellschaft": "81A",
    "versorgungsordnung": 71,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1965-05-01'),
    "unternehmensaustritt": new Date('1984-12-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1990-09-01'),
    "zusagedatum": null,
    "verstorbenAm": new Date('2025-04-11'),
    "bemerkung": "ab 11.20 auf Barzahlung"
},

{
    "personalnummer": 108225,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Peter Janssen",
    "adresse": "Ulrichstraße 109, 60433 Frankfurt",
    "geschlecht": "männlich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1939-12-20'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 77,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1970-10-01'),
    "unternehmensaustritt": new Date('1981-01-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2000-01-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 403241,
    "aktuelleStatusgruppe": "Hinterbliebene",
    "alteStatusgruppe": null,
    "name": "Annegret Hoffmeyer",
    "adresse": "Gerhart-Hauptmann-Ring 388, 60439 Frankfurt/Main",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1929-09-12'),
    "geheiratetAm": new Date('1950-06-10'),
    "gesellschaft": "81A",
    "versorgungsordnung": 71,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1965-04-01'),
    "unternehmensaustritt": new Date('1985-06-30'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1989-12-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "Telefon: 069-57 56 47"
},
{
    "personalnummer": 105072,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Hartger Hoefs",
    "adresse": "Krottstraße 11–13, 52146 Würselen",
    "geschlecht": "männlich",
    "familienstand": null,
    "geburtsdatum": new Date('1943-05-23'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1971-10-15'),
    "unternehmensaustritt": new Date('1990-03-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2008-06-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "Telefon: 02405 40 684 24"
},
{
    "personalnummer": 500530,
    "aktuelleStatusgruppe": "Hinterbliebene",
    "alteStatusgruppe": null,
    "name": "Lore Hirrlinger",
    "adresse": "Wiflingshauser Straße 129, 73732 Eßlingen",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1928-08-09'),
    "geheiratetAm": new Date('2018-08-28'),
    "gesellschaft": "81A",
    "versorgungsordnung": 82,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1973-01-01'),
    "unternehmensaustritt": new Date('1986-06-30'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1986-07-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 178087,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Birgit Hermann",
    "adresse": "Hühnerwinkel 10, 31191 Algermissen",
    "geschlecht": "weiblich",
    "familienstand": null,
    "geburtsdatum": new Date('1945-12-13'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 77,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1969-01-01'),
    "unternehmensaustritt": new Date('1983-06-30'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2007-12-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 131748,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Christel Hauptvogel",
    "adresse": "Hochfeld 44, 22607 Hamburg",
    "geschlecht": "weiblich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1941-12-24'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 71,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1966-05-01'),
    "unternehmensaustritt": new Date('1990-09-30'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2002-01-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 104653,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Dieter Gusko",
    "adresse": "Droysenstraße 7, 10629 Berlin",
    "geschlecht": "männlich",
    "familienstand": null,
    "geburtsdatum": new Date('1937-12-05'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1973-06-15'),
    "unternehmensaustritt": new Date('1989-03-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2002-04-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 401714,
    "aktuelleStatusgruppe": "Verstorbene",
    "alteStatusgruppe": "Hinterbliebene",
    "name": "Helgard Grothe",
    "adresse": "Nidaforum 11, 60439 Frankfurt",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1929-07-26'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 71,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1962-10-01'),
    "unternehmensaustritt": new Date('1983-12-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1987-01-01'),
    "zusagedatum": null,
    "verstorbenAm": new Date('2024-12-06'),
    "bemerkung": ""
},

{
    "personalnummer": 310573,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Vorruheständler",
    "name": "Arno Grabbert",
    "adresse": "Budapester Straße 14, 21423 Winsen",
    "geschlecht": "männlich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1936-03-04'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 77,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1968-01-01'),
    "unternehmensaustritt": new Date('1994-12-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1999-04-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 141457,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Rosaria Gigas",
    "adresse": "Friedenstraße 4, 21614 Buxtehude",
    "geschlecht": "weiblich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1947-04-09'),
    "geheiratetAm": new Date('1969-01-24'),
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1978-04-01'),
    "unternehmensaustritt": new Date('1993-06-30'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2008-05-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "Telefon: 04161 722216"
},

{
    "personalnummer": 976038,
    "aktuelleStatusgruppe": "Hinterbliebene",
    "alteStatusgruppe": null,
    "name": "Ramona Gardosch",
    "adresse": "Zum See 7, 14542 Werder",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1954-12-03'),
    "geheiratetAm": new Date('2008-01-05'),
    "gesellschaft": "81A",
    "versorgungsordnung": 81,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1969-01-01'),
    "unternehmensaustritt": new Date('1982-12-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1990-12-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "Verzicht auf Anp. 1.12.96, 2. Ehe ? !!!! 03384 590 933"
},

{
    "personalnummer": 315218,
    "aktuelleStatusgruppe": "Hinterbliebene",
    "alteStatusgruppe": null,
    "name": "Sigrid Otte",
    "adresse": "Forstweg 4, 27777 Ganderkesee",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1944-01-26'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 77,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1970-02-01'),
    "unternehmensaustritt": new Date('1983-04-15'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1985-11-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 500561,
    "aktuelleStatusgruppe": "Hinterbliebene",
    "alteStatusgruppe": null,
    "name": "Ute Pabst",
    "adresse": "Pfadstr. 18, 71069 Sindelfingen",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1940-07-20'),
    "geheiratetAm": new Date('1962-09-06'),
    "gesellschaft": "61",
    "versorgungsordnung": 71,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1959-10-01'),
    "unternehmensaustritt": new Date('1986-12-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1988-04-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "Telefon: 07031 384 173"
},

{
    "personalnummer": 500485,
    "aktuelleStatusgruppe": "Hinterbliebene",
    "alteStatusgruppe": null,
    "name": "Maria Passarge",
    "adresse": "Ostlandstraße 3a, 30982 Pattensen",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1952-07-04'),
    "geheiratetAm": new Date('1973-12-28'),
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1972-04-01'),
    "unternehmensaustritt": new Date('1994-09-30'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1998-12-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "05066 - 4738"
},

{
    "personalnummer": 215459,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Birgit Peikert",
    "adresse": "Driburger Straße 5, 40472 Düsseldorf",
    "geschlecht": "weiblich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1953-11-21'),
    "geheiratetAm": new Date('2002-03-01'),
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1978-10-01'),
    "unternehmensaustritt": new Date('1988-12-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2014-12-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 112649,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Ingelore Pflegel",
    "adresse": "Innere Wiener Straße 10, 81667 München",
    "geschlecht": "weiblich",
    "familienstand": "ledig",
    "geburtsdatum": new Date('1945-10-28'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1970-11-01'),
    "unternehmensaustritt": new Date('1981-09-30'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2010-07-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 318501,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Gisela Piel",
    "adresse": "Birkenweg 16, 25782 Tellingstedt",
    "geschlecht": "weiblich",
    "familienstand": "gesch.",
    "geburtsdatum": new Date('1936-09-22'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1972-01-01'),
    "unternehmensaustritt": new Date('1983-07-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1996-10-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 131839,
    "aktuelleStatusgruppe": "Verstorbene",
    "alteStatusgruppe": "Altersrentner",
    "name": "Uwe Rabe",
    "adresse": "Huder Fähre Fährweg 4, 25876 Hude/Nordfriesland",
    "geschlecht": "männlich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1931-07-18'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 77,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1969-01-01'),
    "unternehmensaustritt": new Date('1984-12-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1993-01-01'),
    "zusagedatum": null,
    "verstorbenAm": new Date('2025-04-14'),
    "bemerkung": ""
},
{
    "personalnummer": 281683,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Marika Raichle",
    "adresse": "Torweg 14, 73277 Owen/Teck",
    "geschlecht": "weiblich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1942-10-12'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 77,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1970-07-01'),
    "unternehmensaustritt": new Date('1981-09-30'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2002-11-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},
{
    "personalnummer": 132357,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Frühpensionäre",
    "name": "Erika Rau",
    "adresse": "Bockhorst 122, 22589 Hamburg",
    "geschlecht": "weiblich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1935-09-23'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1974-01-10'),
    "unternehmensaustritt": new Date('1990-09-30'),
    "ruhegeldfaehigAb": new Date('1974-01-01'),
    "rentenbeginn": new Date('1995-10-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "Telefon: 827571, 0176 571 935 00"
},
{
    "personalnummer": 500318,
    "aktuelleStatusgruppe": "Hinterbliebene",
    "alteStatusgruppe": null,
    "name": "Erika Reibold",
    "adresse": "Abrahamstraße 4, 22145 Hamburg",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1937-03-18'),
    "geheiratetAm": new Date('1958-11-29'),
    "gesellschaft": "81A",
    "versorgungsordnung": 71,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1962-06-15'),
    "unternehmensaustritt": new Date('1985-12-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1999-08-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "Telefon: 040/6782341"
},

{
    "personalnummer": 311340,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Frühpensionäre",
    "name": "Helmut Richter",
    "adresse": "Siedlerstraße 17, 58313 Herdecke",
    "geschlecht": "männlich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1935-06-15'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 77,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1968-04-01'),
    "unternehmensaustritt": new Date('1991-03-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1995-07-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "Telefon: 02330-9100345"
},

{
    "personalnummer": 157362,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Gisela Richter-Hansen",
    "adresse": "Reesenbüttler Redder 43a, 22926 Ahrensburg",
    "geschlecht": "weiblich",
    "familienstand": null,
    "geburtsdatum": new Date('1954-08-24'),
    "geheiratetAm": null,
    "gesellschaft": "N1",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1980-10-01'),
    "unternehmensaustritt": new Date('1990-12-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2020-06-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "Telefon: 0171 68 23 206"
},

{
    "personalnummer": 141432,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Jürgen Ritze",
    "adresse": "Schöner Blick 6, 22587 Hamburg",
    "geschlecht": "männlich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1941-04-30'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 71,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1965-06-01'),
    "unternehmensaustritt": new Date('1985-06-30'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2006-05-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 100511,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Friedo Röhrs",
    "adresse": "Gunsbüttel 7, 25870 Oldenswort",
    "geschlecht": "männlich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1938-11-03'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1971-04-01'),
    "unternehmensaustritt": new Date('1984-12-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2001-01-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},

{
    "personalnummer": 500306,
    "aktuelleStatusgruppe": "Hinterbliebene",
    "alteStatusgruppe": null,
    "name": "Mirsada Roznjakovic",
    "adresse": "Elligersweg 77, 22307 Hamburg",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1955-05-28'),
    "geheiratetAm": new Date('1981-10-08'),
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1971-10-01'),
    "unternehmensaustritt": new Date('1981-12-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1991-08-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "Sohn: 017623 55 49 09"
},

{
        "personalnummer": 500568,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Brügel",
        "adresse": "Schillerstraße 82, 73033 Göppingen",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1944-09-25'),
        "geheiratetAm": new Date('1966-08-30'),
        "gesellschaft": "N1",
        "versorgungsordnung": 71,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1966-06-01'),
        "unternehmensaustritt": new Date('1988-12-31'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('1998-04-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "07391 419 68 und 0716 11 38 52"
},

	{
        "personalnummer": 136093,
        "aktuelleStatusgruppe": "Altersrentner",
        "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
        "name": "Rudolf Aberle",
        "adresse": "Höhenringstraße 10, 82256 Fürstenfeldbruck",
        "geschlecht": "männlich",
        "familienstand": "verh.",
        "geburtsdatum": new Date('1940-02-12'),
        "geheiratetAm": null,
        "gesellschaft": "81A",
        "versorgungsordnung": 76,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1971-10-01'),
        "unternehmensaustritt": new Date('1984-06-22'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('2004-10-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": ""
    },
	
	{
        "personalnummer": 100939,
        "aktuelleStatusgruppe": "Verstorbene",
        "alteStatusgruppe": "Altersrentner",
        "name": "Peter Antoni",
        "adresse": "Mellenbergstieg 7, 22359 Hamburg",
        "geschlecht": "männlich",
        "familienstand": "verh.",
        "geburtsdatum": new Date('1940-05-19'),
        "geheiratetAm": null,
        "gesellschaft": "81A",
        "versorgungsordnung": 79,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1970-01-01'),
        "unternehmensaustritt": new Date('1980-02-29'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('2003-11-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "Telefon: 040/519 06613"
    },
	
	{
        "personalnummer": 131159,
        "aktuelleStatusgruppe": "Altersrentner",
        "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
        "name": "Gabriele Balke",
        "adresse": "An der Au 2, 25376 Borsfleth",
        "geschlecht": "weiblich",
        "familienstand": "verh.",
        "geburtsdatum": new Date('1952-09-14'),
        "geheiratetAm": null,
        "gesellschaft": "81A",
        "versorgungsordnung": 76,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1972-10-01'),
        "unternehmensaustritt": new Date('1988-12-24'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('2013-11-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": ""
    },
	
	{
        "personalnummer": 500536,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Gisela Becker",
        "adresse": "Borchlingweg 44, 22605 Hamburg",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1942-12-22'),
        "geheiratetAm": new Date('1988-08-18'),
        "gesellschaft": "81A",
        "versorgungsordnung": 71,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1960-03-01'),
        "unternehmensaustritt": new Date('1991-07-31'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('1991-08-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "Versorgungsausgleich ? Telefon: 881 05 94"
    },
	
	{
        "personalnummer": 976031,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Ellen Behrens",
        "adresse": "Albert-Schweitzer-Weg 9, 27777 Ganderkesee",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1941-06-26'),
        "geheiratetAm": new Date('1965-10-21'),
        "gesellschaft": "81A",
        "versorgungsordnung": 71,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1967-01-01'),
        "unternehmensaustritt": new Date('1985-06-20'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('2022-03-04'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": ""
    },
	
	{
        "personalnummer": 500359,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Helga Benecke",
        "adresse": "Schulenburgring 1a, 21031 Hamburg",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1934-10-16'),
        "geheiratetAm": new Date('1953-08-01'),
        "gesellschaft": "81A",
        "versorgungsordnung": 73,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1960-03-01'),
        "unternehmensaustritt": new Date('1984-02-29'),
        "ruhegeldfaehigAb": new Date('1959-06-01'),
        "rentenbeginn": new Date('1988-03-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "Telefon: 738 43 74 3 Kinder, 1 Neuseeland"
    },
    {
        "personalnummer": 139717,
        "aktuelleStatusgruppe": "Altersrentner",
        "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
        "name": "Hans-Peter Berger",
        "adresse": "An der Rehwiese 51, 21614 Buxtehude",
        "geschlecht": "männlich",
        "familienstand": "gesch.",
        "geburtsdatum": new Date('1940-07-21'),
        "geheiratetAm": null,
        "gesellschaft": "81A",
        "versorgungsordnung": 77,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1968-11-16'),
        "unternehmensaustritt": new Date('1992-04-30'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('2005-08-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "Versorgungsausgleich"
    },
    {
        "personalnummer": 404165,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Elisabeth Beyn",
        "adresse": "Am Feenteich 1, 22085 Hamburg",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1925-12-30'),
        "geheiratetAm": new Date('1959-03-26'),
        "gesellschaft": "81G",
        "versorgungsordnung": 72,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1969-06-01'),
        "unternehmensaustritt": new Date('1977-06-30'),
        "ruhegeldfaehigAb": new Date('1954-03-01'),
        "rentenbeginn": new Date('1977-07-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": ""
    },
    {
        "personalnummer": 310235,
        "aktuelleStatusgruppe": "Altersrentner",
        "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
        "name": "Dr. Klaus-Jürgen Biertz",
        "adresse": "Ohkamp 36, 22399 Hamburg",
        "geschlecht": "männlich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1932-06-23'),
        "geheiratetAm": null,
        "gesellschaft": "81A",
        "versorgungsordnung": 71,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1969-07-01'),
        "unternehmensaustritt": new Date('1986-06-30'),
        "ruhegeldfaehigAb": new Date('1959-08-01'),
        "rentenbeginn": new Date('1990-07-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "5382828"
    },
	
	{
        "personalnummer": 403438,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Elvira Blasy",
        "adresse": "c/o Gerokheim, Mömpelgardstraße 8/1, 71640 Ludwigsburg",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1939-11-29'),
        "geheiratetAm": new Date('1994-06-17'),
        "gesellschaft": "81A",
        "versorgungsordnung": 77,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1970-04-01'),
        "unternehmensaustritt": new Date('1980-06-27'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('1995-06-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "2. Ehe mit 1. Frau"
    },
    {
        "personalnummer": 131722,
        "aktuelleStatusgruppe": "Altersrentner",
        "alteStatusgruppe": "---",
        "name": "Helga Bleisz",
        "adresse": "Straßweg 2, 22607 Hamburg",
        "geschlecht": "weiblich",
        "familienstand": "ledig",
        "geburtsdatum": new Date('1929-09-05'),
        "geheiratetAm": null,
        "gesellschaft": "81A",
        "versorgungsordnung": 71,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1966-04-15'),
        "unternehmensaustritt": new Date('1989-09-30'),
        "ruhegeldfaehigAb": new Date('1966-04-01'),
        "rentenbeginn": new Date('1989-10-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": ""
    },
    {
        "personalnummer": 500347,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Beate Boche",
        "adresse": "Asmusweg 8, 22043 Hamburg",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1949-06-25'),
        "geheiratetAm": new Date('1972-08-05'),
        "gesellschaft": "81A",
        "versorgungsordnung": 77,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1967-09-01'),
        "unternehmensaustritt": new Date('1982-12-31'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('2003-09-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "Telefon: 652 92 79"
    },
    {
        "personalnummer": 500183,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Brigitte Bohlen",
        "adresse": "c/o Herrn J. Schmidt (Betreuungsverein), Papenstraße 27, 22089 Hamburg",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1932-02-10'),
        "geheiratetAm": new Date('1966-11-11'),
        "gesellschaft": "81A",
        "versorgungsordnung": 76,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1971-04-01'),
        "unternehmensaustritt": new Date('1984-12-31'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('1987-02-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": ""
    },
    {
        "personalnummer": 976014,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Bärbel Böhmer",
        "adresse": "Heimatring 44, 60596 Frankfurt",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1935-04-05'),
        "geheiratetAm": new Date('1960-09-16'),
        "gesellschaft": "81A",
        "versorgungsordnung": 76,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1975-08-01'),
        "unternehmensaustritt": new Date('1986-12-31'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('1992-02-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "Telefon: 069 634 725"
    },
    {
        "personalnummer": 104703,
        "aktuelleStatusgruppe": "Altersrentner",
        "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
        "name": "Rolf Bongardt",
        "adresse": "Holzdamm 2B, 50374 Erftstadt",
        "geschlecht": "männlich",
        "familienstand": "verh.",
        "geburtsdatum": new Date('1941-10-28'),
        "geheiratetAm": null,
        "gesellschaft": "81A",
        "versorgungsordnung": 76,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1971-01-15'),
        "unternehmensaustritt": new Date('1990-09-30'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('2006-11-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": ""
    },
    {
        "personalnummer": 500225,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Brigitte Brandt",
        "adresse": "Ilmenauer Weg 2, 37075 Göttingen",
        "geschlecht": "weiblich",
        "familienstand": "verh.",
        "geburtsdatum": new Date('1931-04-22'),
        "geheiratetAm": new Date('1974-11-15'),
        "gesellschaft": "81A",
        "versorgungsordnung": 77,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1969-03-01'),
        "unternehmensaustritt": new Date('1984-08-31'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('1987-10-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": ""
    },
    {
        "personalnummer": 500567,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Edith Braun",
        "adresse": "Bayerwaldstr. 20, 81737 München",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1930-09-08'),
        "geheiratetAm": new Date('1953-08-07'),
        "gesellschaft": "51",
        "versorgungsordnung": 77,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1968-01-01'),
        "unternehmensaustritt": new Date('1983-09-30'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('1984-07-21'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "Telefon: 0151 251 15 975"
    },
    
   
{
  "personalnummer": 500255,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Burmester",
  "adresse": "Dalldorf 1, 29562 Suhlendorf",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1938-09-27'),
  "geheiratetAm": new Date('1961-01-07'),
  "gesellschaft": "81A",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1974-01-01'),
  "unternehmensaustritt": new Date('1984-01-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1999-08-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 403931,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Conrad",
  "adresse": "Taunusstraße 89, 65835 Liederbach",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1929-09-02'),
  "geheiratetAm": new Date('1977-03-18'),
  "gesellschaft": "81A",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1969-07-01'),
  "unternehmensaustritt": new Date('1984-03-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1984-04-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "06196-26198"
},
{
  "personalnummer": 404932,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Damske",
  "adresse": "Ostermeyerstraße 25, 22607 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1935-09-27'),
  "geheiratetAm": new Date('1972-07-12'),
  "gesellschaft": "81A",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1961-10-01'),
  "unternehmensaustritt": new Date('1984-12-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1986-11-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "040/819 917 43"
},
{
  "personalnummer": 313650,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Del Re",
  "adresse": "c/o Rosenhof, App. 544, Lübecker Straße 3-11, 22926 Ahrensburg",
  "geschlecht": "weiblich",
  "familienstand": "gesch.",
  "geburtsdatum": new Date('1935-03-30'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1980-04-01'),
  "unternehmensaustritt": new Date('1990-12-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1995-04-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 310854,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Denker",
  "adresse": "Parkstieg 6, 22143 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date('1939-03-17'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1971-01-01'),
  "unternehmensaustritt": new Date('1991-12-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('2004-04-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Tel. 6471093 01724517244"
},

{
  "personalnummer": 500535,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Dohle",
  "adresse": "Veilchenweg 21, 40670 Meerbusch",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1948-09-26'),
  "geheiratetAm": new Date('1971-05-28'),
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1973-10-01'),
  "unternehmensaustritt": new Date('1984-12-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('2009-08-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 104885,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Dohmen",
  "adresse": "Kollwitzstraße 20, 52134 Herzogenrath",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date('1940-09-07'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1974-01-15'),
  "unternehmensaustritt": new Date('1984-06-30'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('2005-10-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 500437,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Dragt",
  "adresse": "Breul 16, 48143 Münster",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1941-08-31'),
  "geheiratetAm": new Date('1973-11-16'),
  "gesellschaft": "81A",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1970-01-01'),
  "unternehmensaustritt": new Date('1983-09-30'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1993-01-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 310961,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Drewski",
  "adresse": "Archenholzstraße 28, 22117 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1940-04-16'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1970-03-01'),
  "unternehmensaustritt": new Date('1995-06-30'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('2000-05-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 732 17 75"
},
{
  "personalnummer": 314864,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Ehlers",
  "adresse": "Residenz am Wiesenkamp, Wiesenkamp 16, 22359 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1935-12-09'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1973-10-01'),
  "unternehmensaustritt": new Date('1984-04-14'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1984-04-15'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 136200,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Ehrke-Mösing",
  "adresse": "Salinenstraße 33, 23843 Bad Oldesloe",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date('1938-12-11'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1972-04-01'),
  "unternehmensaustritt": new Date('1993-12-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1999-01-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Eheschließung nach VA, Telefon: 04531 808 69 33"
},
{
  "personalnummer": 116129,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Engelbrecht",
  "adresse": "Luitpoldstraße 25, 83435 Bad Reichenhall",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date('1938-08-24'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1972-11-01'),
  "unternehmensaustritt": new Date('1984-08-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('2003-09-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 403448,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Engels",
  "adresse": "Abteiweg 61, 41468 Neuss",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1930-08-11'),
  "geheiratetAm": new Date('1955-08-16'),
  "gesellschaft": "81A",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1959-07-01'),
  "unternehmensaustritt": new Date('1985-06-30'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1989-05-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 311142,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "---",
  "name": "Fellenz",
  "adresse": "Lokstedter Steindamm 16a, 22529 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date('1931-10-24'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1969-04-01'),
  "unternehmensaustritt": new Date('1989-03-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1991-11-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 560 21 23"
},
{
  "personalnummer": 500385,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Fischer",
  "adresse": "Lilienthalstraße 8, 38518 Gifhorn",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1939-06-19'),
  "geheiratetAm": new Date('1964-12-04'),
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1970-12-09'),
  "unternehmensaustritt": new Date('1983-06-30'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1990-05-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 125104,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Foulon",
  "adresse": "Heinrichstraße 33, 64283 Darmstadt",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date('1940-04-16'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1961-04-10'),
  "unternehmensaustritt": new Date('1976-03-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('2000-05-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 136192,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "---",
  "name": "Fraßdorf",
  "adresse": "Hagenauer Straße 16, 81479 München",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date('1930-03-29'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1975-01-01'),
  "unternehmensaustritt": new Date('1978-09-30'),
  "ruhegeldfaehigAb": new Date('1967-10-01'),
  "rentenbeginn": new Date('1993-01-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "2. Ehe ???!!!!!!"
},
{
  "personalnummer": 500261,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Freitag",
  "adresse": "Waldstraße 4, 23683 Scharbeutz",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1926-04-22'),
  "geheiratetAm": new Date('1954-07-17'),
  "gesellschaft": "81A",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1968-04-01'),
  "unternehmensaustritt": new Date('1983-06-30'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1987-11-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 500443,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Friedberg",
  "adresse": "Hanfstaenglstr. 1, 80638 München",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1928-03-22'),
  "geheiratetAm": new Date('1955-06-04'),
  "gesellschaft": "81A",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1968-02-01'),
  "unternehmensaustritt": new Date('1979-06-30'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1991-03-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 089 8114999"
},
{
  "personalnummer": 132530,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Garbe",
  "adresse": "Waldwinkel 2, 21220 Seevetal",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date('1945-07-04'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 78,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1966-05-01'),
  "unternehmensaustritt": new Date('1982-08-01'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('2008-08-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}







































          ];

// Axios POST request function
// Axios POST request function
async function insertData() {
  for (let i = 0; i < dataToInsert.length; i++) {
    const person = dataToInsert[i];

    try {
      const response = await axios.post(
        "http://localhost:4000/api/person",
        person
      );

      console.log(`✔️ Inserted personalnummer ${person.personalnummer}`);
    } catch (error) {
      // Wenn der Server geantwortet hat (HTTP-Fehlercode)
      if (error.response) {
        // 400 = existiert schon (so wie du es in deiner Route gebaut hast)
        if (error.response.status === 400) {
          console.warn(
            `⚠️ personalnummer ${person.personalnummer} exists – skipped`
          );
          continue; // optional, macht nur explizit "weiter" zur nächsten Person
        }

        // Andere HTTP-Fehler
        console.error(
          `❌ HTTP ${error.response.status} for personalnummer ${person.personalnummer}:`,
          error.response.data
        );
      } else {
        // Kein Response = z.B. Netzwerkfehler / Server nicht erreichbar
        console.error(
          `❌ Network/Unknown error for personalnummer ${person.personalnummer}:`,
          error.message
        );
      }
    }
  }

  console.log("✅ Import finished.");
}


// Call the function to insert data
insertData();