const axios = require('axios');

const dataToInsert = [
    
    {
  "personalnummer": 324178,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Werner Schomann",
  "adresse": "Friedrich-Ebert-Damm 89B, 22047 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1939-08-04"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 74,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1960-08-22"),
  "unternehmensaustritt": new Date("2000-08-31"),
  "ruhegeldfaehigAb": new Date("1960-08-01"),
  "rentenbeginn": new Date("2001-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich, 2. Ehe"
},

{
  "personalnummer": 321505,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Vorruheständler",
  "name": "Hans-Joachim Schrader",
  "adresse": "Buckhornstieg 18, 22359 Hamburg 67",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1939-12-07"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 74,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1957-04-01"),
  "unternehmensaustritt": new Date("1999-06-30"),
  "ruhegeldfaehigAb": new Date("1959-12-01"),
  "rentenbeginn": new Date("2000-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 323204,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Eveline Siegler",
  "adresse": "Moorredder 5a, 23570 Lübeck-Travemünde",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1943-07-17"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("2000-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2003-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 322198,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Vorruheständler",
  "name": "Hans Sobczak",
  "adresse": "Trelder Dorfstr. 24, 21244 Buchholz-Trelde",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1934-09-06"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 75,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1968-10-01"),
  "unternehmensaustritt": new Date("1995-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 04186 7870"
},

{
  "personalnummer": 500495,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Hannelore Steinmetz",
  "adresse": "Im Winkel 31, 37077 Göttingen",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1947-05-19"),
  "geheiratetAm": new Date("1974-06-07"),
  "gesellschaft": "90",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-04-01"),
  "unternehmensaustritt": new Date("1995-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1999-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 055124770"
},

{
  "personalnummer": 337006,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Veronika Stieldorf",
  "adresse": "Kiesselbachweg 29, 22399 Hamburg 63",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1948-03-04"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1964-08-24"),
  "unternehmensaustritt": new Date("1995-12-31"),
  "ruhegeldfaehigAb": new Date("1968-03-01"),
  "rentenbeginn": new Date("2012-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 040/6027850"
},

{
  "personalnummer": 310730,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Hans-Joachim Wohlenberg",
  "adresse": "Ahrenloher Straße 30, 25436 Tornesch",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1934-08-18"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 77,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1969-01-01"),
  "unternehmensaustritt": new Date("1993-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1995-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 403554,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Gisela Büllesbach",
  "adresse": "Am Schulzentrum 9, 26605 Aurich",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1940-01-15"),
  "geheiratetAm": null,
  "gesellschaft": "M1",
  "versorgungsordnung": 74,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1960-07-01"),
  "unternehmensaustritt": new Date("1983-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1984-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 176743,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Ursula Chereck",
  "adresse": "Pestalozzistr. 2, 30880 Laatzen",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1934-07-18"),
  "geheiratetAm": null,
  "gesellschaft": "M1",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-04-01"),
  "unternehmensaustritt": new Date("1989-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-09-30"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 177675,
  "aktuelleStatusgruppe": "Verstorbene",
  "alteStatusgruppe": "Altersrentner",
  "name": "Ernst Fauth",
  "adresse": "Turmalinstraße 2, 30823 Garbsen",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1932-02-13"),
  "geheiratetAm": null,
  "gesellschaft": "M1",
  "versorgungsordnung": 78,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1962-09-01"),
  "unternehmensaustritt": new Date("1983-05-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1995-03-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2025-09-27"),
  "bemerkung": null
},

{
  "personalnummer": 340190,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Gerhard Fritz",
  "adresse": "Saturnring 23, 30823 Garbsen",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1932-04-09"),
  "geheiratetAm": null,
  "gesellschaft": "M1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-06-01"),
  "unternehmensaustritt": new Date("1989-09-30"),
  "ruhegeldfaehigAb": new Date("1971-06-01"),
  "rentenbeginn": new Date("1992-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "05522 500 31 99 988"
},

{
  "personalnummer": 174458,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Wolfgang Galler",
  "adresse": "Brillantweg 6, 30823 Garbsen",
  "geschlecht": "männlich",
  "familienstand": null,
  "geburtsdatum": new Date("1939-12-25"),
  "geheiratetAm": null,
  "gesellschaft": "M1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-07-01"),
  "unternehmensaustritt": new Date("1988-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2005-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500207,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Lina Harms",
  "adresse": "Weserstraße 14, 26548 Norderney",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1938-03-15"),
  "geheiratetAm": new Date("1958-05-17"),
  "gesellschaft": "M1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-06-01"),
  "unternehmensaustritt": new Date("1988-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 339515,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Jürgen Hoppe",
  "adresse": "Albert-Bischofstraße 7, 28357 Bremen",
  "geschlecht": "männlich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1939-05-30"),
  "geheiratetAm": null,
  "gesellschaft": "M1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1978-03-06"),
  "unternehmensaustritt": new Date("1988-12-31"),
  "ruhegeldfaehigAb": new Date("1978-03-01"),
  "rentenbeginn": new Date("1995-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0421-833139"
},

{
  "personalnummer": 178079,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Ursula Kadner",
  "adresse": "An der Breche 13, 87647 Unterthingau",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1937-01-07"),
  "geheiratetAm": null,
  "gesellschaft": "M1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-07-01"),
  "unternehmensaustritt": new Date("1987-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1997-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 083778222"
},

{
  "personalnummer": 185694,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Frido Kammeyer",
  "adresse": "Ilmenausstraße 2, 38120 Braunschweig",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1929-11-19"),
  "geheiratetAm": null,
  "gesellschaft": "M1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1977-10-01"),
  "unternehmensaustritt": new Date("1990-02-28"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 337816,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Mechthild Koch",
  "adresse": "Falkenstraße 5b, 22385 Barsbüttel",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1944-04-08"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-04-01"),
  "unternehmensaustritt": new Date("1982-02-28"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 173468,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Teilübertragung auf Direktversicherung",
  "name": "Dieter Kukler",
  "adresse": "Rudorffstraße 13, 30459 Hannover",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1938-06-16"),
  "geheiratetAm": null,
  "gesellschaft": "M1",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1959-04-01"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1998-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "0511231103"
},

{
  "personalnummer": 340463,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Alwin Lüdecke",
  "adresse": "c/o Ernst und Cläre Jung Stiftung, Celler Straße 2, Whg. 3, 21509 Stade Riensförde",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1927-03-21"),
  "geheiratetAm": null,
  "gesellschaft": "M1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1975-09-01"),
  "unternehmensaustritt": new Date("1988-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 500555,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Evelin Lütjemüller",
  "adresse": "Ludwig-Ganghofer-Str. 8, 86899 Landsberg am Lech",
  "geschlecht": "weiblich",
  "familienstand": null,
  "geburtsdatum": new Date("1949-01-11"),
  "geheiratetAm": new Date("1970-08-21"),
  "gesellschaft": "M1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-04-15"),
  "unternehmensaustritt": new Date("1987-02-28"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2006-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 500438,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Klaus Meurer",
  "adresse": "Krasseltweg 11c, 30657 Hannover",
  "geschlecht": "männlich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1938-07-22"),
  "geheiratetAm": new Date("1967-09-14"),
  "gesellschaft": "M1",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1958-09-22"),
  "unternehmensaustritt": new Date("1975-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0511/601203"
},

{
  "personalnummer": 177873,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Ursula Paul",
  "adresse": "Schloßplatz 2-3, 31812 Bad Pyrmont",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1930-02-15"),
  "geheiratetAm": null,
  "gesellschaft": "M1",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1950-06-20"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 404906,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ingeburg Pläging",
  "adresse": "Südring 47, 37079 Göttingen",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1928-06-30"),
  "geheiratetAm": new Date("1952-03-29"),
  "gesellschaft": "M1",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-10-01"),
  "unternehmensaustritt": new Date("1989-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "05516 345 553 Schwiegertochter, 0551 70891293 selbst"
},

{
  "personalnummer": 403542,
  "aktuelleStatusgruppe": "Versorgungsausgleich",
  "alteStatusgruppe": null,
  "name": "Ina Propp",
  "adresse": "Ehlvershof 23, 30419 Hannover",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1946-09-06"),
  "geheiratetAm": new Date("1997-01-09"),
  "gesellschaft": "M1",
  "versorgungsordnung": 86,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-10-01"),
  "unternehmensaustritt": new Date("1985-08-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1985-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich, verlängerter schuldrechtlicher lt. Urte"
},

{
  "personalnummer": 191585,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Marlies Strübe",
  "adresse": "Ricklinger Stadtweg 3, 30823 Garbsen",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1935-12-06"),
  "geheiratetAm": null,
  "gesellschaft": "M1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1974-01-01"),
  "unternehmensaustritt": new Date("1985-06-20"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1985-06-21"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 186171,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Anneliese Trauthwein",
  "adresse": "Gerätehausweg 2, 31303 Burgdorf",
  "geschlecht": "weiblich",
  "familienstand": null,
  "geburtsdatum": new Date("1951-08-26"),
  "geheiratetAm": null,
  "gesellschaft": "M1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1978-04-01"),
  "unternehmensaustritt": new Date("1990-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2017-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0513-688 3020, 0170 2951583"
},

{
  "personalnummer": 500540,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Maria Ulbig",
  "adresse": "c/o Herrn Matthias Ulbig, Kampstraße 72E, 30629 Hannover",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1932-12-29"),
  "geheiratetAm": null,
  "gesellschaft": "M1",
  "versorgungsordnung": 74,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1965-12-01"),
  "unternehmensaustritt": new Date("1989-03-31"),
  "ruhegeldfaehigAb": new Date("1958-12-01"),
  "rentenbeginn": new Date("1990-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500165,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ilse Freifrau von Münchhausen",
  "adresse": "Hohenzollernstraße 12, 30161 Hannover",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1933-03-09"),
  "geheiratetAm": new Date("1960-06-15"),
  "gesellschaft": "M1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-07-01"),
  "unternehmensaustritt": new Date("1987-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "?"
},

{
  "personalnummer": 343541,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Gisela Adam",
  "adresse": "c/o Barbara Hartmann, Friesenstraße 53, 30926 Seelze",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1936-03-19"),
  "geheiratetAm": null,
  "gesellschaft": "N2",
  "versorgungsordnung": 81,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1962-01-01"),
  "unternehmensaustritt": new Date("1970-08-14"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1970-08-15"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "db.hartmann@t-online.de"
},

{
  "personalnummer": 500426,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Inge Bartels",
  "adresse": "c/o Residenz am Wiesenkamp, Wiesenkamp 16 App. 2009, 22359 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1930-09-26"),
  "geheiratetAm": new Date("1955-02-19"),
  "gesellschaft": "N1",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1954-07-12"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Tel. 644 162 09"
},

{
  "personalnummer": 976010,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ingrid Bauer",
  "adresse": "c/o Dirk Bauer, Löhndorfer Str. 35, 42699 Solingen",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1940-01-04"),
  "geheiratetAm": new Date("1958-12-18"),
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1979-05-01"),
  "unternehmensaustritt": new Date("1990-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1992-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "?"
},

{
  "personalnummer": 405174,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Margot Bevers",
  "adresse": "Am Steinberg 53, 25436 Uetersen",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1938-06-26"),
  "geheiratetAm": new Date("1959-09-05"),
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-11-15"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": new Date("1970-11-01"),
  "rentenbeginn": new Date("1994-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500428,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Susanne Bitter",
  "adresse": "Reuterstraße 213, 51467 Bergisch Gladbach",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1938-07-02"),
  "geheiratetAm": new Date("1972-09-28"),
  "gesellschaft": "N1",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1954-01-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 151639,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Norbert Bollweg",
  "adresse": "Kampstraße 16, 25355 Barmstedt",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1949-07-24"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1974-05-01"),
  "unternehmensaustritt": new Date("1989-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2012-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500480,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Werner Bott",
  "adresse": "Am Leinewehr 39, 30519 Hannover",
  "geschlecht": "männlich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1929-08-07"),
  "geheiratetAm": new Date("1964-10-30"),
  "gesellschaft": "M1",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1964-05-01"),
  "unternehmensaustritt": new Date("1980-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1984-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500531,
  "aktuelleStatusgruppe": "Versorgungsausgleich",
  "alteStatusgruppe": null,
  "name": "Hans-Jürgen Braun",
  "adresse": "Am Markt 25, 18337 Marlow",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1949-03-22"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 86,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2018-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "2. Ehe"
},

{
  "personalnummer": 126029,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Gisa Bruns",
  "adresse": "Rahlstedter Str. 120, 22143 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1943-10-23"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-07-17"),
  "unternehmensaustritt": new Date("1983-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2006-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 677 29 58"
},

{
  "personalnummer": 337956,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Hans-Jürgen Burmeister",
  "adresse": "Wildermuthring 100, 22415 Hamburg 62",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1939-08-01"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1977-11-01"),
  "unternehmensaustritt": new Date("1993-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1999-08-01"),
  "zusagedatum": null,
  "verstorbenAm": new Date("2025-06-21"),
  "bemerkung": null
},

{
  "personalnummer": 500551,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Gudrun Cygan",
  "adresse": "Bredenhoop 8, 25767 Albersdorf",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1942-04-23"),
  "geheiratetAm": new Date("1963-08-09"),
  "gesellschaft": "N1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1964-04-01"),
  "unternehmensaustritt": new Date("1990-02-28"),
  "ruhegeldfaehigAb": new Date("1957-04-01"),
  "rentenbeginn": new Date("1995-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 337117,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Ingrid Dittmann",
  "adresse": "Mundsburger Damm 26 A, 22087 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1930-11-25"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1967-01-01"),
  "unternehmensaustritt": new Date("1983-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 220 7638"
},

{
  "personalnummer": 500549,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Elke Faber",
  "adresse": "Reepschlägerstraße 36, 22880 Wedel",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1941-08-23"),
  "geheiratetAm": new Date("1962-08-30"),
  "gesellschaft": "N1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1961-11-01"),
  "unternehmensaustritt": new Date("1981-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1997-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 04103-14622"
},

{
  "personalnummer": 340802,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Wolfgang Fitzner",
  "adresse": "Drostenkamp 20, 32760 Detmold",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1926-12-14"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-08-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1987-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 976057,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Karin Fröhlich",
  "adresse": "Lindenstr. 7, 25421 Pinneberg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1937-08-07"),
  "geheiratetAm": new Date("1957-08-13"),
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1975-12-08"),
  "unternehmensaustritt": new Date("1989-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1994-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 337212,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Maria Granofsky",
  "adresse": "Müssenkamp 2a, 22149 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1934-05-13"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1968-12-05"),
  "unternehmensaustritt": new Date("1990-12-31"),
  "ruhegeldfaehigAb": new Date("1968-12-01"),
  "rentenbeginn": new Date("1994-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 672 62 78"
},

{
  "personalnummer": 976030,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Brunhilde Grause",
  "adresse": "c/o RA Daniel Jacobsmeyer, Nienberger Kirchplatz 8, 48161 Münster-Nienberge",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1939-10-31"),
  "geheiratetAm": new Date("1964-08-25"),
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-04-01"),
  "unternehmensaustritt": new Date("1983-02-07"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2022-01-08"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 345520,
  "aktuelleStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "alteStatusgruppe": null,
  "name": "Sabine Groeneveld",
  "adresse": "Schmachthäger Straße 37, 22309 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1958-03-28"),
  "geheiratetAm": new Date("1994-05-02"),
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1980-04-01"),
  "unternehmensaustritt": new Date("1990-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 403115,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ursula Haedge",
  "adresse": "Lühmnnstr. 11, 24558 Henstedt-Ulzburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1928-12-30"),
  "geheiratetAm": new Date("1962-07-16"),
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1976-04-01"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1995-12-11"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500421,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Heike Haslbeck",
  "adresse": "Jahnkeweg 15, 22179 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1944-09-21"),
  "geheiratetAm": new Date("1964-03-20"),
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-05-16"),
  "unternehmensaustritt": new Date("1987-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 6410718"
},

{
  "personalnummer": 337097,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Jutta Jansen",
  "adresse": "Sandfoort 104d, 22415 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1943-12-11"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1967-11-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2009-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 532 22 63"
},

{
  "personalnummer": 500376,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Christa Jürgensen",
  "adresse": "Wippen 10, 24107 Kiel",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1929-12-25"),
  "geheiratetAm": new Date("1956-03-22"),
  "gesellschaft": "N1",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1960-08-04"),
  "unternehmensaustritt": new Date("1988-03-31"),
  "ruhegeldfaehigAb": new Date("1960-09-01"),
  "rentenbeginn": new Date("1992-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500227,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Helga Knittel",
  "adresse": "Neckarkanalstraße 102, 71686 Remseck - Aldingen",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1941-05-18"),
  "geheiratetAm": new Date("1971-12-10"),
  "gesellschaft": "61",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-04-01"),
  "unternehmensaustritt": new Date("1985-03-31"),
  "ruhegeldfaehigAb": new Date("1962-04-01"),
  "rentenbeginn": new Date("1991-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 337451,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Manfred König",
  "adresse": "Schwentine­str. 23, 22851 Norderstedt",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1935-08-14"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": "10",
  "unternehmenseintritt": new Date("1972-06-13"),
  "unternehmensaustritt": new Date("1990-12-31"),
  "ruhegeldfaehigAb": new Date("1972-06-01"),
  "rentenbeginn": new Date("1995-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 149369,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Elisabeth Kray-Graef",
  "adresse": "Ekho­fstraße 41, 22087 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1941-01-02"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-10-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1995-01-04"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 323022,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Teilübertragung auf Direktversicherung",
  "name": "Thorsten Krellenberg",
  "adresse": "Timm-Kröger-Weg 13, 23843 Bad Oldesloe",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1944-06-22"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-08-01"),
  "unternehmensaustritt": new Date("1990-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2009-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 340810,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Gerhard Krök",
  "adresse": "Am Stadion 5, 33689 Bielefeld",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1932-11-21"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1974-04-01"),
  "unternehmensaustritt": new Date("1989-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1992-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 976060,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ursula Lahmann",
  "adresse": "Akazienstraße 16, 31515 Wunstorf",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1937-01-26"),
  "geheiratetAm": new Date("1960-06-03"),
  "gesellschaft": "N1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1960-06-01"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": new Date("1958-08-01"),
  "rentenbeginn": new Date("1994-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 976022,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Helmut Lotze",
  "adresse": "Borsigweg 3, 30165 Hannover",
  "geschlecht": "männlich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1938-05-13"),
  "geheiratetAm": new Date("1963-08-09"),
  "gesellschaft": "N1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-11-14"),
  "unternehmensaustritt": new Date("1986-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1999-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 150961,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Karl Lüttgerding",
  "adresse": "Albert-Schweitzer-Str. 62, 23611 Bad Schwartau",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1936-12-05"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-04-01"),
  "unternehmensaustritt": new Date("1989-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1997-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500450,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ingeborg Marg",
  "adresse": "Silcherstraße 34, 22761 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1941-01-18"),
  "geheiratetAm": new Date("1969-06-30"),
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-07-01"),
  "unternehmensaustritt": new Date("1990-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2006-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 899 32 34"
},

{
  "personalnummer": 132829,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Siegfried Marszan",
  "adresse": "Hamburger Straße 41, 25581 Henstedt/Ulzburg 1",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1936-07-25"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-10-01"),
  "unternehmensaustritt": new Date("1985-08-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500235,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Elsbeth Meszkat",
  "adresse": "Lindenstr. 9, 22941 Bargteheide",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1942-01-05"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1966-09-01"),
  "unternehmensaustritt": new Date("1991-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 148551,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Karin Michaelis",
  "adresse": "Högenkamp 18, 22399 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1939-10-03"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1972-02-01"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-05-08"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500395,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Monika Möller",
  "adresse": "Bergstr. 12, 21483 Gülzow",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1942-06-17"),
  "geheiratetAm": new Date("1962-06-08"),
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-10-01"),
  "unternehmensaustritt": new Date("1991-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Tel. Sohn: 0173 63 00 616, Fr. Möller 04158182492"
},

{
  "personalnummer": 337345,
  "aktuelleStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Holger Pampel",
  "adresse": "Rodenbekstieg 4, 22395 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1953-01-18"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-04-01"),
  "unternehmensaustritt": new Date("1988-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1992-12-11"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 604 03 79"
},

{
  "personalnummer": 339713,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Karin Pawelzik",
  "adresse": "Inselweg 10b, 23714 Malente-Timmdorf",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1937-09-21"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-07-01"),
  "unternehmensaustritt": new Date("1990-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1997-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500217,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ingrid Plattfaut",
  "adresse": "Papenloh 6, 59069 Hamm/Rhynern",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date("1942-08-11"),
  "geheiratetAm": new Date("1965-11-26"),
  "gesellschaft": "N1",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1965-07-01"),
  "unternehmensaustritt": new Date("1992-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 02385 9359373"
},

{
  "personalnummer": 151472,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Manfred Praast",
  "adresse": "Bahnhofstr. 37a, 29574 Ebstorf",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date("1947-04-13"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-05-01"),
  "unternehmensaustritt": new Date("1987-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2011-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 345132,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Klaus Rautenberg",
  "adresse": "Lüneburger Straße 203, 21423 Winsen/Luhe",
  "geschlecht": "männlich",
  "familienstand": null,
  "geburtsdatum": new Date("1939-12-12"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1980-01-01"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1998-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich"
},

{
  "personalnummer": 336768,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Norbert Roisch",
  "adresse": "Kiefernweg 16, 21360 Voeegelsen",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1937-11-12"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1963-01-01"),
  "unternehmensaustritt": new Date("1993-09-30"),
  "ruhegeldfaehigAb": new Date("1957-01-01"),
  "rentenbeginn": new Date("1997-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500544,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Renate Rosenlöcher",
  "adresse": "Norra Storgatan 76A, S57334 Tranas, Schweden",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1941-06-23"),
  "geheiratetAm": new Date("1968-05-24"),
  "gesellschaft": "N1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-07-01"),
  "unternehmensaustritt": new Date("1992-01-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "004614014436"
},

{
  "personalnummer": 976043,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Lieselotte Rothgänger",
  "adresse": "Lilli-Friedemann-Ring 5, 30177 Hannover",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1931-01-12"),
  "geheiratetAm": new Date("1954-07-10"),
  "gesellschaft": "N1",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1959-05-21"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": new Date("1955-10-01"),
  "rentenbeginn": new Date("1988-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 337022,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Christa Rudolph",
  "adresse": "Aprikosenweg 40A, 22175 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1941-06-22"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1957-04-01"),
  "unternehmensaustritt": new Date("1992-06-30"),
  "ruhegeldfaehigAb": new Date("1961-06-22"),
  "rentenbeginn": new Date("2001-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 339879,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Klaus Schachtschneider",
  "adresse": "Lerchenweg 2b, 21339 Lüneburg",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1952-03-25"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1979-04-01"),
  "unternehmensaustritt": new Date("1989-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2016-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 04131 244627"
},

{
  "personalnummer": 500523,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Irmgard Schenck",
  "adresse": "Kreuzweg 22 a, 22869 Schenefeld",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1938-06-12"),
  "geheiratetAm": new Date("1958-01-01"),
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-10-01"),
  "unternehmensaustritt": new Date("1989-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 401772,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Heiner Schiemann",
  "adresse": "Pyritzer Stieg 14, 22147 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1940-10-30"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-04-01"),
  "unternehmensaustritt": new Date("1992-03-27"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1992-03-28"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 338186,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Helga Schnabel-De Haar",
  "adresse": "Broyhanstraße 17, 30419 Hannover",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1934-05-30"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1964-05-15"),
  "unternehmensaustritt": new Date("1986-03-31"),
  "ruhegeldfaehigAb": new Date("1958-05-15"),
  "rentenbeginn": new Date("1994-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0511 79 35 07"
},

{
  "personalnummer": 500489,
  "aktuelleStatusgruppe": "Versorgungsausgleich",
  "alteStatusgruppe": null,
  "name": "Liselotte Schönhütte",
  "adresse": "c/o Frau Dr. Kirstin Fischer, Rübezahlweg 6, 53797 Lohmar",
  "geschlecht": "weiblich",
  "familienstand": "geschieden",
  "geburtsdatum": new Date("1944-12-24"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("2015-12-01"),
  "unternehmensaustritt": null,
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2015-12-01"),
  "zusagedatum": new Date("2015-12-01"),
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 336727,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Peter Schönhütte",
  "adresse": "Julius-Wichmann-Weg 8, 23769 Fehmarn OT Burg",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1942-12-09"),
  "geheiratetAm": null,
  "gesellschaft": "N1",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-10-01"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2008-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "2. Ehe? Tel. 04371864866, 01717771153"
},

{
  "personalnummer": 500406,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ruth Siggelkow",
  "adresse": "Elbinger Kehre 9b, 22175 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1946-08-08"),
  "geheiratetAm": new Date("1975-01-22"),
  "gesellschaft": "N1",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-10-01"),
  "unternehmensaustritt": new Date("1989-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1994-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}






    



       ];
    
     // Axios POST request function
    // Axios POST request function
async function insertData() {
  for (let i = 0; i < dataToInsert.length; i++) {
    const person = dataToInsert[i];

    try {
      const response = await axios.post(
        "http://localhost:4000/api/person",
        person
      );

      console.log(`✔️ Inserted personalnummer ${person.personalnummer}`);
    } catch (error) {
      // Wenn der Server geantwortet hat (HTTP-Fehlercode)
      if (error.response) {
        // 400 = existiert schon (so wie du es in deiner Route gebaut hast)
        if (error.response.status === 400) {
          console.warn(
            `⚠️ personalnummer ${person.personalnummer} exists – skipped`
          );
          continue; // optional, macht nur explizit "weiter" zur nächsten Person
        }

        // Andere HTTP-Fehler
        console.error(
          `❌ HTTP ${error.response.status} for personalnummer ${person.personalnummer}:`,
          error.response.data
        );
      } else {
        // Kein Response = z.B. Netzwerkfehler / Server nicht erreichbar
        console.error(
          `❌ Network/Unknown error for personalnummer ${person.personalnummer}:`,
          error.message
        );
      }
    }
  }

  console.log("✅ Import finished.");
}

    
    // Call the function to insert data
    insertData();