const axios = require('axios');

const dataToInsert = [

    {
    "personalnummer": 403241,
    "aktuelleStatusgruppe": "Hinterbliebene",
    "alteStatusgruppe": null,
    "name": "Annegret Hoffmeyer",
    "adresse": "Gerhart-Hauptmann-Ring 388, 60439 Frankfurt/Main",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1929-09-12'),
    "geheiratetAm": new Date('1950-06-10'),
    "gesellschaft": "81A",
    "versorgungsordnung": 71,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1965-04-01'),
    "unternehmensaustritt": new Date('1985-06-30'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1989-12-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "Telefon: 069-57 56 47"
},
{
    "personalnummer": 108225,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Peter Janssen",
    "adresse": "Ulrichstraße 109, 60433 Frankfurt",
    "geschlecht": "männlich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1939-12-20'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 77,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1970-10-01'),
    "unternehmensaustritt": new Date('1981-01-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2000-01-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},
{
    "personalnummer": 404041,
    "aktuelleStatusgruppe": "Verstorbene",
    "alteStatusgruppe": "Hinterbliebene",
    "name": "Anneliese Kaden",
    "adresse": "c/o Gerald Kaden, Hermsdorfer Damm 106, 13467 Berlin",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1927-08-19'),
    "geheiratetAm": new Date('1953-02-14'),
    "gesellschaft": "81A",
    "versorgungsordnung": 71,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1965-05-01'),
    "unternehmensaustritt": new Date('1984-12-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1990-09-01'),
    "zusagedatum": null,
    "verstorbenAm": new Date('2025-04-11'),
    "bemerkung": "ab 11.20 auf Barzahlung"
},
{
    "personalnummer": 319681,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Joachim Kasten",
    "adresse": "Kirchenstraße 340, 22946 Trittau",
    "geschlecht": "männlich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1942-09-20'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 71,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1976-11-01'),
    "unternehmensaustritt": new Date('1983-12-31'),
    "ruhegeldfaehigAb": new Date('1966-09-01'),
    "rentenbeginn": new Date('2006-01-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "Versorgungsausgleich Telefon: 04107 908847"
},
{
    "personalnummer": 108951,
    "aktuelleStatusgruppe": "Verstorbene",
    "alteStatusgruppe": "Altersrentner",
    "name": "Ingrid Kerth",
    "adresse": "c/o Frau Dr. jur. E. Portz, Imlangelfeld 10a, 61350 Bad Homburg vor der Höhe",
    "geschlecht": "weiblich",
    "familienstand": "gesch.",
    "geburtsdatum": new Date('1942-05-08'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 75,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1972-10-01'),
    "unternehmensaustritt": new Date('1984-12-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1985-01-01'),
    "zusagedatum": null,
    "verstorbenAm": new Date('2023-12-19'),
    "bemerkung": ""
},
{
    "personalnummer": 105130,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Karl-Heinz Klärding",
    "adresse": "Karl-Marx-Allee 142, 52066 Aachen",
    "geschlecht": "männlich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1936-08-07'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1971-01-01'),
    "unternehmensaustritt": new Date('1985-03-19'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1996-09-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "0031455728210, L.T.M. Weg 22, NL 6412 BP Heerlen Niederlande"
},
{
    "personalnummer": 319368,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Anni Kohlmey",
    "adresse": "Georg-Kerschensteiner-Str. 17, 23554 Lübeck",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1940-08-10'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1973-10-01'),
    "unternehmensaustritt": new Date('1984-03-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2005-09-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},
{
    "personalnummer": 500498,
    "aktuelleStatusgruppe": "Hinterbliebene",
    "alteStatusgruppe": null,
    "name": "Käthe Krifft",
    "adresse": "Amselweg 2, 41849 Wassenberg",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1936-08-31'),
    "geheiratetAm": new Date('1961-04-14'),
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1971-01-01'),
    "unternehmensaustritt": new Date('1981-03-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1992-08-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},
{
"personalnummer": 102574,
"aktuelleStatusgruppe": "Altersrentner",
"alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
"name": "Ingrid Lampe",
"adresse": "Curtiusweg 20, 27749 Delmenhorst",
"geschlecht": "weiblich",
"familienstand": "verh.",
"geburtsdatum": new Date('1944-09-07'),
"geheiratetAm": null,
"gesellschaft": "81A",
"versorgungsordnung": 77,
"arbVerhRentTr": null,
"unternehmenseintritt": new Date('1970-01-01'),
"unternehmensaustritt": new Date('1982-10-19'),
"ruhegeldfaehigAb": null,
"rentenbeginn": new Date('2009-10-01'),
"zusagedatum": null,
"verstorbenAm": null,
"bemerkung": "Telefon: 0422162488"
},
{
"personalnummer": 319160,
"aktuelleStatusgruppe": "Altersrentner",
"alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
"name": "Dieter Lange",
"adresse": "Möhlenbarg 21, 22848 Norderstedt",
"geschlecht": "männlich",
"familienstand": "ledig",
"geburtsdatum": new Date('1941-04-19'),
"geheiratetAm": null,
"gesellschaft": "81A",
"versorgungsordnung": 77,
"arbVerhRentTr": null,
"unternehmenseintritt": new Date('1969-01-01'),
"unternehmensaustritt": new Date('1984-10-31'),
"ruhegeldfaehigAb": null,
"rentenbeginn": new Date('2006-05-01'),
"zusagedatum": null,
"verstorbenAm": null,
"bemerkung": ""
},
{
"personalnummer": 500496,
"aktuelleStatusgruppe": "Hinterbliebene",
"alteStatusgruppe": null,
"name": "Wiltrud Laufer",
"adresse": "Schlebuschweg 23a, 21029 Hamburg",
"geschlecht": "weiblich",
"familienstand": "verw.",
"geburtsdatum": new Date('1938-12-12'),
"geheiratetAm": null,
"gesellschaft": "81A",
"versorgungsordnung": 71,
"arbVerhRentTr": null,
"unternehmenseintritt": new Date('1966-01-01'),
"unternehmensaustritt": new Date('1984-12-31'),
"ruhegeldfaehigAb": null,
"rentenbeginn": new Date('1996-06-01'),
"zusagedatum": null,
"verstorbenAm": null,
"bemerkung": ""
},
{
"personalnummer": 500263,
"aktuelleStatusgruppe": "Hinterbliebene",
"alteStatusgruppe": null,
"name": "Dr. Margot Lehner-Siegmund",
"adresse": "Unsöldstraße 14, 80538 München",
"geschlecht": "weiblich",
"familienstand": "verw.",
"geburtsdatum": new Date('1942-05-27'),
"geheiratetAm": null,
"gesellschaft": "81A",
"versorgungsordnung": 78,
"arbVerhRentTr": null,
"unternehmenseintritt": new Date('1962-05-01'),
"unternehmensaustritt": new Date('1979-12-31'),
"ruhegeldfaehigAb": new Date('1959-09-01'),
"rentenbeginn": new Date('1987-04-01'),
"zusagedatum": null,
"verstorbenAm": null,
"bemerkung": ""
},
{
"personalnummer": 131573,
"aktuelleStatusgruppe": "Altersrentner",
"alteStatusgruppe": "Frühpensionäre",
"name": "Manfred-Hermann Mex",
"adresse": "Am Mühlenberg 28, 21271 Asendorf",
"geschlecht": "männlich",
"familienstand": "verh.",
"geburtsdatum": new Date('1939-05-20'),
"geheiratetAm": null,
"gesellschaft": "81A",
"versorgungsordnung": 77,
"arbVerhRentTr": null,
"unternehmenseintritt": new Date('1969-02-01'),
"unternehmensaustritt": new Date('1995-03-31'),
"ruhegeldfaehigAb": null,
"rentenbeginn": new Date('1999-06-01'),
"zusagedatum": null,
"verstorbenAm": null,
"bemerkung": ""
},
{
    "personalnummer": 500416,
    "aktuelleStatusgruppe": "Hinterbliebene",
    "alteStatusgruppe": null,
    "name": "Lotte Mey",
    "adresse": "Plathweg 9, 22307 Hamburg",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1931-08-06'),
    "geheiratetAm": new Date('1963-05-27'),
    "gesellschaft": "81A",
    "versorgungsordnung": 75,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1969-04-01'),
    "unternehmensaustritt": new Date('1989-12-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1994-04-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},
{
    "personalnummer": 311472,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Hajo Meyer",
    "adresse": "Muchallstraße 13, 26789 Leer/Ostfr.",
    "geschlecht": "männlich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1943-07-05'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1972-01-01'),
    "unternehmensaustritt": new Date('1985-04-30'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2003-08-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},
{
    "personalnummer": 322958,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Ursula Meyer",
    "adresse": "Up de Worth 39, 22391 Hamburg",
    "geschlecht": "weiblich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1947-12-06'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 77,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1969-10-01'),
    "unternehmensaustritt": new Date('1983-09-30'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2013-02-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},
{
    "personalnummer": 313130,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Gertrud Möllenkamp",
    "adresse": "Lange Hecke 37, 37130 Gleichen",
    "geschlecht": "weiblich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1952-08-12'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1978-07-01'),
    "unternehmensaustritt": new Date('1989-08-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2018-03-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},
{
    "personalnummer": 310979,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Frühpensionäre",
    "name": "Günter Möller",
    "adresse": "Großer Ring 41c, 25492 Heist",
    "geschlecht": "männlich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1933-09-06'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 75,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1968-10-01'),
    "unternehmensaustritt": new Date('1989-08-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1993-10-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},
{
    "personalnummer": 283002,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Thomas Mörder",
    "adresse": "Von-Andrianstraße 8, 83620 Feldkirchen-Westerham",
    "geschlecht": "männlich",
    "familienstand": "VA",
    "geburtsdatum": new Date('1942-04-26'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1973-04-01'),
    "unternehmensaustritt": new Date('1983-12-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2006-05-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},
{
    "personalnummer": 104752,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Heinz-Peter Moseler",
    "adresse": "Uhlenkoog 25, 24113 Kiel",
    "geschlecht": "männlich",
    "familienstand": "verh.",
    "geburtsdatum": new Date('1939-10-08'),
    "geheiratetAm": new Date('1971-09-09'),
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1973-01-09'),
    "unternehmensaustritt": new Date('1981-08-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2003-06-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "Telefon: 0431-6594515"
},
{
    "personalnummer": 500550,
    "aktuelleStatusgruppe": "Hinterbliebene",
    "alteStatusgruppe": null,
    "name": "Hannelore Naefken",
    "adresse": "Sonnenredder 70, 22045 Hamburg",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1943-08-25'),
    "geheiratetAm": new Date('1964-07-17'),
    "gesellschaft": "81A",
    "versorgungsordnung": 75,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1967-04-01'),
    "unternehmensaustritt": new Date('1990-09-30'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1990-10-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": "040715 81 96"
},
{
    "personalnummer": 500046,
    "aktuelleStatusgruppe": "Hinterbliebene",
    "alteStatusgruppe": null,
    "name": "Elke Nandy",
    "adresse": "c/o Max-Brauer-Haus, Hohnerredder 21a, 22175 Hamburg",
    "geschlecht": "weiblich",
    "familienstand": "verw.",
    "geburtsdatum": new Date('1940-01-01'),
    "geheiratetAm": new Date('1964-09-18'),
    "gesellschaft": "81A",
    "versorgungsordnung": 71,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1963-05-01'),
    "unternehmensaustritt": new Date('1984-01-31'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('1984-02-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
},
{
    "personalnummer": 136523,
    "aktuelleStatusgruppe": "Altersrentner",
    "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
    "name": "Hans-Dietrich Oerding",
    "adresse": "Am Berge 28, 21629 Neu Wulmsdorf",
    "geschlecht": "männlich",
    "familienstand": null,
    "geburtsdatum": new Date('1944-05-03'),
    "geheiratetAm": null,
    "gesellschaft": "81A",
    "versorgungsordnung": 76,
    "arbVerhRentTr": null,
    "unternehmenseintritt": new Date('1972-01-01'),
    "unternehmensaustritt": new Date('1982-02-28'),
    "ruhegeldfaehigAb": null,
    "rentenbeginn": new Date('2009-06-01'),
    "zusagedatum": null,
    "verstorbenAm": null,
    "bemerkung": ""
}











    ];

// Axios POST request function
// Axios POST request function
async function insertData() {
  for (let i = 0; i < dataToInsert.length; i++) {
    const person = dataToInsert[i];

    try {
      const response = await axios.post(
        "http://localhost:4000/api/person",
        person
      );

      console.log(`✔️ Inserted personalnummer ${person.personalnummer}`);
    } catch (error) {
      // Wenn der Server geantwortet hat (HTTP-Fehlercode)
      if (error.response) {
        // 400 = existiert schon (so wie du es in deiner Route gebaut hast)
        if (error.response.status === 400) {
          console.warn(
            `⚠️ personalnummer ${person.personalnummer} exists – skipped`
          );
          continue; // optional, macht nur explizit "weiter" zur nächsten Person
        }

        // Andere HTTP-Fehler
        console.error(
          `❌ HTTP ${error.response.status} for personalnummer ${person.personalnummer}:`,
          error.response.data
        );
      } else {
        // Kein Response = z.B. Netzwerkfehler / Server nicht erreichbar
        console.error(
          `❌ Network/Unknown error for personalnummer ${person.personalnummer}:`,
          error.message
        );
      }
    }
  }

  console.log("✅ Import finished.");
}


// Call the function to insert data
insertData();