const axios = require('axios');

const dataToInsert = [
    
    
    {
  "personalnummer": 500275,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ilse Gertrud Menger",
  "adresse": "c/o Frau Marion Köhler, Distelkamp 2, 27389 Fintel",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1935-08-20"),
  "geheiratetAm": new Date("1955-08-20"),
  "gesellschaft": "11",
  "versorgungsordnung": 74,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1962-04-01"),
  "unternehmensaustritt": new Date("1989-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon Tochter: 04265-95122, 0162-9406723"
},

{
  "personalnummer": 500101,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Waltraud Moczynski",
  "adresse": "Kroonhorst 128, 22549 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1937-09-06"),
  "geheiratetAm": new Date("1959-08-14"),
  "gesellschaft": "11",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-02-01"),
  "unternehmensaustritt": new Date("1985-11-14"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1985-11-15"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 83 51 81"
},

{
  "personalnummer": 500452,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Walther Norbach",
  "adresse": "Heinrich-Bomhoff-Weg 3, 22607 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1938-02-08"),
  "geheiratetAm": new Date("1965-05-13"),
  "gesellschaft": "11",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-10-01"),
  "unternehmensaustritt": new Date("1984-01-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1986-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 148528,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Hermann Nossing",
  "adresse": "Aalborgring 36, 24109 Kiel",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1936-09-23"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1966-07-01"),
  "unternehmensaustritt": new Date("1987-08-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Tochter: Insa Kiefer, Am Felde 6c, Ellerau, 04106-773295"
},

{
  "personalnummer": 152496,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
  "name": "Renate Olef",
  "adresse": "Wohnung Nr. 3, Reeperbahn 4, 21481 Lauenburg",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1940-01-27"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-05-01"),
  "unternehmensaustritt": new Date("1980-11-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1997-07-23"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "VA, Telefon: 04153 5711102"
},

{
  "personalnummer": 500482,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Susanne Ramünke",
  "adresse": "Bergstedter Chaussee 87, 22395 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1952-09-03"),
  "geheiratetAm": new Date("1971-09-17"),
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-11-01"),
  "unternehmensaustritt": new Date("1986-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2009-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500556,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Brita Regenbogen",
  "adresse": "Gerdauring 29 C, 21147 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1941-06-26"),
  "geheiratetAm": new Date("1966-09-09"),
  "gesellschaft": "11",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-02-01"),
  "unternehmensaustritt": new Date("1987-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1987-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 7964852"
},

{
  "personalnummer": 158352,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Edith Rönnpage",
  "adresse": "Erntingweg 10, 22179 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1935-07-11"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-07-01"),
  "unternehmensaustritt": new Date("1984-03-07"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1984-03-08"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 642 03 31"
},

{
  "personalnummer": 500538,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Edita Schlesener",
  "adresse": "c/o Frau Sabrina Schlesener, Boostedter Straße 98, 24539 Neumünster",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1934-07-16"),
  "geheiratetAm": new Date("1966-07-15"),
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1955-04-01"),
  "unternehmensaustritt": new Date("1985-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 149542,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Kurt Schlichting",
  "adresse": "Ostseestraße 21, 24107 Kiel",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1928-09-18"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1957-04-15"),
  "unternehmensaustritt": new Date("1985-08-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 159996,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Irma Schlüter",
  "adresse": "c/o Frau Monika Schlüter, Itzehoer Chaussee 1, 24808 Jevenstedt",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1935-04-27"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-08-01"),
  "unternehmensaustritt": new Date("1987-05-24"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1987-05-25"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 301531,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Günter Siegmann",
  "adresse": "Gütchen 8, 42719 Solingen",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1943-08-04"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1975-05-01"),
  "unternehmensaustritt": new Date("1985-05-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2008-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich"
},

{
  "personalnummer": 157859,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Krystalia Syri",
  "adresse": "Fillelinon 80, 38221 Volos Greece",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1938-04-24"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-10-18"),
  "unternehmensaustritt": new Date("1982-02-04"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1982-02-05"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 157602,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Gisela Treppner",
  "adresse": "Hardauring 14 C, 21147 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1929-03-31"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-08-01"),
  "unternehmensaustritt": new Date("1981-06-04"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1981-06-05"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 149146,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Annegret Tresselt",
  "adresse": "Damen 15, 25813 Husum",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1937-08-29"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-06-01"),
  "unternehmensaustritt": new Date("1986-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1997-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 04102-697535"
},

{
  "personalnummer": 500223,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Helma Wasner",
  "adresse": "Achtern Born 105, 22549 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1933-05-12"),
  "geheiratetAm": null,
  "gesellschaft": "11",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1967-06-01"),
  "unternehmensaustritt": new Date("1986-05-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1986-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500423,
  "aktuelleStatusgruppe": "Versorgungsausgleich",
  "alteStatusgruppe": null,
  "name": "Antje Weibezahl",
  "adresse": "Soltaus Koppel 15b, 21465 Reinbek",
  "geschlecht": "weiblich",
  "familienstand": "geschieden",
  "geburtsdatum": new Date("1944-06-20"),
  "geheiratetAm": new Date("1969-07-24"),
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1962-11-01"),
  "unternehmensaustritt": new Date("1983-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2013-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500475,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Heidemarie Zietz",
  "adresse": "Büchener Weg 121 a, 21481 Lauenburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1941-04-24"),
  "geheiratetAm": new Date("1965-02-26"),
  "gesellschaft": "11",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1966-04-01"),
  "unternehmensaustritt": new Date("1984-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2003-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 174052,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Ursel Anderseck",
  "adresse": "c/o Maj-Britt Anderseck, Reinsweg 5, 28844 Weyhe",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1936-01-15"),
  "geheiratetAm": null,
  "gesellschaft": "21",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1963-11-15"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "0421-803064"
},

{
  "personalnummer": 138107,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ilse-Frieda Bartels",
  "adresse": "Lange Strasse 16, 28870 Ottersberg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1936-07-25"),
  "geheiratetAm": null,
  "gesellschaft": "21",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-04-01"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1986-11-23"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500301,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Edith Bruck",
  "adresse": "Bahnhofstraße 105, 27711 Osterholz-Scharmbeck",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1936-09-29"),
  "geheiratetAm": null,
  "gesellschaft": "21",
  "versorgungsordnung": 74,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1964-11-23"),
  "unternehmensaustritt": new Date("1986-10-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1986-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 04791-9315548"
},

{
  "personalnummer": 173708,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Heinrich Buss",
  "adresse": "Jeromeweg 8, 31542 Bad Nenndorf",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1940-12-24"),
  "geheiratetAm": null,
  "gesellschaft": "21",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-01-01"),
  "unternehmensaustritt": new Date("1982-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2005-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 175547,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Charlotte Frieben",
  "adresse": "c/o Frau E. Viering, Freiberger Straße 2 G, 28215 Bremen",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1928-05-18"),
  "geheiratetAm": null,
  "gesellschaft": "21",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1968-01-01"),
  "unternehmensaustritt": new Date("1980-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1984-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 500364,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Erna Gabel",
  "adresse": "Lilienthaler Heerstr. 59 A, 28357 Bremen",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1927-08-07"),
  "geheiratetAm": new Date("1951-06-20"),
  "gesellschaft": "21",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1966-03-01"),
  "unternehmensaustritt": new Date("1983-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1983-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 500537,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Margot Gerber",
  "adresse": "Fedderwarder Weg 53, 28197 Bremen",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1937-09-11"),
  "geheiratetAm": new Date("1960-07-08"),
  "gesellschaft": "21",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1960-04-01"),
  "unternehmensaustritt": new Date("1986-02-28"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0421-547 227"
},

{
  "personalnummer": 500230,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Helga Gleitsmann",
  "adresse": "Riessstraße 21, 27721 Ritterhude",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1942-09-29"),
  "geheiratetAm": null,
  "gesellschaft": "21",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1960-10-01"),
  "unternehmensaustritt": new Date("1986-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1989-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 176933,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Helga Gleitsmann",
  "adresse": "Riessstraße 21a, 27721 Ritterhude",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1942-09-29"),
  "geheiratetAm": new Date("1975-08-12"),
  "gesellschaft": "21",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1973-02-01"),
  "unternehmensaustritt": new Date("1985-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2007-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 176016,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Fred Harjes",
  "adresse": "Starnberger Straße 16, 28215 Bremen",
  "geschlecht": "männlich",
  "familienstand": "getrennt lebend",
  "geburtsdatum": new Date("1946-12-02"),
  "geheiratetAm": null,
  "gesellschaft": "21",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-01-01"),
  "unternehmensaustritt": new Date("1987-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2012-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 321174,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Dr. Ekkehard Helms",
  "adresse": "Hermann-Allmers-Str. 26a, 28209 Bremen",
  "geschlecht": "männlich",
  "familienstand": null,
  "geburtsdatum": new Date("1938-06-03"),
  "geheiratetAm": null,
  "gesellschaft": "21",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-09-01"),
  "unternehmensaustritt": new Date("1984-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 176339,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Ursula Lange-David",
  "adresse": "Eislebener Straße 33, 28329 Bremen",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1936-08-31"),
  "geheiratetAm": null,
  "gesellschaft": "21",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1970-02-01"),
  "unternehmensaustritt": new Date("1981-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-09-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 404379,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Brunhilde Launhardt",
  "adresse": "Mittelweg 9, 27356 Rotenburg/Wümme",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1934-10-22"),
  "geheiratetAm": new Date("1957-11-15"),
  "gesellschaft": "21",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1956-05-16"),
  "unternehmensaustritt": new Date("1986-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1988-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 500343,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Lilli Loewner",
  "adresse": "Curiestr 23, 28357 Bremen",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1938-04-18"),
  "geheiratetAm": new Date("1972-12-15"),
  "gesellschaft": "21",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1954-03-11"),
  "unternehmensaustritt": new Date("1976-05-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1980-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0421-272330"
},

{
  "personalnummer": 500436,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Renate Mehrtens",
  "adresse": "Rita-Bardenheuer-Str. 6, 28213 Bremen",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1935-07-11"),
  "geheiratetAm": new Date("1958-08-28"),
  "gesellschaft": "21",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1962-03-01"),
  "unternehmensaustritt": new Date("1985-05-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1987-07-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 186643,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Renate Nieder",
  "adresse": "Lüdenscheider Str. 17, 28199 Bremen",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1927-06-16"),
  "geheiratetAm": null,
  "gesellschaft": "21",
  "versorgungsordnung": 73,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1957-10-01"),
  "unternehmensaustritt": new Date("1978-07-24"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1978-07-25"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 404188,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ingrid Paust",
  "adresse": "Strandweg 8a, 23570 Lübeck",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1938-04-19"),
  "geheiratetAm": new Date("1964-03-26"),
  "gesellschaft": "21",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1964-04-01"),
  "unternehmensaustritt": new Date("1980-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 500407,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ingrid Reiner",
  "adresse": "Scharnhorststraße 13, 27568 Bremerhaven",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1938-01-03"),
  "geheiratetAm": new Date("1959-08-31"),
  "gesellschaft": "21",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1964-05-01"),
  "unternehmensaustritt": new Date("1985-03-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1994-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "0471-4835930"
},

{
  "personalnummer": 173955,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": null,
  "name": "Hinrich Scheper",
  "adresse": "Strandstr. 37, 27638 Wremen",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1930-10-17"),
  "geheiratetAm": null,
  "gesellschaft": "21",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1962-03-01"),
  "unternehmensaustritt": new Date("1987-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-11-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich, 2. Ehefrau, Hinterbliebenenrente prüfen"
},

{
  "personalnummer": 976058,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ingrid Scheper",
  "adresse": "Lange Wenjen 1a, 28357 Bremen",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1937-07-11"),
  "geheiratetAm": new Date("1958-03-21"),
  "gesellschaft": "21",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1953-09-01"),
  "unternehmensaustritt": new Date("1986-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1990-03-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 132688,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Brigitte Schnier",
  "adresse": "Glatzer Straße 20, 27798 Hude 1",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1947-12-22"),
  "geheiratetAm": null,
  "gesellschaft": "21",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1972-04-01"),
  "unternehmensaustritt": new Date("1982-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2013-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 04408-2012"
},

{
  "personalnummer": 173989,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Frieder Schwarz",
  "adresse": "c/o Antje Schwarz, Kreutstr. 102, 28203 Bremen",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1931-07-18"),
  "geheiratetAm": null,
  "gesellschaft": "21",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1960-04-01"),
  "unternehmensaustritt": new Date("1985-04-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1991-08-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 500329,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Christel Stendzina",
  "adresse": "Alfred-Nobel-Str. 15, 55124 Mainz",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1941-08-30"),
  "geheiratetAm": new Date("1962-02-08"),
  "gesellschaft": "21",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1969-11-01"),
  "unternehmensaustritt": new Date("1986-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 06131 47 84 28"
},

{
  "personalnummer": 500467,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Sigrid Thape",
  "adresse": "Hamhofsweg 140B, 28357 Bremen",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1949-01-22"),
  "geheiratetAm": new Date("1973-04-13"),
  "gesellschaft": "21",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1976-02-01"),
  "unternehmensaustritt": new Date("1987-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2012-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 310615,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Aktive mit vereinbartem Vorruhestand",
  "name": "Gerhard Kayser",
  "adresse": "Linsenkamp 13, 22175 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1934-12-14"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 71,
  "arbVerhRentTr": "10",
  "unternehmenseintritt": new Date("1965-07-01"),
  "unternehmensaustritt": new Date("1997-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1998-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 040/640 05 52"
},

{
  "personalnummer": 122846,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Günther Klahn",
  "adresse": "Ahrensburger Str. 38 B, 22041 Hamburg 70",
  "geschlecht": "männlich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1939-04-26"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 76,
  "arbVerhRentTr": "10",
  "unternehmenseintritt": new Date("1971-08-01"),
  "unternehmensaustritt": new Date("1994-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1999-05-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 401176,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Sigrid Kneesch",
  "adresse": "Hafenstraße 8, 25436 Uetersen",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1940-01-25"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 86,
  "arbVerhRentTr": "10",
  "unternehmenseintritt": new Date("1990-08-16"),
  "unternehmensaustritt": new Date("1997-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 338129,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Karin Knuth",
  "adresse": "Kanaltwiete 2, 23795 Bad Segeberg",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date("1939-05-20"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 76,
  "arbVerhRentTr": "10",
  "unternehmenseintritt": new Date("1972-07-01"),
  "unternehmensaustritt": new Date("1994-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1999-06-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 0171 615 27 64"
},

{
  "personalnummer": 976061,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": null,
  "name": "Ursula Krauß",
  "adresse": "Uferstr. 12, 22081 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1938-08-19"),
  "geheiratetAm": new Date("1962-09-14"),
  "gesellschaft": "90",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1978-07-01"),
  "unternehmensaustritt": new Date("1996-09-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1996-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 337329,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Ilse Langsdorff",
  "adresse": "Goldbekufer 9, 22303 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "geschieden",
  "geburtsdatum": new Date("1945-10-12"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1971-04-01"),
  "unternehmensaustritt": new Date("1994-06-30"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2005-12-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 132522,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Horst Lehmann",
  "adresse": "Im Wiesengrund 25, 25474 Ellerbek",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1935-11-03"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 74,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1962-05-01"),
  "unternehmensaustritt": new Date("1995-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1997-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 169144,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Aktive mit zugesagter Betriebsrente",
  "name": "Carsten Lüßmann",
  "adresse": "Lütt Heesen 5, 21033 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verwitwet",
  "geburtsdatum": new Date("1941-03-09"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date("1987-08-01"),
  "unternehmensaustritt": new Date("2001-03-31"),
  "ruhegeldfaehigAb": new Date("1969-04-01"),
  "rentenbeginn": new Date("2001-04-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
},

{
  "personalnummer": 336982,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Karin Marten",
  "adresse": "Eichenkamp 1, 24558 Wakendorf",
  "geschlecht": "weiblich",
  "familienstand": "geschieden",
  "geburtsdatum": new Date("1939-12-18"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 75,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1960-04-01"),
  "unternehmensaustritt": new Date("1994-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2000-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "VA - Telefon: 04535 8861"
},

{
  "personalnummer": 322131,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Walter Mumm",
  "adresse": "Sachsenweg 26 A, 22455 Hamburg 61",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1943-12-12"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 76,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1973-01-01"),
  "unternehmensaustritt": new Date("1997-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2004-01-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 551 57 71"
},

{
  "personalnummer": 310011,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Inge Parczany",
  "adresse": "Scharpenmoor 67, 22848 Norderstedt",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1941-01-20"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 76,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1981-04-01"),
  "unternehmensaustritt": new Date("1997-12-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("2001-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 523 71 23"
},

{
  "personalnummer": 310680,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Bernd Raloff",
  "adresse": "Riesstraße 21, 27721 Ritterhude",
  "geschlecht": "männlich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1939-09-28"),
  "geheiratetAm": new Date("1994-11-30"),
  "gesellschaft": "90",
  "versorgungsordnung": 71,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1970-12-01"),
  "unternehmensaustritt": new Date("1995-08-31"),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date("1999-10-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Versorgungsausgleich/2. Ehe 11/94"
},

{
  "personalnummer": 338921,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Margit Schlarp",
  "adresse": "Untere Torstraße 13, 74613 Öhringen",
  "geschlecht": "weiblich",
  "familienstand": "verheiratet",
  "geburtsdatum": new Date("1943-01-02"),
  "geheiratetAm": null,
  "gesellschaft": "90",
  "versorgungsordnung": 76,
  "arbVerhRentTr": 10,
  "unternehmenseintritt": new Date("1979-01-08"),
  "unternehmensaustritt": new Date("1997-06-30"),
  "ruhegeldfaehigAb": new Date("1979-01-01"),
  "rentenbeginn": new Date("2003-02-01"),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": null
}








    
              ];

// Axios POST request function
// Axios POST request function
async function insertData() {
  for (let i = 0; i < dataToInsert.length; i++) {
    const person = dataToInsert[i];

    try {
      const response = await axios.post(
        "http://localhost:4000/api/person",
        person
      );

      console.log(`✔️ Inserted personalnummer ${person.personalnummer}`);
    } catch (error) {
      // Wenn der Server geantwortet hat (HTTP-Fehlercode)
      if (error.response) {
        // 400 = existiert schon (so wie du es in deiner Route gebaut hast)
        if (error.response.status === 400) {
          console.warn(
            `⚠️ personalnummer ${person.personalnummer} exists – skipped`
          );
          continue; // optional, macht nur explizit "weiter" zur nächsten Person
        }

        // Andere HTTP-Fehler
        console.error(
          `❌ HTTP ${error.response.status} for personalnummer ${person.personalnummer}:`,
          error.response.data
        );
      } else {
        // Kein Response = z.B. Netzwerkfehler / Server nicht erreichbar
        console.error(
          `❌ Network/Unknown error for personalnummer ${person.personalnummer}:`,
          error.message
        );
      }
    }
  }

  console.log("✅ Import finished.");
}


// Call the function to insert data
insertData();