const axios = require('axios');

const dataToInsert = [

	{
        "personalnummer": 136093,
        "aktuelleStatusgruppe": "Altersrentner",
        "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
        "name": "Rudolf Aberle",
        "adresse": "Höhenringstraße 10, 82256 Fürstenfeldbruck",
        "geschlecht": "männlich",
        "familienstand": "verh.",
        "geburtsdatum": new Date('1940-02-12'),
        "geheiratetAm": null,
        "gesellschaft": "81A",
        "versorgungsordnung": 76,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1971-10-01'),
        "unternehmensaustritt": new Date('1984-06-22'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('2004-10-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": ""
    },
	
	{
        "personalnummer": 100939,
        "aktuelleStatusgruppe": "Verstorbene",
        "alteStatusgruppe": "Altersrentner",
        "name": "Peter Antoni",
        "adresse": "Mellenbergstieg 7, 22359 Hamburg",
        "geschlecht": "männlich",
        "familienstand": "verh.",
        "geburtsdatum": new Date('1940-05-19'),
        "geheiratetAm": null,
        "gesellschaft": "81A",
        "versorgungsordnung": 79,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1970-01-01'),
        "unternehmensaustritt": new Date('1980-02-29'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('2003-11-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "Telefon: 040/519 06613"
    },
	
	{
        "personalnummer": 131159,
        "aktuelleStatusgruppe": "Altersrentner",
        "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
        "name": "Gabriele Balke",
        "adresse": "An der Au 2, 25376 Borsfleth",
        "geschlecht": "weiblich",
        "familienstand": "verh.",
        "geburtsdatum": new Date('1952-09-14'),
        "geheiratetAm": null,
        "gesellschaft": "81A",
        "versorgungsordnung": 76,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1972-10-01'),
        "unternehmensaustritt": new Date('1988-12-24'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('2013-11-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": ""
    },
	
	{
        "personalnummer": 500536,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Gisela Becker",
        "adresse": "Borchlingweg 44, 22605 Hamburg",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1942-12-22'),
        "geheiratetAm": new Date('1988-08-18'),
        "gesellschaft": "81A",
        "versorgungsordnung": 71,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1960-03-01'),
        "unternehmensaustritt": new Date('1991-07-31'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('1991-08-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "Versorgungsausgleich ? Telefon: 881 05 94"
    },
	
	{
        "personalnummer": 976031,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Ellen Behrens",
        "adresse": "Albert-Schweitzer-Weg 9, 27777 Ganderkesee",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1941-06-26'),
        "geheiratetAm": new Date('1965-10-21'),
        "gesellschaft": "81A",
        "versorgungsordnung": 71,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1967-01-01'),
        "unternehmensaustritt": new Date('1985-06-20'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('2022-03-04'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": ""
    },
	
	{
        "personalnummer": 500359,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Helga Benecke",
        "adresse": "Schulenburgring 1a, 21031 Hamburg",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1934-10-16'),
        "geheiratetAm": new Date('1953-08-01'),
        "gesellschaft": "81A",
        "versorgungsordnung": 73,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1960-03-01'),
        "unternehmensaustritt": new Date('1984-02-29'),
        "ruhegeldfaehigAb": new Date('1959-06-01'),
        "rentenbeginn": new Date('1988-03-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "Telefon: 738 43 74 3 Kinder, 1 Neuseeland"
    },
    {
        "personalnummer": 139717,
        "aktuelleStatusgruppe": "Altersrentner",
        "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
        "name": "Hans-Peter Berger",
        "adresse": "An der Rehwiese 51, 21614 Buxtehude",
        "geschlecht": "männlich",
        "familienstand": "gesch.",
        "geburtsdatum": new Date('1940-07-21'),
        "geheiratetAm": null,
        "gesellschaft": "81A",
        "versorgungsordnung": 77,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1968-11-16'),
        "unternehmensaustritt": new Date('1992-04-30'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('2005-08-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "Versorgungsausgleich"
    },
    {
        "personalnummer": 404165,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Elisabeth Beyn",
        "adresse": "Am Feenteich 1, 22085 Hamburg",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1925-12-30'),
        "geheiratetAm": new Date('1959-03-26'),
        "gesellschaft": "81G",
        "versorgungsordnung": 72,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1969-06-01'),
        "unternehmensaustritt": new Date('1977-06-30'),
        "ruhegeldfaehigAb": new Date('1954-03-01'),
        "rentenbeginn": new Date('1977-07-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": ""
    },
    {
        "personalnummer": 310235,
        "aktuelleStatusgruppe": "Altersrentner",
        "alteStatusgruppe": "Erwerbs- bzw. Berufsunfähigkeitsrentner",
        "name": "Dr. Klaus-Jürgen Biertz",
        "adresse": "Ohkamp 36, 22399 Hamburg",
        "geschlecht": "männlich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1932-06-23'),
        "geheiratetAm": null,
        "gesellschaft": "81A",
        "versorgungsordnung": 71,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1969-07-01'),
        "unternehmensaustritt": new Date('1986-06-30'),
        "ruhegeldfaehigAb": new Date('1959-08-01'),
        "rentenbeginn": new Date('1990-07-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "5382828"
    },
	
	{
        "personalnummer": 403438,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Elvira Blasy",
        "adresse": "c/o Gerokheim, Mömpelgardstraße 8/1, 71640 Ludwigsburg",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1939-11-29'),
        "geheiratetAm": new Date('1994-06-17'),
        "gesellschaft": "81A",
        "versorgungsordnung": 77,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1970-04-01'),
        "unternehmensaustritt": new Date('1980-06-27'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('1995-06-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "2. Ehe mit 1. Frau"
    },
    {
        "personalnummer": 131722,
        "aktuelleStatusgruppe": "Altersrentner",
        "alteStatusgruppe": "---",
        "name": "Helga Bleisz",
        "adresse": "Straßweg 2, 22607 Hamburg",
        "geschlecht": "weiblich",
        "familienstand": "ledig",
        "geburtsdatum": new Date('1929-09-05'),
        "geheiratetAm": null,
        "gesellschaft": "81A",
        "versorgungsordnung": 71,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1966-04-15'),
        "unternehmensaustritt": new Date('1989-09-30'),
        "ruhegeldfaehigAb": new Date('1966-04-01'),
        "rentenbeginn": new Date('1989-10-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": ""
    },
    {
        "personalnummer": 500347,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Beate Boche",
        "adresse": "Asmusweg 8, 22043 Hamburg",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1949-06-25'),
        "geheiratetAm": new Date('1972-08-05'),
        "gesellschaft": "81A",
        "versorgungsordnung": 77,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1967-09-01'),
        "unternehmensaustritt": new Date('1982-12-31'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('2003-09-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "Telefon: 652 92 79"
    },
    {
        "personalnummer": 500183,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Brigitte Bohlen",
        "adresse": "c/o Herrn J. Schmidt (Betreuungsverein), Papenstraße 27, 22089 Hamburg",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1932-02-10'),
        "geheiratetAm": new Date('1966-11-11'),
        "gesellschaft": "81A",
        "versorgungsordnung": 76,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1971-04-01'),
        "unternehmensaustritt": new Date('1984-12-31'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('1987-02-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": ""
    },
    {
        "personalnummer": 976014,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Bärbel Böhmer",
        "adresse": "Heimatring 44, 60596 Frankfurt",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1935-04-05'),
        "geheiratetAm": new Date('1960-09-16'),
        "gesellschaft": "81A",
        "versorgungsordnung": 76,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1975-08-01'),
        "unternehmensaustritt": new Date('1986-12-31'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('1992-02-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "Telefon: 069 634 725"
    },
    {
        "personalnummer": 104703,
        "aktuelleStatusgruppe": "Altersrentner",
        "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
        "name": "Rolf Bongardt",
        "adresse": "Holzdamm 2B, 50374 Erftstadt",
        "geschlecht": "männlich",
        "familienstand": "verh.",
        "geburtsdatum": new Date('1941-10-28'),
        "geheiratetAm": null,
        "gesellschaft": "81A",
        "versorgungsordnung": 76,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1971-01-15'),
        "unternehmensaustritt": new Date('1990-09-30'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('2006-11-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": ""
    },
    {
        "personalnummer": 500225,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Brigitte Brandt",
        "adresse": "Ilmenauer Weg 2, 37075 Göttingen",
        "geschlecht": "weiblich",
        "familienstand": "verh.",
        "geburtsdatum": new Date('1931-04-22'),
        "geheiratetAm": new Date('1974-11-15'),
        "gesellschaft": "81A",
        "versorgungsordnung": 77,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1969-03-01'),
        "unternehmensaustritt": new Date('1984-08-31'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('1987-10-01'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": ""
    },
    {
        "personalnummer": 500567,
        "aktuelleStatusgruppe": "Hinterbliebene",
        "alteStatusgruppe": "---",
        "name": "Edith Braun",
        "adresse": "Bayerwaldstr. 20, 81737 München",
        "geschlecht": "weiblich",
        "familienstand": "verw.",
        "geburtsdatum": new Date('1930-09-08'),
        "geheiratetAm": new Date('1953-08-07'),
        "gesellschaft": "51",
        "versorgungsordnung": 77,
        "arbVerhRentTr": null,
        "unternehmenseintritt": new Date('1968-01-01'),
        "unternehmensaustritt": new Date('1983-09-30'),
        "ruhegeldfaehigAb": null,
        "rentenbeginn": new Date('1984-07-21'),
        "zusagedatum": null,
        "verstorbenAm": null,
        "bemerkung": "Telefon: 0151 251 15 975"
    },
    
   
{
  "personalnummer": 500255,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Burmester",
  "adresse": "Dalldorf 1, 29562 Suhlendorf",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1938-09-27'),
  "geheiratetAm": new Date('1961-01-07'),
  "gesellschaft": "81A",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1974-01-01'),
  "unternehmensaustritt": new Date('1984-01-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1999-08-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 403931,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Conrad",
  "adresse": "Taunusstraße 89, 65835 Liederbach",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1929-09-02'),
  "geheiratetAm": new Date('1977-03-18'),
  "gesellschaft": "81A",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1969-07-01'),
  "unternehmensaustritt": new Date('1984-03-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1984-04-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "06196-26198"
},
{
  "personalnummer": 404932,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Damske",
  "adresse": "Ostermeyerstraße 25, 22607 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1935-09-27'),
  "geheiratetAm": new Date('1972-07-12'),
  "gesellschaft": "81A",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1961-10-01'),
  "unternehmensaustritt": new Date('1984-12-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1986-11-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "040/819 917 43"
},
{
  "personalnummer": 313650,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Del Re",
  "adresse": "c/o Rosenhof, App. 544, Lübecker Straße 3-11, 22926 Ahrensburg",
  "geschlecht": "weiblich",
  "familienstand": "gesch.",
  "geburtsdatum": new Date('1935-03-30'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1980-04-01'),
  "unternehmensaustritt": new Date('1990-12-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1995-04-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 310854,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Denker",
  "adresse": "Parkstieg 6, 22143 Hamburg",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date('1939-03-17'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1971-01-01'),
  "unternehmensaustritt": new Date('1991-12-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('2004-04-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Tel. 6471093 01724517244"
},

{
  "personalnummer": 500535,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Dohle",
  "adresse": "Veilchenweg 21, 40670 Meerbusch",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1948-09-26'),
  "geheiratetAm": new Date('1971-05-28'),
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1973-10-01'),
  "unternehmensaustritt": new Date('1984-12-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('2009-08-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 104885,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Dohmen",
  "adresse": "Kollwitzstraße 20, 52134 Herzogenrath",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date('1940-09-07'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1974-01-15'),
  "unternehmensaustritt": new Date('1984-06-30'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('2005-10-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 500437,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Dragt",
  "adresse": "Breul 16, 48143 Münster",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1941-08-31'),
  "geheiratetAm": new Date('1973-11-16'),
  "gesellschaft": "81A",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1970-01-01'),
  "unternehmensaustritt": new Date('1983-09-30'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1993-01-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},

{
  "personalnummer": 310961,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Drewski",
  "adresse": "Archenholzstraße 28, 22117 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1940-04-16'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1970-03-01'),
  "unternehmensaustritt": new Date('1995-06-30'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('2000-05-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 732 17 75"
},
{
  "personalnummer": 314864,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Ehlers",
  "adresse": "Residenz am Wiesenkamp, Wiesenkamp 16, 22359 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1935-12-09'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1973-10-01'),
  "unternehmensaustritt": new Date('1984-04-14'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1984-04-15'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 136200,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Frühpensionäre",
  "name": "Ehrke-Mösing",
  "adresse": "Salinenstraße 33, 23843 Bad Oldesloe",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date('1938-12-11'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1972-04-01'),
  "unternehmensaustritt": new Date('1993-12-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1999-01-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Eheschließung nach VA, Telefon: 04531 808 69 33"
},
{
  "personalnummer": 116129,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Engelbrecht",
  "adresse": "Luitpoldstraße 25, 83435 Bad Reichenhall",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date('1938-08-24'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1972-11-01'),
  "unternehmensaustritt": new Date('1984-08-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('2003-09-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 403448,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Engels",
  "adresse": "Abteiweg 61, 41468 Neuss",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1930-08-11'),
  "geheiratetAm": new Date('1955-08-16'),
  "gesellschaft": "81A",
  "versorgungsordnung": 71,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1959-07-01'),
  "unternehmensaustritt": new Date('1985-06-30'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1989-05-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 311142,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "---",
  "name": "Fellenz",
  "adresse": "Lokstedter Steindamm 16a, 22529 Hamburg",
  "geschlecht": "weiblich",
  "familienstand": "ledig",
  "geburtsdatum": new Date('1931-10-24'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 75,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1969-04-01'),
  "unternehmensaustritt": new Date('1989-03-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1991-11-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 560 21 23"
},
{
  "personalnummer": 500385,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Fischer",
  "adresse": "Lilienthalstraße 8, 38518 Gifhorn",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1939-06-19'),
  "geheiratetAm": new Date('1964-12-04'),
  "gesellschaft": "81A",
  "versorgungsordnung": 76,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1970-12-09'),
  "unternehmensaustritt": new Date('1983-06-30'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1990-05-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 125104,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Foulon",
  "adresse": "Heinrichstraße 33, 64283 Darmstadt",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date('1940-04-16'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1961-04-10'),
  "unternehmensaustritt": new Date('1976-03-31'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('2000-05-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 136192,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "---",
  "name": "Fraßdorf",
  "adresse": "Hagenauer Straße 16, 81479 München",
  "geschlecht": "männlich",
  "familienstand": "verh.",
  "geburtsdatum": new Date('1930-03-29'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1975-01-01'),
  "unternehmensaustritt": new Date('1978-09-30'),
  "ruhegeldfaehigAb": new Date('1967-10-01'),
  "rentenbeginn": new Date('1993-01-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "2. Ehe ???!!!!!!"
},
{
  "personalnummer": 500261,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Freitag",
  "adresse": "Waldstraße 4, 23683 Scharbeutz",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1926-04-22'),
  "geheiratetAm": new Date('1954-07-17'),
  "gesellschaft": "81A",
  "versorgungsordnung": 77,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1968-04-01'),
  "unternehmensaustritt": new Date('1983-06-30'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1987-11-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
},
{
  "personalnummer": 500443,
  "aktuelleStatusgruppe": "Hinterbliebene",
  "alteStatusgruppe": "---",
  "name": "Friedberg",
  "adresse": "Hanfstaenglstr. 1, 80638 München",
  "geschlecht": "weiblich",
  "familienstand": "verw.",
  "geburtsdatum": new Date('1928-03-22'),
  "geheiratetAm": new Date('1955-06-04'),
  "gesellschaft": "81A",
  "versorgungsordnung": 79,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1968-02-01'),
  "unternehmensaustritt": new Date('1979-06-30'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('1991-03-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": "Telefon: 089 8114999"
},
{
  "personalnummer": 132530,
  "aktuelleStatusgruppe": "Altersrentner",
  "alteStatusgruppe": "Ausgeschiedene mit unverfallbarem Anspruch",
  "name": "Garbe",
  "adresse": "Waldwinkel 2, 21220 Seevetal",
  "geschlecht": "weiblich",
  "familienstand": "verh.",
  "geburtsdatum": new Date('1945-07-04'),
  "geheiratetAm": null,
  "gesellschaft": "81A",
  "versorgungsordnung": 78,
  "arbVerhRentTr": null,
  "unternehmenseintritt": new Date('1966-05-01'),
  "unternehmensaustritt": new Date('1982-08-01'),
  "ruhegeldfaehigAb": null,
  "rentenbeginn": new Date('2008-08-01'),
  "zusagedatum": null,
  "verstorbenAm": null,
  "bemerkung": ""
}




];

// Axios POST request function
// Axios POST request function
async function insertData() {
  for (let i = 0; i < dataToInsert.length; i++) {
    const person = dataToInsert[i];

    try {
      const response = await axios.post(
        "http://localhost:4000/api/person",
        person
      );

      console.log(`✔️ Inserted personalnummer ${person.personalnummer}`);
    } catch (error) {
      // Wenn der Server geantwortet hat (HTTP-Fehlercode)
      if (error.response) {
        // 400 = existiert schon (so wie du es in deiner Route gebaut hast)
        if (error.response.status === 400) {
          console.warn(
            `⚠️ personalnummer ${person.personalnummer} exists – skipped`
          );
          continue; // optional, macht nur explizit "weiter" zur nächsten Person
        }

        // Andere HTTP-Fehler
        console.error(
          `❌ HTTP ${error.response.status} for personalnummer ${person.personalnummer}:`,
          error.response.data
        );
      } else {
        // Kein Response = z.B. Netzwerkfehler / Server nicht erreichbar
        console.error(
          `❌ Network/Unknown error for personalnummer ${person.personalnummer}:`,
          error.message
        );
      }
    }
  }

  console.log("✅ Import finished.");
}


// Call the function to insert data
insertData();

